import { loginAdmin, redirectIfAdmin } from './admin-auth.js?v=20260904-persistent-aal2-1&sb=20260823-security-supabase-pin-1';
const $=id=>document.getElementById(id);
function say(text='',ok=false){const message=$('msg');if(!message)return;message.textContent=text;message.classList.toggle('ok',ok);}
window.addEventListener('error',event=>say('Erro: '+event.message));window.addEventListener('unhandledrejection',event=>say('Erro: '+(event.reason?.message||event.reason)));
/* Contenção local de UX. A segurança real é Auth + autoridade server-side + módulos/capabilities. Founder adiciona MFA/AAL2. */
localStorage.removeItem('echoarena_admin_attempts');const RL_KEY='echoarena_admin_attempts_v2',MAX_TRIES=5,LOCK_MS=15*60*1000;
function readAttempts(){try{return JSON.parse(localStorage.getItem(RL_KEY))||{n:0,until:0};}catch{return{n:0,until:0};}}
function lockedSeconds(){const attempt=readAttempts();return attempt.until>Date.now()?Math.ceil((attempt.until-Date.now())/1000):0;}
function registerFail(){const attempt=readAttempts();attempt.n+=1;if(attempt.n>=MAX_TRIES){attempt.until=Date.now()+LOCK_MS;attempt.n=0;}localStorage.setItem(RL_KEY,JSON.stringify(attempt));}
function resetAttempts(){localStorage.removeItem(RL_KEY);}let running=false,checkingSession=true;
async function enter(){if(running||checkingSession)return;const wait=lockedSeconds();if(wait){say(`Muitas tentativas neste navegador. Aguarde ${Math.ceil(wait/60)} minuto(s).`);return;}const email=$('email').value.trim(),password=$('password').value;if(!email||!password){say('Preencha e-mail e senha.');return;}running=true;$('login').disabled=true;$('login').textContent='Entrando...';say('');try{const result=await loginAdmin(email,password);resetAttempts();if(result.needsMfa){say('Conta Founder confirmada. Segundo fator obrigatório...',true);location.replace('./mfa.html');return;}say(result.reusedSession?'Sessão segura reconhecida. Abrindo o painel...':'Acesso administrativo confirmado. Abrindo o painel...',true);location.replace('./index.html');}catch(error){registerFail();await new Promise(resolve=>setTimeout(resolve,700));const raw=error?.message||String(error);say(raw==='Invalid login credentials'?'E-mail ou senha incorretos.':raw);console.error('[login]',error);}finally{running=false;$('login').disabled=false;$('login').textContent='Entrar';}}
$('login')?.addEventListener('click',enter);['email','password'].forEach(id=>{$(id)?.addEventListener('keydown',event=>{if(event.key==='Enter')enter();});});say('Verificando sessão...');if($('login'))$('login').disabled=true;redirectIfAdmin('./index.html').then(redirected=>{checkingSession=false;if(!redirected){$('login').disabled=false;say('');}}).catch(error=>{checkingSession=false;$('login').disabled=false;console.error('[login] falha ao verificar sessão:',error);say('');});
