import { supabase } from '../../js/supabase.js?v=20260823-security-supabase-pin-1';
import { initAdminShell } from './admin-shell.js?v=20260906-home-featured-phase-e-1&sb=20260823-security-supabase-pin-1&sc=20260906-1';

const shell=await initAdminShell({activeId:'community-hub',pageTitle:'Comunidade',pageSubtitle:'Moderação contextual · atividade real'});
if(!shell) throw new Error('Admin Shell indisponível.');
const state={posts:[],profiles:new Map(),pulse:new Map(),filter:'active',search:''};
const $=id=>document.getElementById(id);const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[ch]));const norm=value=>String(value??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();const fmt=value=>{const d=new Date(value);return Number.isNaN(d.getTime())?'—':d.toLocaleString('pt-BR',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'});};const kindLabel=value=>({discussion:'Discussão',question:'Pergunta',tip:'Dica',showcase:'Showcase'})[value]||value;
function message(text='',type=''){const n=$('community-admin-message');if(!n)return;n.textContent=text;n.className=`community-admin-message ${text?'is-visible':''} ${type}`.trim();}
function author(id){const p=state.profiles.get(id);return p?.display_name||p?.username||'Jogador';}
function renderMetrics(){$('community-admin-active').textContent=state.posts.filter(p=>p.status==='active').length;$('community-admin-hidden').textContent=state.posts.filter(p=>p.status==='hidden').length;$('community-admin-replies').textContent=state.posts.reduce((s,p)=>s+Number(p.reply_count||0),0);$('community-admin-reactions').textContent=state.posts.reduce((s,p)=>s+Number(p.reaction_count||0),0);}
function context(post){if(post.pulse_item_id&&state.pulse.has(post.pulse_item_id))return `Pulse · ${state.pulse.get(post.pulse_item_id).title}`;if(post.hero_id)return 'Herói vinculado';if(post.build_id)return 'Build vinculada';return 'Conversa geral';}
function actions(post){const parts=[];if(post.status==='active')parts.push(`<button class="danger" data-status="hidden" data-id="${post.id}" type="button">Ocultar</button>`);if(post.status==='hidden')parts.push(`<button class="ok" data-status="active" data-id="${post.id}" type="button">Restaurar</button>`);if(post.status!=='deleted')parts.push(`<button data-pin="${post.id}" data-value="${post.is_pinned?'false':'true'}" type="button">${post.is_pinned?'Desafixar':'Fixar'}</button>`);parts.push(`<a href="../comunidade.html?post=${encodeURIComponent(post.id)}" target="_blank" rel="noopener noreferrer">Abrir conversa ↗</a>`);return parts.join('');}
function render(){const term=norm(state.search);const visible=state.posts.filter(post=>(state.filter==='all'||post.status===state.filter)&&(!term||norm(`${post.title||''} ${post.body} ${author(post.author_id)} ${context(post)}`).includes(term)));const root=$('community-admin-list'),empty=$('community-admin-state');if(!root||!empty)return;if(!visible.length){root.innerHTML='';empty.hidden=false;empty.textContent=state.posts.length?'Nenhuma conversa corresponde a este filtro.':'A comunidade ainda não possui conversas. Nenhum conteúdo de demonstração foi criado.';return;}empty.hidden=true;root.innerHTML=visible.map(post=>`<article class="community-admin-card ${post.status==='hidden'?'hidden':''}"><div class="community-admin-card-head"><div><div class="community-admin-meta"><span class="community-admin-chip">${esc(kindLabel(post.kind))}</span><span class="community-admin-chip ${post.status==='hidden'?'hidden':''}">${esc(post.status)}</span>${post.is_pinned?'<span class="community-admin-chip pinned">Fixada</span>':''}<span class="community-admin-chip">${esc(context(post))}</span></div><h3>${esc(post.title||post.body.slice(0,90))}</h3><p>${esc(post.body)}</p><div class="community-admin-byline">${esc(author(post.author_id))} · ${esc(fmt(post.created_at))}</div></div><div class="community-admin-stats"><span>${Number(post.reply_count||0)} respostas</span><span>${Number(post.reaction_count||0)} reações</span></div></div><div class="community-admin-actions">${actions(post)}</div></article>`).join('');bindActions();}
async function updatePost(id,patch,success){const {error}=await supabase.from('community_posts').update(patch).eq('id',id);if(error){message(error.message||'Falha na moderação.','error');return;}message(success,'ok');await load();}
function bindActions(){document.querySelectorAll('[data-status][data-id]').forEach(btn=>btn.addEventListener('click',()=>updatePost(btn.dataset.id,{status:btn.dataset.status},btn.dataset.status==='hidden'?'Conversa ocultada.':'Conversa restaurada.')));document.querySelectorAll('[data-pin]').forEach(btn=>btn.addEventListener('click',()=>updatePost(btn.dataset.pin,{is_pinned:btn.dataset.value==='true'},btn.dataset.value==='true'?'Conversa fixada.':'Conversa desafixada.')));}
async function load(){try{const {data,error}=await supabase.from('community_posts').select('*').order('is_pinned',{ascending:false}).order('created_at',{ascending:false}).limit(200);if(error)throw error;state.posts=data||[];const authors=[...new Set(state.posts.map(p=>p.author_id).filter(Boolean))],pulseIds=[...new Set(state.posts.map(p=>p.pulse_item_id).filter(Boolean))];const tasks=[];if(authors.length)tasks.push(supabase.from('profiles').select('id,display_name,username').in('id',authors).then(({data})=>state.profiles=new Map((data||[]).map(row=>[row.id,row]))));else state.profiles=new Map();if(pulseIds.length)tasks.push(supabase.from('pulse_items').select('id,title').in('id',pulseIds).then(({data})=>state.pulse=new Map((data||[]).map(row=>[row.id,row]))));else state.pulse=new Map();await Promise.all(tasks);renderMetrics();render();}catch(error){console.error('[community-admin] falha:',error);message(error.message||'Não foi possível carregar a comunidade.','error');}}
$('community-admin-search')?.addEventListener('input',event=>{state.search=event.target.value||'';render();});document.querySelectorAll('[data-filter]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(item=>item.classList.remove('is-active'));btn.classList.add('is-active');state.filter=btn.dataset.filter||'active';render();}));await load();
