const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const fmtDate=v=>v?new Date(v).toLocaleString('pt-BR'):'—';
const PRESETS={hero:{label:'Curador de Heróis',modules:['dashboard','heroes','moderation']},equipment:{label:'Curador de Equipamentos',modules:['dashboard','equipment','moderation']},moderator:{label:'Moderador',modules:['dashboard','moderation']},publisher:{label:'Admin de Conteúdo',modules:['dashboard','publishing','moderation']},quality:{label:'Qualidade de Dados',modules:['dashboard','quality']},intelligence:{label:'Operador de Inteligência',modules:['dashboard','intelligence','quality']}};
export async function initFounderCenter({supabase,access}){
 if(!access?.is_founder){document.querySelector('.fc').innerHTML='<div class="fc-empty">Acesso exclusivo do Founder.</div>';return;}
 const $=s=>document.querySelector(s),els={msg:$('#fc-message'),staff:$('#fc-staff'),detail:$('#fc-detail'),audit:$('#fc-audit'),integrity:$('#fc-integrity'),modal:$('#fc-modal'),modalBody:$('#fc-modal-body'),modalTitle:$('#fc-modal-title'),modalSubtitle:$('#fc-modal-subtitle'),teamSearch:$('#fc-team-search'),teamFilter:$('#fc-team-filter'),auditSearch:$('#fc-audit-search'),auditModule:$('#fc-audit-module'),integrityFilter:$('#fc-integrity-filter')};
 const state={modules:[],staff:[],grants:[],profiles:new Map(),audit:[],signals:[],selected:null,tab:'permissions'};
 const message=(text,tone='')=>{els.msg.textContent=text;els.msg.dataset.tone=tone;};
 const memberName=id=>{const p=state.profiles.get(id);return p?.display_name||p?.username||id?.slice(0,8)||'Sistema';};
 const memberHandle=id=>state.profiles.get(id)?.username||'';
 const getMember=id=>state.staff.find(s=>s.user_id===id);
 const grantSet=id=>new Set(state.grants.filter(g=>g.user_id===id).map(g=>g.module_key));
 async function load(){message('Atualizando governança…');const [mods,staff,grants,directory,audit,signals]=await Promise.all([
   supabase.from('admin_modules').select('module_key,label,description,sort_order').eq('is_active',true).order('sort_order'),
   supabase.from('admin_staff_memberships').select('*').order('created_at'),
   supabase.from('admin_staff_module_grants').select('*'),
   supabase.rpc('echo_founder_staff_directory',{p_query:'',p_limit:50}),
   supabase.from('admin_audit_events').select('id,actor_user_id,actor_kind,module_key,capability_key,action,target_type,target_id,reason,aal,created_at').order('created_at',{ascending:false}).limit(300),
   supabase.from('admin_integrity_signals').select('*').order('created_at',{ascending:false}).limit(100)
 ]);for(const r of[mods,staff,grants,directory,audit,signals])if(r.error)throw r.error;state.modules=mods.data||[];state.staff=staff.data||[];state.grants=grants.data||[];for(const p of directory.data||[])state.profiles.set(p.user_id,p);state.audit=audit.data||[];state.signals=signals.data||[];renderAll();message('Governança atualizada.','success');}
 function stats(){const nonFounder=state.staff.filter(s=>s.staff_label!=='Founder'),active=nonFounder.filter(s=>s.active),inactive=nonFounder.filter(s=>!s.active),open=state.signals.filter(s=>s.status==='open');$('#fc-stat-team').textContent=String(nonFounder.length);$('#fc-stat-active').textContent=String(active.length);$('#fc-stat-inactive').textContent=String(inactive.length);$('#fc-stat-signals').textContent=String(open.length);}
 function statusOf(s){if(s.staff_label==='Founder')return['Founder','active'];if(s.revoked_at)return['Revogado','revoked'];if(!s.active)return['Suspenso','suspended'];return['Ativo','active'];}
 function renderStaff(){const q=els.teamSearch.value.trim().toLowerCase(),filter=els.teamFilter.value;const rows=state.staff.filter(s=>{const status=statusOf(s)[1],match=!q||memberName(s.user_id).toLowerCase().includes(q)||memberHandle(s.user_id).toLowerCase().includes(q)||s.staff_label.toLowerCase().includes(q);const ok=filter==='all'||(filter==='active'&&status==='active')||(filter==='inactive'&&status!=='active');return match&&ok;});els.staff.innerHTML=rows.map(s=>{const [status,tone]=statusOf(s),mods=s.staff_label==='Founder'?['Todos os módulos']:[...grantSet(s.user_id)];return `<button type="button" class="fc-member ${state.selected===s.user_id?'is-selected':''}" data-user="${s.user_id}"><div class="fc-member-top"><strong>${esc(memberName(s.user_id))}${s.staff_label==='Founder'?' · FUNDADOR':''}</strong><span class="fc-status ${tone}">${status}</span></div><small>${esc(s.staff_label)}${memberHandle(s.user_id)?` · @${esc(memberHandle(s.user_id))}`:''}</small><div class="fc-badges">${mods.slice(0,4).map(m=>`<span class="fc-chip">${esc(m)}</span>`).join('')}${mods.length>4?`<span class="fc-chip">+${mods.length-4}</span>`:''}</div></button>`}).join('')||'<div class="fc-empty">Nenhum membro encontrado.</div>';els.staff.querySelectorAll('[data-user]').forEach(b=>b.onclick=()=>{state.selected=b.dataset.user;state.tab='permissions';renderStaff();renderDetail();});}
 function personHeader(s){const p=state.profiles.get(s.user_id)||{},initial=memberName(s.user_id).slice(0,1).toUpperCase(),avatar=p.avatar_url?`<img class="fc-avatar" src="${esc(p.avatar_url)}" alt="">`:`<div class="fc-avatar fc-avatar-fallback">${esc(initial)}</div>`;const [status,tone]=statusOf(s);return `<header class="fc-panel-header"><div class="fc-person-head">${avatar}<div><h3>${esc(memberName(s.user_id))}</h3><p>${esc(s.staff_label)} · <span class="fc-status ${tone}">${status}</span></p></div></div></header><nav class="fc-tabs"><button class="fc-tab ${state.tab==='permissions'?'is-active':''}" data-tab="permissions">Permissões</button><button class="fc-tab ${state.tab==='dossier'?'is-active':''}" data-tab="dossier">Dossiê</button><button class="fc-tab ${state.tab==='security'?'is-active':''}" data-tab="security">Segurança</button></nav>`;}
 function renderDetail(){const s=getMember(state.selected);if(!s){els.detail.className='fc-detail-empty';els.detail.innerHTML='Selecione um membro da equipe para abrir permissões, dossiê e segurança.';return;}els.detail.className='';els.detail.innerHTML=personHeader(s)+`<div class="fc-panel-body" id="fc-tab-body"></div>`;els.detail.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;renderDetail();});if(state.tab==='permissions')renderPermissions(s);if(state.tab==='dossier')renderDossier(s);if(state.tab==='security')renderSecurity(s);}
 function moduleCards(selected,disabled=false){return `<div class="fc-modules">${state.modules.filter(m=>m.module_key!=='governance').map(m=>`<label class="fc-module"><input type="checkbox" data-module="${m.module_key}" ${selected.has(m.module_key)?'checked':''} ${(disabled||m.module_key==='dashboard')?'disabled':''}><span><strong>${esc(m.label)}</strong><small>${esc(m.description)}</small></span></label>`).join('')}</div>`;}
 function renderPermissions(s){const body=$('#fc-tab-body');if(s.staff_label==='Founder'){body.innerHTML='<div class="fc-empty">A autoridade Founder é singleton, recebe todos os módulos implicitamente e não pode ser reduzida por este painel.</div>';return;}const own=grantSet(s.user_id);body.innerHTML=`<div class="fc-form-grid"><div class="fc-field full"><label>Cargo interno</label><input id="fc-role-label" class="fc-input" maxlength="60" value="${esc(s.staff_label)}"></div><div class="fc-field full"><label>Atalhos de função</label><div class="fc-presets">${Object.entries(PRESETS).map(([k,p])=>`<button type="button" class="fc-preset" data-preset="${k}">${esc(p.label)}</button>`).join('')}</div></div><div class="fc-field full"><label>Módulos autorizados</label>${moduleCards(own,!s.active)}</div><div class="fc-field full"><label>Motivo da alteração</label><textarea id="fc-change-reason" class="fc-textarea" rows="2" placeholder="Ex.: responsável pela curadoria de equipamentos"></textarea></div></div><div class="fc-actions"><button id="fc-save-permissions" class="fc-button primary" ${!s.active?'disabled':''}>Salvar permissões</button><button id="fc-toggle-status" class="fc-button">${s.active?'Suspender acesso':'Reativar acesso'}</button><button id="fc-revoke" class="fc-button danger">Revogar autoridade</button></div>`;body.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{const p=PRESETS[b.dataset.preset];$('#fc-role-label').value=p.label;body.querySelectorAll('[data-module]').forEach(i=>i.checked=p.modules.includes(i.dataset.module));});$('#fc-save-permissions').onclick=async()=>{const modules=[...body.querySelectorAll('[data-module]')].filter(i=>i.checked).map(i=>i.dataset.module);if(!modules.includes('dashboard'))modules.unshift('dashboard');const label=$('#fc-role-label').value.trim(),reason=$('#fc-change-reason').value.trim();message('Salvando cargo e módulos…');const{error}=await supabase.rpc('echo_founder_save_staff',{p_user_id:s.user_id,p_staff_label:label,p_module_keys:modules,p_reason:reason||'Atualização pelo Founder Center'});if(error){message(error.message,'error');return;}await load();message('Permissões atualizadas atomicamente e registradas no ledger.','success');};$('#fc-toggle-status').onclick=()=>openStatusModal(s);$('#fc-revoke').onclick=()=>openRevokeModal(s);}
 function renderDossier(s){const body=$('#fc-tab-body'),events=state.audit.filter(a=>a.actor_user_id===s.user_id),publicEvents=events.filter(a=>a.actor_kind==='public_staff'),destructive=events.filter(a=>['delete','public_delete','revoke_staff'].includes(a.action));body.innerHTML=`<div class="fc-dossier-grid"><div class="fc-mini-stat"><span>Ações registradas</span><strong>${events.length}</strong></div><div class="fc-mini-stat"><span>Atividade pública relevante</span><strong>${publicEvents.length}</strong></div><div class="fc-mini-stat"><span>Ações destrutivas</span><strong>${destructive.length}</strong></div></div><div class="fc-section-title"><h3>Atividade recente</h3><span class="fc-chip">últimos ${Math.min(events.length,40)}</span></div><div class="fc-timeline">${events.slice(0,40).map(a=>`<article class="fc-event"><div class="fc-event-top"><strong>${esc(a.module_key||'atividade')} · ${esc(a.action)}</strong><time>${fmtDate(a.created_at)}</time></div><p>${esc(a.target_type||'registro')}${a.target_id?` · ${esc(a.target_id)}`:''}${a.reason?` · ${esc(a.reason)}`:''}</p></article>`).join('')||'<div class="fc-empty">Ainda não há eventos para este membro.</div>'}</div>`;}
 function renderSecurity(s){const body=$('#fc-tab-body'),signals=state.signals.filter(x=>x.actor_user_id===s.user_id);body.innerHTML=`<div class="fc-section-title"><h3>Sinais de integridade</h3><span class="fc-chip">${signals.filter(x=>x.status==='open').length} abertos</span></div><div class="fc-integrity">${signalHtml(signals.slice(0,30))}</div><div class="fc-divider"></div><p style="color:var(--admin-muted);font-size:11px;line-height:1.6">A conta pública permanece separada da autoridade administrativa. Suspender ou revogar staff não apaga perfil, posts ou histórico; apenas remove o contexto interno.</p>`;bindSignalActions(body);}
 function signalHtml(rows){return rows.map(s=>`<article class="fc-signal" data-severity="${esc(s.severity)}"><div class="fc-signal-head"><h4>${esc(s.title)}</h4><span class="fc-status ${s.status==='open'?'suspended':'active'}">${esc(s.status)}</span></div><p>${esc(s.signal_type)} · ${fmtDate(s.created_at)}</p>${s.status==='open'?`<div class="fc-actions"><button class="fc-button ghost" data-signal-review="${s.id}">Marcar revisado</button><button class="fc-button ghost" data-signal-resolve="${s.id}">Resolver</button></div>`:''}</article>`).join('')||'<div class="fc-empty">Nenhum sinal de integridade.</div>';}
 function renderIntegrity(){const rows=state.signals.filter(s=>els.integrityFilter.value==='all'||s.status==='open');els.integrity.innerHTML=signalHtml(rows.slice(0,60));bindSignalActions(els.integrity);}
 function bindSignalActions(root){root.querySelectorAll('[data-signal-review],[data-signal-resolve]').forEach(b=>b.onclick=async()=>{const id=Number(b.dataset.signalReview||b.dataset.signalResolve),status=b.dataset.signalResolve?'resolved':'reviewed';const note=prompt('Nota da revisão (opcional):')||'';message('Atualizando sinal…');const{error}=await supabase.rpc('echo_founder_review_integrity_signal',{p_signal_id:id,p_status:status,p_note:note});if(error){message(error.message,'error');return;}await load();message('Sinal atualizado e ação auditada.','success');});}
 function renderAudit(){const q=els.auditSearch.value.trim().toLowerCase(),mod=els.auditModule.value;const rows=state.audit.filter(a=>(mod==='all'||(a.module_key||'')===mod)&&(!q||`${a.action} ${a.target_type||''} ${a.target_id||''} ${a.reason||''} ${memberName(a.actor_user_id)}`.toLowerCase().includes(q)));els.audit.innerHTML=rows.slice(0,200).map(a=>`<tr><td>${fmtDate(a.created_at)}</td><td>${esc(memberName(a.actor_user_id))}</td><td>${esc(a.module_key||'—')}</td><td>${esc(a.action)}</td><td>${esc(a.target_type||'—')} ${esc(a.target_id||'')}</td><td>${esc(a.aal||'—')}</td></tr>`).join('')||'<tr><td colspan="6">Nenhum evento para este filtro.</td></tr>';}
 function renderAll(){stats();renderStaff();renderDetail();renderIntegrity();els.auditModule.innerHTML='<option value="all">Todos os módulos</option>'+state.modules.map(m=>`<option value="${m.module_key}">${esc(m.label)}</option>`).join('')+'<option value="public_activity">Atividade pública</option>';renderAudit();}
 function openModal(title,subtitle,html){els.modalTitle.textContent=title;els.modalSubtitle.textContent=subtitle;els.modalBody.innerHTML=html;els.modal.hidden=false;document.body.style.overflow='hidden';}
 function closeModal(){els.modal.hidden=true;document.body.style.overflow='';}
 els.modal.querySelectorAll('[data-close-modal]').forEach(x=>x.onclick=closeModal);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!els.modal.hidden)closeModal();});
 async function openAdd(){openModal('Adicionar administrador','Busque uma conta já cadastrada no Echo Arena.','<div class="fc-field"><label>Buscar por apelido, nome ou UUID</label><input id="fc-user-search" class="fc-input" type="search" placeholder="Digite para buscar"></div><div id="fc-candidates" class="fc-candidates"><div class="fc-empty">Digite ao menos 2 caracteres.</div></div>');const input=$('#fc-user-search'),target=$('#fc-candidates');let timer;input.oninput=()=>{clearTimeout(timer);timer=setTimeout(async()=>{const q=input.value.trim();if(q.length<2){target.innerHTML='<div class="fc-empty">Digite ao menos 2 caracteres.</div>';return;}target.innerHTML='<div class="fc-empty">Buscando…</div>';const{data,error}=await supabase.rpc('echo_founder_staff_directory',{p_query:q,p_limit:20});if(error){target.innerHTML=`<div class="fc-empty">${esc(error.message)}</div>`;return;}for(const p of data||[])state.profiles.set(p.user_id,p);const founderId=state.staff.find(s=>s.staff_label==='Founder')?.user_id;const rows=(data||[]).filter(p=>p.user_id!==founderId&&!p.is_blocked);target.innerHTML=rows.map(p=>`<button class="fc-candidate" type="button" data-candidate="${p.user_id}"><div><strong>${esc(p.display_name||p.username||p.user_id.slice(0,8))}</strong><small>${p.username?`@${esc(p.username)} · `:''}${p.is_staff?'já faz parte da equipe':'conta elegível'}</small></div></button>`).join('')||'<div class="fc-empty">Nenhuma conta elegível encontrada.</div>';target.querySelectorAll('[data-candidate]').forEach(b=>b.onclick=()=>openOnboarding(b.dataset.candidate));},260);};setTimeout(()=>input.focus(),50);}
 function openOnboarding(userId){const p=state.profiles.get(userId)||{},existing=getMember(userId),selected=new Set(existing?[...grantSet(userId)]:PRESETS.hero.modules);openModal(existing?'Editar administrador':'Novo administrador',`${p.display_name||p.username||userId.slice(0,8)} · defina responsabilidade e menor privilégio necessário.`,`<div class="fc-form-grid"><div class="fc-field full"><label>Cargo interno</label><input id="fc-new-role" class="fc-input" maxlength="60" value="${esc(existing?.staff_label||PRESETS.hero.label)}"></div><div class="fc-field full"><label>Preset</label><div class="fc-presets">${Object.entries(PRESETS).map(([k,x])=>`<button class="fc-preset" type="button" data-new-preset="${k}">${esc(x.label)}</button>`).join('')}</div></div><div class="fc-field full"><label>Módulos</label>${moduleCards(selected,false)}</div><div class="fc-field full"><label>Justificativa</label><textarea id="fc-new-reason" class="fc-textarea" rows="3" placeholder="Por que esta pessoa precisa deste acesso?"></textarea></div></div><div class="fc-actions"><button id="fc-create-staff" class="fc-button primary">${existing?'Salvar administrador':'Adicionar à equipe'}</button><button class="fc-button" type="button" data-close-modal-local>Cancelar</button></div>`);els.modalBody.querySelectorAll('[data-new-preset]').forEach(b=>b.onclick=()=>{const preset=PRESETS[b.dataset.newPreset];$('#fc-new-role').value=preset.label;els.modalBody.querySelectorAll('[data-module]').forEach(i=>i.checked=preset.modules.includes(i.dataset.module));});els.modalBody.querySelector('[data-close-modal-local]').onclick=closeModal;$('#fc-create-staff').onclick=async()=>{const label=$('#fc-new-role').value.trim(),reason=$('#fc-new-reason').value.trim(),modules=[...els.modalBody.querySelectorAll('[data-module]')].filter(i=>i.checked).map(i=>i.dataset.module);if(!modules.includes('dashboard'))modules.unshift('dashboard');if(reason.length<4){message('Informe uma justificativa para conceder autoridade.','error');return;}message('Concedendo autoridade…');const{error}=await supabase.rpc('echo_founder_save_staff',{p_user_id:userId,p_staff_label:label,p_module_keys:modules,p_reason:reason});if(error){message(error.message,'error');return;}closeModal();state.selected=userId;await load();message('Administrador salvo com módulos, justificativa e auditoria.','success');};}
 function openStatusModal(s){const suspending=s.active;openModal(suspending?'Suspender administrador':'Reativar administrador',memberName(s.user_id),`<div class="fc-field"><label>Motivo</label><textarea id="fc-status-reason" class="fc-textarea" rows="3" placeholder="Motivo operacional obrigatório"></textarea></div><div class="fc-actions"><button id="fc-confirm-status" class="fc-button ${suspending?'danger':'primary'}">${suspending?'Suspender acesso':'Reativar acesso'}</button><button class="fc-button" data-close-modal-local>Cancelar</button></div>`);els.modalBody.querySelector('[data-close-modal-local]').onclick=closeModal;$('#fc-confirm-status').onclick=async()=>{const reason=$('#fc-status-reason').value.trim();if(reason.length<4){message('Informe o motivo.','error');return;}const{error}=await supabase.rpc('echo_founder_set_staff_status',{p_user_id:s.user_id,p_active:!s.active,p_reason:reason});if(error){message(error.message,'error');return;}closeModal();await load();message(suspending?'Acesso suspenso.':'Acesso reativado.','success');};}
 function openRevokeModal(s){openModal('Revogar autoridade administrativa',memberName(s.user_id),`<div class="fc-field"><label>Motivo da revogação</label><textarea id="fc-revoke-reason" class="fc-textarea" rows="3" placeholder="O histórico será preservado; a conta pública não será apagada."></textarea></div><p style="color:var(--admin-muted);font-size:11px;line-height:1.6">Todos os módulos serão removidos imediatamente. O dossiê e o ledger continuam preservados.</p><div class="fc-actions"><button id="fc-confirm-revoke" class="fc-button danger">Revogar autoridade</button><button class="fc-button" data-close-modal-local>Cancelar</button></div>`);els.modalBody.querySelector('[data-close-modal-local]').onclick=closeModal;$('#fc-confirm-revoke').onclick=async()=>{const reason=$('#fc-revoke-reason').value.trim();if(reason.length<4){message('Informe o motivo da revogação.','error');return;}const{error}=await supabase.rpc('echo_founder_revoke_staff',{p_user_id:s.user_id,p_reason:reason});if(error){message(error.message,'error');return;}closeModal();await load();message('Autoridade revogada; conta pública e histórico preservados.','success');};}
 $('#fc-add-admin').onclick=openAdd;$('#fc-refresh').onclick=()=>load().catch(e=>message(e.message,'error'));els.teamSearch.oninput=renderStaff;els.teamFilter.onchange=renderStaff;els.auditSearch.oninput=renderAudit;els.auditModule.onchange=renderAudit;els.integrityFilter.onchange=renderIntegrity;
 try{await load();}catch(error){console.error('[founder-center]',error);message(error.message||'Falha ao carregar Founder Center.','error');}
}
