import { loadStatusCentralData, centralRpc, requestBrainProof } from './status-central-api.js?sc=20260906-1&sb=20260823-security-supabase-pin-1';
import { discoverStatusFields, inventoryStatusEffects, buildStatusProof, draftStatusRegistry, statusTargetChoices, suggestedStatusId, statusActionRecord } from './status-central-model.js?sc=20260906-1&eq=20260907-effects-1';
import { STATUS_UNITS, STATUS_OPERATORS, STATUS_CONDITIONS, STATUS_REASONS, compileStatusRegistry, statusAttributeRows, stableStatusJson, validateStatusPayload, finiteStatusNumber, compareStatusCalculations } from '../../js/status-registry-v1.js?sc=20260906-1&eq=20260907-effects-1';
import { canonicalKey, STAT_DEFINITIONS } from '../../js/game-stat-engine.js?v=15&sc=20260906-1&eq=20260907-effects-1';
import { mountStatusCentralGuided } from './status-central-guided.js?ux=20260908-1&sb=20260823-security-supabase-pin-1';

const $ = id => document.getElementById(id);
const esc = value => String(value ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const format = value => finiteStatusNumber(value) === null ? 'Não cadastrado' : Number(value).toLocaleString('pt-BR',{maximumFractionDigits:4});
const options = (rows,label='name',value='id') => rows.map(r=>`<option value="${esc(r[value])}">${esc(r[label])}</option>`).join('');
const state = { data:null, draft:null, fields:[], effects:[], fieldLimit:40, selections:[], bindingRows:[], proof:null, busy:false, dirty:false, baseExpected:null, returnToBinding:false };
let guided=null;
const statusText = {bound:'Vínculo publicado',legacy:'Pendente de vínculo',unmapped:'Pendente de vínculo',changed:'Fonte alterada',ambiguous:'Vínculo ambíguo'};
const msg = (text,kind='') => { $('sc-message').textContent=text; $('sc-message').className=`sc-message ${kind ? `is-${kind}` : ''}`; };
function tab(name) {
  document.querySelectorAll('[data-sc-tab]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.scTab===name)));
  document.querySelectorAll('[data-sc-view]').forEach(p=>p.hidden=p.dataset.scView!==name);
  $('sc-advanced-savebar').hidden=name==='guided';
  if(name!=='guided')$('sc-advanced-tools').open=true;
}
function invalidateProof(reason='Os dados mudaram. Execute uma nova prova.') { state.proof=null; $('sc-proof-result').textContent=''; $('sc-parity').textContent=reason; guided?.invalidate(reason); }
function setDirty() { state.dirty=true; invalidateProof('O rascunho mudou. Execute uma nova prova.'); guided.invalidate('O rascunho mudou nas ferramentas avançadas. Teste novamente antes de aplicar.'); $('sc-dirty').textContent='Há alterações locais no rascunho'; renderDefinitions(); renderBindings(); }
async function action(fn) {
  if(state.busy) return;
  state.busy=true; $('status-central').inert=true; updateButtons();
  try { await fn(); } catch(error) { msg(error.message,'error'); }
  finally { state.busy=false; $('status-central').inert=false; updateButtons(); }
}
function updateButtons() {
  const permissions=state.data?.central?.permissions || {};
  $('sc-save').disabled=state.busy||!state.dirty||!permissions.edit;
  $('sc-publish').disabled=state.busy||state.dirty||!permissions.publish||!state.data?.central.draft_revision;
  $('sc-save-base').disabled=state.busy||!permissions.base_edit;
}
function badge(status) { return `<span class="sc-badge ${status==='bound'?'good':['changed','unmapped','ambiguous'].includes(status)?'warn':''}">${esc(statusText[status]||status)}</span>`; }
function renderOverview() {
  const data=state.data,pub=data.central.published,counts={};
  for(const s of ['bound','legacy','unmapped','changed','ambiguous']) counts[s]=state.effects.filter(e=>e.status===s).length;
  $('sc-metrics').innerHTML=[['Campos encontrados',state.fields.length,`${data.heroes.length} heróis · ${data.skills.length} habilidades`],['Vínculos publicados',pub.payload.bindings.length,`${pub.payload.definitions.length} definições de status`],['Efeitos sem regra',counts.unmapped,'Exigem vínculo ou classificação'],['Fontes alteradas',counts.changed+counts.ambiguous,'Revisar antes de aplicar']].map(([label,note,sub])=>`<article><span>${label}</span><strong>${note}</strong><small>${sub}</small></article>`).join('');
  const issues=state.effects.filter(e=>['unmapped','changed','ambiguous'].includes(e.status));
  $('sc-issues').innerHTML=issues.slice(0,12).map(e=>`<div class="sc-row"><div><strong>${esc(e.name)}</strong><small>${esc(e.rarity)} · ${esc(e.label)} · ${esc(e.value)}</small>${badge(e.status)}</div><button class="admin-button" type="button" data-link-source="${esc(e.equipmentId||e.source_id)}" data-kind="${e.source_kind}">Vincular</button></div>`).join('')||'<div class="sc-empty">Nenhuma linha sem regra foi encontrada nesta leitura. A prova ainda é necessária para conferir bases e aplicação.</div>';
  if(issues.length>12) $('sc-issues').insertAdjacentHTML('beforeend',`<p class="sc-note">${issues.length} ocorrências no total. Revise as fontes em “Vincular efeitos”.</p>`);
  $('sc-system').innerHTML=`<div class="sc-row"><div><strong>Registro ${pub.revision ? `publicado · revisão ${pub.revision}` : 'ainda sem publicação'}</strong><small>${pub.revision?'Lido do banco nesta atualização.':'Efeitos sem vínculo publicado ficam pendentes e não alteram os status.'}</small></div></div><div class="sc-row"><div><strong>Central obrigatória para os equipamentos</strong><small>Destino, operação e condição vêm do vínculo de cada linha e raridade.</small></div></div><div class="sc-row"><div><strong>Brain: prova ainda não executada</strong><small>Selecione herói e itens para comparar revisão, valores e origens.</small></div></div>`;
  $('sc-revision').textContent=`Publicado: ${pub.revision||'nenhum'} · Rascunho: ${data.central.draft_revision||'nenhum'}`;
}
function definitionFor(field) { return state.draft.definitions.find(d=>d.scope===field.scope&&d.source_key===field.source_key&&(d.skill_id||null)===(field.skill_id||null)&&(d.level_id||null)===(field.level_id||null)); }
function renderFields() {
  const query=$('sc-search').value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
  const unobserved=state.draft.definitions.filter(d=>!state.fields.some(f=>definitionFor(f)?.id===d.id)).map(d=>({...d,locator:`registered:${d.id}`,heroes:0,samples:[]}));
  const rows=[...state.fields,...unobserved].filter(f=>`${f.name} ${f.source_key}`.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().includes(query));
  $('sc-fields').innerHTML=rows.slice(0,state.fieldLimit).map(f=>{const d=definitionFor(f),range=f.samples.map(s=>s.value);return `<div class="sc-row"><div><strong>${esc(d?.name||f.name)}</strong><small>${esc(f.scope==='hero'?'Herói':f.scope==='weapon'?'Arma':'Habilidade')} · ${f.heroes} herói(s) · valores ${format(Math.min(...range))} a ${format(Math.max(...range))}</small><small><code>${esc(f.source_key)}</code> · ${d?esc(STATUS_UNITS[d.unit].label):'Significado e unidade pendentes'}</small></div><button type="button" class="admin-button" data-register="${esc(f.locator)}">${d?'Revisar':'Registrar status'}</button></div>`;}).join('')||'<div class="sc-empty">Nenhum campo corresponde à busca. Você pode cadastrar um novo status.</div>';
  $('sc-more-fields').hidden=rows.length<=state.fieldLimit;
}
function renderDefinitions() {
  const select=$('sc-binding-target'),value=select.value;
  const choices=statusTargetChoices(state.fields,state.draft);
  const label=d=>`${d.scope==='weapon'?'Arma':d.scope==='hero'?'Herói':'Habilidade'} · ${d.name} · ${d.source_key}`;
  select.innerHTML='<option value="">Escolha o status de destino</option>'
    +(choices.registered.length?'<optgroup label="Status configurados">'+options(choices.registered.map(d=>({...d,name:label(d)})))+'</optgroup>':'')
    +(choices.pending.length?'<optgroup label="Campos encontrados — configurar unidade">'+options(choices.pending.map(d=>({id:'discover:'+d.locator,name:label(d)})))+'</optgroup>':'');
  $('sc-target-help').textContent=choices.registered.length?'Confira origem e condição antes de vincular.':'Escolha um campo encontrado para confirmar sua unidade. Você voltará para este efeito em seguida.';
  if(state.draft.definitions.some(d=>d.id===value)) select.value=value;
  renderFields(); updateButtons();
}
function renderBindings() {
  $('sc-current-bindings').innerHTML=state.draft.bindings.filter(b=>!$('sc-binding-item').value||sourceRows().some(r=>r.source_kind===b.source_kind&&r.source_id===b.source_id)).map(b=>{
    const e=state.effects.find(e=>e.source_kind===b.source_kind&&e.source_id===b.source_id&&e.key===b.attribute_key),d=state.draft.definitions.find(d=>d.id===b.target);
    return `<div class="sc-row"><div><strong>${esc(e?.name||'Habilidade')} → ${esc(d?.name||b.target)}</strong><small>${esc(d?.scope==='weapon'?'Arma':d?.scope==='hero'?'Herói':'Habilidade')} · ${esc(d?.source_key||'')}<br>${esc(e?.rarity||'')} · ${esc(e?.label||b.attribute_key)} · ${esc(STATUS_OPERATORS[b.operator]?.label)} · ${esc(STATUS_CONDITIONS[b.condition])}</small></div><button class="admin-button" type="button" data-remove-binding="${esc(b.id)}">Retirar do rascunho</button></div>`;
  }).join('')||'<div class="sc-empty">Nenhum vínculo no rascunho. Registre um status e escolha a linha que deve alterá-lo.</div>';
}
function populateSelectors() {
  const data=state.data;
  for(const id of ['sc-base-hero','sc-skills-hero','sc-proof-hero']) { const old=$(id).value;$(id).innerHTML='<option value="">Escolha o herói</option>'+options(data.heroes);if(old)$(id).value=old; }
  const skillOptions='<option value="">Não se aplica</option>'+options(data.skills.map(s=>({...s,name:`${data.heroes.find(h=>h.id===s.hero_id)?.name||''} · ${s.name}`})));
  $('sc-stat-form').elements.skill_id.innerHTML=skillOptions;$('sc-condition-ability').innerHTML=skillOptions;
  $('sc-stat-form').elements.level_id.innerHTML='<option value="">Não se aplica</option>'+options(data.levels.map(l=>({...l,name:`${data.skills.find(s=>s.id===l.skill_id)?.name||''} · nível ${l.level}`})));
  $('sc-source-keys').innerHTML=[...new Set(state.fields.filter(f=>['hero','weapon'].includes(f.scope)).map(f=>f.source_key))].map(k=>`<option value="${esc(k)}"></option>`).join('');
  $('sc-proof-item').innerHTML='<option value="">Escolha um equipamento</option>'+options(data.equipments.filter(e=>e.enabled));
  updateBindingSources(); renderSkills();
}
function editStat(field=null) {
  const form=$('sc-stat-form'),existing=field?(field.id?state.draft.definitions.find(d=>d.id===field.id):definitionFor(field)):null;
  form.reset(); form.dataset.editId=existing?.id||''; delete form.elements.id.dataset.manual;
  let suggested=field?suggestedStatusId(field):'';
  if(field?.skill_id) suggested=`skill_${field.skill_id.replaceAll('-','').slice(0,12)}_${field.source_key}`;
  if(field?.level_id) suggested=`level_${field.level_id.replaceAll('-','').slice(0,12)}_${field.source_key}`;
  const value=existing||{id:suggested,name:field?.name||'',scope:field?.scope||'hero',source_key:field?.source_key||'',skill_id:field?.skill_id||'',level_id:field?.level_id||'',unit:'unknown',direction:'neutral',kind:'scalar'};
  for(const [key,val] of Object.entries(value)) if(form.elements[key]) form.elements[key].value=val??'';
  form.elements.id.readOnly=Boolean(existing);
  $('sc-stat-editor').hidden=false;$('sc-stat-title').textContent=existing?'Revisar definição':'Registrar status';
  tab('stats');$('sc-stat-editor').scrollIntoView({block:'start'});form.elements.name.focus();
}
function updateBindingSources() {
  const kind=$('sc-binding-kind').value,data=state.data;
  const rows=kind==='equipment_variant'?data.equipments:kind==='set_bonus'?data.bonuses.map(b=>({...b,name:`${b.title} · ${b.required_pieces} peças`})):
    kind==='hero_skill'?data.skills.map(s=>({...s,name:`${data.heroes.find(h=>h.id===s.hero_id)?.name||''} · ${s.name}`})):
    data.levels.map(l=>({...l,name:`${data.skills.find(s=>s.id===l.skill_id)?.name||''} · nível ${l.level}`}));
  $('sc-binding-item').innerHTML='<option value="">Escolha a fonte</option>'+options(rows);updateBindingLines();
}
function sourceRows() {
  const kind=$('sc-binding-kind').value,id=$('sc-binding-item').value;
  if(kind==='equipment_variant') return state.effects.filter(e=>e.equipmentId===id&&!e.missing).sort((a,b)=>a.rank-b.rank);
  if(kind==='set_bonus') return state.effects.filter(e=>e.source_id===id&&e.source_kind===kind&&!e.missing);
  const source=(kind==='hero_skill'?state.data.skills:state.data.levels).find(s=>s.id===id);
  const keys=kind==='hero_skill'?['cooldown','duration','energy_cost']:['damage','healing','shield','cooldown','duration','radius','range','speed','energy_cost'];
  return source?statusAttributeRows(Object.fromEntries(keys.filter(k=>source[k]!=null).map(k=>[k,source[k]]))).map(row=>({...row,source_kind:kind,source_id:id,name:source.name||'Nível de habilidade',rarity:source.level?`Nível ${source.level}`:'Habilidade',status:'unmapped',abilityId:kind==='hero_skill'?id:source.skill_id})):[];
}
function updateBindingLines() {
  const rows=sourceRows(),labels=[...new Set(rows.map(r=>r.label))];
  $('sc-binding-line').innerHTML=labels.map(label=>`<option value="${esc(label)}">${esc(label)}</option>`).join('');renderBindingRows();
}
function renderBindingRows() {
  state.bindingRows=sourceRows().filter(r=>r.label===$('sc-binding-line').value);
  const duplicates=new Set();for(const r of state.bindingRows) if(state.bindingRows.filter(x=>x.source_id===r.source_id).length>1)duplicates.add(r.source_id);
  $('sc-binding-rows').innerHTML=state.bindingRows.length?`<table><thead><tr><th>Vincular</th><th>Raridade / nível</th><th>Valor da fonte</th><th>Estado atual</th></tr></thead><tbody>${state.bindingRows.map((r,i)=>`<tr><td data-label="Vincular"><input type="checkbox" data-bind-row="${i}" aria-label="Vincular ${esc(r.rarity)}" ${duplicates.has(r.source_id)?'':'checked'}></td><td data-label="Raridade">${esc(r.rarity)}${duplicates.has(r.source_id)?'<small> · descrição repetida: escolha a linha</small>':''}</td><td data-label="Valor">${esc(r.value)}</td><td data-label="Estado">${badge(r.status)}</td></tr>`).join('')}</tbody></table>`:'<div class="sc-empty">Esta fonte não possui uma linha numérica disponível. Cadastre o valor no editor de origem.</div>';
  const first=state.bindingRows[0],current=first?state.draft.bindings.find(b=>b.source_kind===first.source_kind&&b.source_id===first.source_id&&b.attribute_key===first.key):null;$('sc-operator').value=current?.operator||first?.operator||'';
  if(current){$('sc-binding-target').value=current.target;$('sc-condition').value=current.condition;$('sc-condition-ability').value=current.ability_id||'';}else if(first?.abilityId){$('sc-condition').value='ability_active';$('sc-condition-ability').value=first.abilityId;}else {$('sc-condition').value='always';$('sc-condition-ability').value='';}
  $('sc-effect-text').textContent=first?.label||'Escolha um equipamento e um efeito.';
  const equipment=$('sc-binding-kind').value==='equipment_variant'?$('sc-binding-item').value:'';
  $('sc-edit-equipment').hidden=!equipment;
  $('sc-edit-equipment').href='./equipment-editor.html?id='+encodeURIComponent(equipment);
  renderBindings();updateFormula();
}
function selectedBindingRows(){return [...document.querySelectorAll('[data-bind-row]:checked')].map(c=>state.bindingRows[Number(c.dataset.bindRow)]);}
function updateFormula(){const d=state.draft?.definitions.find(d=>d.id===$('sc-binding-target').value),op=STATUS_OPERATORS[$('sc-operator').value];$('sc-binding-formula').textContent=d&&op?`${d.scope==='weapon'?'Arma':d.scope==='hero'?'Herói':'Habilidade'} · ${d.name} · ${d.source_key} (${STATUS_UNITS[d.unit].label}) · ${STATUS_CONDITIONS[$('sc-condition').value]}: ${op.operation==='percent'?`valor atual × (1 ${op.sign<0?'−':'+'} bônus ÷ 100)`:`valor atual ${op.sign<0?'−':'+'} bônus`}. Cada efeito é aplicado na sequência; não é convertido para outra unidade.`:'Escolha um status calculável e um operador.';}
function updateBaseReadback(){const form=$('sc-base-form'),base=state.data?.bases.find(b=>b.hero_id===form.elements.hero_id.value),key=form.elements.source_key.value;state.baseExpected=base?.[form.elements.scope.value==='hero'?'hero_stats':'weapon_stats']?.[key]??null;$('sc-base-current').value=format(state.baseExpected);}
function renderSkills(){const id=$('sc-skills-hero').value,rows=state.data.skills.filter(s=>s.hero_id===id);$('sc-skills').innerHTML=rows.map(s=>`<div class="sc-row"><div><strong>${esc(s.name)}</strong><small>${esc(s.verification_status)}${s.needs_recheck?' · precisa de revisão':''} · ${state.data.levels.filter(l=>l.skill_id===s.id).length} níveis cadastrados</small></div><button type="button" class="admin-button" data-skill-source="${s.id}">Vincular efeito</button></div>`).join('')||'<p class="sc-note">Selecione um herói para conferir as habilidades cadastradas.</p>';$('sc-new-skill').href=`./hero-editor.html${id?`?id=${encodeURIComponent(id)}#skills`:''}`;}
function renderHistory(){$('sc-history').innerHTML=state.data.central.history.map(h=>`<div class="sc-row"><div><strong>Revisão ${h.id} · ${esc(new Date(h.created_at).toLocaleString('pt-BR'))}</strong><small>${esc(h.reason)}</small><details><summary>Identificador do conteúdo</summary><code>${esc(h.fingerprint)}</code></details></div><button type="button" class="admin-button" data-restore="${h.id}" ${h.id===state.data.central.draft_revision?'disabled':''}>Restaurar em rascunho</button></div>`).join('')||'<div class="sc-empty">Ainda não há revisões.</div>';}
async function refresh(){const data=await loadStatusCentralData();state.data=data;state.draft=structuredClone(data.central.draft);state.fields=discoverStatusFields(data);state.effects=inventoryStatusEffects(data,compileStatusRegistry(data.central.published));state.dirty=false;invalidateProof();$('sc-dirty').textContent='Rascunho conferido no banco';populateSelectors();renderOverview();renderDefinitions();renderBindings();renderHistory();updateBaseReadback();guided.refresh();msg('Catálogo atualizado. Escolha um equipamento para começar.');}
async function rereadCentral(confirmed=null){state.data.central=confirmed||await centralRpc('admin_get_status_central_v1');state.draft=structuredClone(state.data.central.draft);state.dirty=false;state.effects=inventoryStatusEffects(state.data,compileStatusRegistry(state.data.central.published));renderOverview();renderDefinitions();renderBindings();renderHistory();$('sc-dirty').textContent='Rascunho conferido no banco';}
function proofConditions(){const out={};for(const key of ['aiming','moving']){const value=$(`sc-proof-${key}`).value;if(value)out[key]=value==='true';}const ability=$('sc-proof-ability').value;if(ability==='none')out.activeAbilities=[];else if(ability){out.activeAbilities=[ability];const level=$('sc-proof-level').value;if(level)out.skillLevels={[ability]:level};}return out;}
function renderLoadout(){$('sc-proof-loadout').innerHTML=state.selections.map((s,i)=>`<div class="sc-row"><div><strong>${esc(state.data.equipments.find(e=>e.id===s.equipmentId)?.name)}</strong><small>${esc(state.data.rarities.find(r=>r.id===state.data.variants.find(v=>v.id===s.variantId)?.rarity_id)?.name)}</small></div><button type="button" data-remove-selection="${i}" class="admin-button">Retirar</button></div>`).join('');invalidateProof('Seleção alterada. Execute uma nova prova.');}
function updateProofVariants(){const id=$('sc-proof-item').value;$('sc-proof-variant').innerHTML=options(state.data.variants.filter(v=>v.equipment_id===id).map(v=>({...v,name:state.data.rarities.find(r=>r.id===v.rarity_id)?.name||'Raridade não encontrada'})));}
function coneSvg(calculation){const angle=Object.entries(calculation.origins||{}).find(([key,o])=>o.scope==='weapon'&&o.unit==='degree'&&['weapon_spread','dispersion','aimed_dispersion'].includes(o.key)&&calculation.applied.some(t=>t.target===key));if(!angle)return '';const [key]=angle;const a=calculation.base[key],b=calculation.final[key];if(!Number.isFinite(a)||!Number.isFinite(b)||a<0||b<0||a>180||b>180)return '';const path=angle=>{const rad=angle*Math.PI/360,x=130*Math.sin(rad),y=155-130*Math.cos(rad);return `M160 155 L${160-x} ${y} A130 130 0 0 1 ${160+x} ${y} Z`;};return `<svg class="sc-cone" viewBox="0 0 320 170" role="img" aria-label="Comparação angular da dispersão: ${a} graus antes e ${b} graus depois"><path d="${path(a)}" fill="#b5566555" stroke="#e78291"/><path d="${path(b)}" fill="#70d7c655" stroke="#93f6dd"/><circle cx="160" cy="155" r="4" fill="#fff"/></svg><p class="sc-note">${esc(calculation.definitions[key]?.nome||key)}: representação geométrica do ângulo cadastrado. Rosa: base; verde: resultado. Não mede a cena da captura.</p>`;}
function renderCalculation(calculation,title){const keys=[...new Set([...Object.keys(calculation.origins||{}),...calculation.applied.map(a=>a.target)])];return `<article class="sc-panel"><h2>${title}</h2>${calculation.complete===false?'<p class="sc-formula">Cálculo parcial: há efeitos pendentes. Confira cada motivo na trilha.</p>':''}${coneSvg(calculation)}<div class="sc-table-wrap"><table><thead><tr><th>Status</th><th>Base</th><th>Resultado</th></tr></thead><tbody>${keys.map(k=>{const d=calculation.definitions?.[k]||STAT_DEFINITIONS[k]||{};return `<tr><td data-label="Status">${esc(d.nome||k)}<small><br>${esc(calculation.origins?.[k]?.scope==='weapon'?'Arma':calculation.origins?.[k]?.scope==='hero'?'Herói':'Habilidade')} · ${esc(calculation.origins?.[k]?.key||k)}</small></td><td data-label="Base">${format(calculation.base[k])}${esc(d.unit||'')}</td><td class="sc-proof-number" data-label="Resultado">${format(calculation.final[k])}${esc(d.unit||'')}</td></tr>`;}).join('')}</tbody></table></div><h3>Trilha de aplicação</h3><ol class="sc-trace">${calculation.trace.map(t=>`<li><strong>${esc(t.source?.name||t.sourceKey)}</strong><small>${esc(t.sourceKey)} → ${esc(calculation.definitions?.[t.target]?.nome||STAT_DEFINITIONS[t.target]?.nome||t.target||'Sem destino')}</small>${t.after!==undefined?`${format(t.before)} ${t.operation==='percent'?`× (1 ${t.value<0?'−':'+'} ${format(Math.abs(t.value))}/100)`:`${t.value<0?'−':'+'} ${format(Math.abs(t.value))}`} = <b>${format(t.after)}</b>`:esc(STATUS_REASONS[t.status]||t.reason)}<small>${esc(t.source?.rarity||'')} · ${esc(t.targetScope==='weapon'?'Arma':t.targetScope==='hero'?'Herói':t.targetScope||'Destino pendente')} ${esc(t.targetSourceKey||'')} · ${esc(STATUS_CONDITIONS[t.condition]||'')}<br>${esc(t.reason)}</small></li>`).join('')||'<li>Nenhum equipamento ou efeito foi selecionado.</li>'}</ol></article>`;}
function runProof(){invalidateProof('Prova local atualizada; o Brain ainda não confirmou este resultado.');const heroId=$('sc-proof-hero').value,conditions=proofConditions(),published=buildStatusProof(state.data,heroId,state.selections,compileStatusRegistry(state.data.central.published),conditions),draft=buildStatusProof(state.data,heroId,state.selections,draftStatusRegistry(state.data.central,state.draft),conditions);state.proof={heroId,conditions,published,draft,signature:stableStatusJson(state.draft)};$('sc-proof-result').innerHTML=`<div class="sc-proof-grid">${renderCalculation(published.calculation,'Registro publicado')}${renderCalculation(draft.calculation,'Prévia do rascunho')}</div>`;return state.proof;}

document.querySelectorAll('[data-sc-tab]').forEach(b=>b.addEventListener('click',()=>tab(b.dataset.scTab)));
$('sc-refresh').addEventListener('click',()=>action(async()=>{if(state.dirty&&!confirm('Descartar as alterações locais e reler o banco?'))return;await refresh();}));
$('sc-search').addEventListener('input',()=>{state.fieldLimit=40;renderFields();});$('sc-more-fields').addEventListener('click',()=>{state.fieldLimit+=40;renderFields();});
$('sc-stat-form').elements.id.addEventListener('input',()=>{$('sc-stat-form').elements.id.dataset.manual='true';});
$('sc-stat-form').elements.source_key.addEventListener('input',()=>{const f=$('sc-stat-form');if(!f.dataset.editId&&!f.elements.id.dataset.manual)f.elements.id.value=suggestedStatusId({scope:f.elements.scope.value,source_key:f.elements.source_key.value});});
$('sc-new-stat').addEventListener('click',()=>editStat());$('sc-stat-cancel').addEventListener('click',()=>$('sc-stat-editor').hidden=true);
$('sc-stat-form').addEventListener('submit',event=>{event.preventDefault();action(async()=>{const f=event.currentTarget,e=f.elements,d={id:e.id.value.trim(),name:e.name.value.trim(),scope:e.scope.value,source_key:e.source_key.value.trim(),unit:e.unit.value,direction:e.direction.value,kind:e.kind.value,minimum:e.minimum.value.trim()?finiteStatusNumber(e.minimum.value):null,maximum:e.maximum.value.trim()?finiteStatusNumber(e.maximum.value):null,evidence:e.evidence.value.trim()||statusActionRecord('definição manual de status',`${e.scope.value}.${e.source_key.value}; unidade ${e.unit.value}. Referência adicional não anexada.`)};if(['skill','skill_level'].includes(d.scope))d.skill_id=e.skill_id.value;if(d.scope==='skill_level')d.level_id=e.level_id.value;if((e.minimum.value.trim()&&d.minimum===null)||(e.maximum.value.trim()&&d.maximum===null))throw new Error('Informe limites numéricos válidos.');const next=structuredClone(state.draft),index=next.definitions.findIndex(x=>x.id===d.id);if(index>=0&&!f.dataset.editId)throw new Error('Esse código já existe. Use Revisar para editar a definição.');if(index>=0)next.definitions[index]=d;else next.definitions.push(d);const v=validateStatusPayload(next,{evidence:true});if(!v.valid)throw new Error(v.errors.map(x=>x.message).join(' '));state.draft=next;setDirty();$('sc-stat-editor').hidden=true;if(state.returnToBinding){state.returnToBinding=false;tab('bindings');$('sc-binding-target').value=d.id;updateFormula();$('sc-binding-target').focus();}msg('Status adicionado ao rascunho. Salve a revisão antes de publicar.');});});
for(const id of ['sc-binding-kind','sc-binding-item','sc-binding-line'])$(id).addEventListener('change',id==='sc-binding-kind'?updateBindingSources:id==='sc-binding-item'?updateBindingLines:renderBindingRows);
$('sc-binding-target').addEventListener('change',()=>{
  const value=$('sc-binding-target').value;
  if(value.startsWith('discover:')) { state.returnToBinding=true;editStat(state.fields.find(f=>f.locator===value.slice(9))); }
  else updateFormula();
});
$('sc-register-target').addEventListener('click',()=>{state.returnToBinding=true;editStat();});
for(const id of ['sc-operator','sc-condition'])$(id).addEventListener('change',updateFormula);
$('sc-binding-form').addEventListener('submit',event=>{event.preventDefault();action(async()=>{const e=event.currentTarget.elements,rows=selectedBindingRows();if(!rows.length)throw new Error('Selecione pelo menos uma linha.');const target=state.draft.definitions.find(d=>d.id===e.target.value),op=STATUS_OPERATORS[e.operator.value];if(!target||!op)throw new Error('Escolha o status e o operador.');const next=structuredClone(state.draft);for(const row of rows){const old=next.bindings.find(b=>b.source_kind===row.source_kind&&b.source_id===row.source_id&&b.attribute_key===row.key);const binding={id:old?.id||crypto.randomUUID(),source_kind:row.source_kind,source_id:row.source_id,attribute_key:row.key,source_snapshot:row.raw,target:target.id,operator:e.operator.value,unit:op.operation==='percent'?'percent':target.unit,condition:e.condition.value,evidence:e.evidence.value.trim()||statusActionRecord('vínculo manual',`${row.source_kind}/${row.source_id}/${row.key} → ${target.scope}.${target.source_key}; ${e.operator.value}; ${e.condition.value}.`)};if(binding.condition==='ability_active')binding.ability_id=e.ability_id.value;next.bindings=next.bindings.filter(b=>b.id!==binding.id);next.bindings.push(binding);}const v=validateStatusPayload(next,{evidence:true});if(!v.valid)throw new Error(v.errors.map(x=>x.message).join(' '));state.draft=next;setDirty();msg(`${rows.length} linha(s) vinculadas no rascunho. Confira na Prova do cálculo.`);});});
$('sc-remove-bindings').addEventListener('click',()=>{const rows=selectedBindingRows();state.draft.bindings=state.draft.bindings.filter(b=>!rows.some(r=>r.source_kind===b.source_kind&&r.source_id===b.source_id&&r.key===b.attribute_key));setDirty();});
$('sc-base-form').addEventListener('input',updateBaseReadback);$('sc-base-form').addEventListener('change',updateBaseReadback);
$('sc-base-form').addEventListener('submit',event=>{event.preventDefault();action(async()=>{const e=event.currentTarget.elements,value=finiteStatusNumber(e.value.value);if(value===null)throw new Error('Informe um número válido.');const args={p_hero_id:e.hero_id.value,p_scope:e.scope.value,p_source_key:e.source_key.value.trim(),p_expected_value:state.baseExpected,p_value:value,p_evidence:e.evidence.value.trim()||'Correção manual na Central; referência adicional não anexada.',p_reason:statusActionRecord('correção de base',`${e.scope.value}.${e.source_key.value}: ${state.baseExpected} → ${value}`)};await centralRpc('admin_save_status_base_v1',args);invalidateProof('A base foi alterada. Execute uma nova prova após a releitura.');const updated=await loadStatusCentralData(),actual=updated.bases.find(b=>b.hero_id===args.p_hero_id)?.[args.p_scope==='hero'?'hero_stats':'weapon_stats']?.[args.p_source_key];if(finiteStatusNumber(actual)!==value)throw new Error('A gravação respondeu, mas a releitura não confirmou o valor esperado.');state.data.bases=updated.bases;state.fields=discoverStatusFields(state.data);renderFields();updateBaseReadback();msg('Valor-base salvo e confirmado por releitura. A correção foi registrada na Auditoria.','ok');});});
$('sc-skills-hero').addEventListener('change',renderSkills);
$('sc-proof-item').addEventListener('change',updateProofVariants);$('sc-proof-hero').addEventListener('change',()=>{state.selections=[];$('sc-proof-level').innerHTML='<option value="">Não informado</option>';renderLoadout();$('sc-proof-ability').innerHTML='<option value="">Não informada</option><option value="none">Nenhuma ativa</option>'+options(state.data.skills.filter(s=>s.hero_id===$('sc-proof-hero').value&&s.enabled));});
$('sc-proof-ability').addEventListener('change',()=>{$('sc-proof-level').innerHTML='<option value="">Não informado</option>'+options(state.data.levels.filter(l=>l.skill_id===$('sc-proof-ability').value).map(l=>({...l,name:`Nível ${l.level}`})));});
for(const id of ['sc-proof-aiming','sc-proof-moving','sc-proof-ability','sc-proof-level'])$(id).addEventListener('change',()=>invalidateProof('Condições alteradas. Execute uma nova prova.'));
$('sc-proof-add').addEventListener('click',()=>action(async()=>{const choice={equipmentId:$('sc-proof-item').value,variantId:$('sc-proof-variant').value};buildStatusProof(state.data,$('sc-proof-hero').value,[...state.selections,choice],compileStatusRegistry(state.data.central.published),proofConditions());state.selections.push(choice);renderLoadout();}));
$('sc-run-proof').addEventListener('click',()=>action(async()=>{runProof();msg('Prova executada pelo mesmo módulo do motor. Confira a trilha e os efeitos não aplicados.');}));
$('sc-brain-proof').addEventListener('click',()=>action(async()=>{const proof=runProof();$('sc-parity').textContent='Consultando o Brain com esta seleção…';try{const response=await requestBrainProof(proof.heroId,proof.published.items,proof.conditions);if(state.proof!==proof)return;const parity=compareStatusCalculations(proof.published.calculation,response.calculationTrace);$('sc-parity').textContent=parity.reason;if(!parity.equal)throw new Error(parity.reason);msg('O Brain confirmou a revisão, os resultados e a origem dos efeitos desta prova.','ok');}catch(error){$('sc-parity').textContent=error.message;throw error;}}));
$('sc-save').addEventListener('click',()=>action(async()=>{const expected=structuredClone(state.draft);await centralRpc('admin_save_status_central_v1',{p_expected_revision:state.data.central.draft_revision,p_payload:expected,p_reason:statusActionRecord('revisão do registro',`${state.draft.definitions.length} status; ${state.draft.bindings.length} vínculos; revisão anterior ${state.data.central.draft_revision||0}.`)});invalidateProof('A revisão foi salva. Execute uma nova prova com a revisão relida.');const reread=await centralRpc('admin_get_status_central_v1');if(stableStatusJson(reread.draft)!==stableStatusJson(expected))throw new Error('A releitura encontrou outra revisão. Suas alterações locais foram preservadas para comparação.');await rereadCentral(reread);msg('Rascunho salvo e confirmado por releitura. Confira a prova antes de publicar.','ok');}));
$('sc-publish').addEventListener('click',()=>action(async()=>{if(state.dirty)throw new Error('Salve o rascunho antes da publicação.');if(state.draft.bindings.length&&(!state.proof||state.proof.signature!==stableStatusJson(state.draft)))throw new Error('Execute a prova do cálculo para este rascunho antes de publicar.');$('sc-publish-summary').textContent=`${state.draft.definitions.length} status e ${state.draft.bindings.length} vínculos. Revisão ${state.data.central.draft_revision}.`;$('sc-publish-check').checked=false;$('sc-publish-dialog').showModal();}));
$('sc-confirm-publish').addEventListener('click',event=>{event.preventDefault();action(async()=>{if(!$('sc-publish-check').checked)throw new Error('Confira a revisão e marque a confirmação no diálogo.');const published=await centralRpc('admin_publish_status_central_v1',{p_expected_revision:state.data.central.draft_revision,p_expected_publication:state.data.central.active_publication,p_reason:statusActionRecord('revisão do registro',`${state.draft.definitions.length} status; ${state.draft.bindings.length} vínculos; revisão anterior ${state.data.central.draft_revision||0}.`)});invalidateProof('A publicação mudou. Execute uma nova prova após a releitura.');$('sc-publish-dialog').close();const reread=await centralRpc('admin_get_status_central_v1');if(reread.active_publication!==published.active_publication||reread.published.fingerprint!==published.published.fingerprint)throw new Error('A publicação foi registrada, mas a releitura encontrou outra publicação. Recarregue a Central para revisar o estado atual.');await rereadCentral(reread);msg('Registro publicado e relido. Execute uma nova prova para confirmar a revisão carregada pelo Brain.','ok');});});
document.addEventListener('click',event=>{const b=event.target.closest('button');if(!b||state.busy)return;if(b.dataset.removeBinding){state.draft.bindings=state.draft.bindings.filter(x=>x.id!==b.dataset.removeBinding);setDirty();}if(b.dataset.register)editStat(state.fields.find(f=>f.locator===b.dataset.register)||state.draft.definitions.find(d=>`registered:${d.id}`===b.dataset.register));if(b.dataset.linkSource){tab('bindings');$('sc-binding-kind').value=b.dataset.kind;updateBindingSources();$('sc-binding-item').value=b.dataset.linkSource;updateBindingLines();}if(b.dataset.skillSource){tab('bindings');$('sc-binding-kind').value='hero_skill';updateBindingSources();$('sc-binding-item').value=b.dataset.skillSource;updateBindingLines();}if(b.dataset.removeSelection!==undefined){state.selections.splice(Number(b.dataset.removeSelection),1);renderLoadout();}if(b.dataset.restore)action(async()=>{if(state.dirty)throw new Error('Salve ou descarte as alterações locais antes de restaurar.');await centralRpc('admin_restore_status_central_v1',{p_expected_revision:state.data.central.draft_revision,p_restore_revision:Number(b.dataset.restore),p_reason:statusActionRecord('revisão do registro',`${state.draft.definitions.length} status; ${state.draft.bindings.length} vínculos; revisão anterior ${state.data.central.draft_revision||0}.`)});invalidateProof('Uma revisão foi restaurada. Execute uma nova prova após a releitura.');await rereadCentral();msg('Revisão restaurada em novo rascunho. Confira as fontes atuais antes de publicar.');});});
window.addEventListener('beforeunload',event=>{if(state.dirty){event.preventDefault();event.returnValue='';}});
$('sc-unit').innerHTML=Object.entries(STATUS_UNITS).map(([id,u])=>`<option value="${id}">${u.label}</option>`).join('');
$('sc-operator').innerHTML='<option value="">Escolha o operador</option>'+Object.entries(STATUS_OPERATORS).map(([id,o])=>`<option value="${id}">${o.label}</option>`).join('');
$('sc-condition').innerHTML=Object.entries(STATUS_CONDITIONS).map(([id,label])=>`<option value="${id}">${label}</option>`).join('');
guided=mountStatusCentralGuided({
  getData:()=>({...state.data,central:{...state.data.central,draft:state.draft}}),action,
  onCentral:async central=>{invalidateProof('O registro mudou. Execute uma nova prova.');guided.invalidate();await rereadCentral(central);},
  openAdvanced:(name,selection)=>{
    tab(name);
    if(name==='proof'&&selection){
      $('sc-proof-hero').value=selection.heroId;
      $('sc-proof-hero').dispatchEvent(new Event('change'));
      $('sc-proof-item').value=selection.equipmentId;updateProofVariants();$('sc-proof-variant').value=selection.variantId;
      state.selections=[{equipmentId:selection.equipmentId,variantId:selection.variantId}];renderLoadout();
      for(const key of ['moving','aiming'])$(`sc-proof-${key}`).value=typeof selection.conditions[key]==='boolean'?String(selection.conditions[key]):'';
      $('sc-proof-ability').value=selection.conditions.activeAbilities?.[0]||(Array.isArray(selection.conditions.activeAbilities)?'none':'');
    }
  },
  openBase:selection=>{tab('stats');const form=$('sc-base-form');form.elements.hero_id.value=selection.heroId;form.elements.scope.value=selection.scope;form.elements.source_key.value=selection.sourceKey;updateBaseReadback();form.scrollIntoView({block:'start'});form.elements.value.focus();}
});
await action(async()=>{await refresh();const params=new URLSearchParams(location.search);if(params.get('equipment'))guided.refresh(params.get('equipment'));});
