#!/usr/bin/env python3
"""Execute the real promo migrations and RPCs in a disposable CI PostgreSQL.

Only the surrounding identity helpers are fixtures. The promo schema, grants,
policies and function bodies come unchanged from the committed migrations.
Never connects to Supabase or accepts a production database endpoint.
"""
from pathlib import Path
import os
import shutil
import subprocess
import time

ROOT = Path(__file__).resolve().parents[1]
BASE_MIGRATIONS = (
    '20260823074346_promo_code_gated_reveal.sql',
    '20260823074404_promo_code_blocked_rereveal_hardening.sql',
    '20260823155922_promo_official_global_sources.sql',
)
FIX = '20260827232940_promo_like_rpc_conflict_fix.sql'
QUICK_ADMIN = '20260831040210_simplify_promo_admin_flow.sql'

if os.environ.get('PGHOST') not in {'promo-db', '127.0.0.1', 'localhost'}:
    raise SystemExit('PROMO RPC DATABASE: refused a non-test database host')
if os.environ.get('PGDATABASE') != 'promo_rpc_test':
    raise SystemExit('PROMO RPC DATABASE: requires the disposable promo_rpc_test database')
if not shutil.which('psql') or not shutil.which('pg_isready'):
    raise SystemExit('PROMO RPC DATABASE: PostgreSQL client tools are required')

for attempt in range(30):
    ready = subprocess.run(['pg_isready', '-q', '-t', '1'], check=False)
    if ready.returncode == 0:
        break
    time.sleep(1)
else:
    raise SystemExit('PROMO RPC DATABASE: disposable database did not become ready')


def sql(source: str, *, check: bool = True):
    result = subprocess.run(
        ['psql', '-X', '--no-password', '-qAt', '-v', 'ON_ERROR_STOP=1',
         '-v', 'VERBOSITY=verbose'],
        input=source, text=True, capture_output=True, timeout=60,
    )
    if check and result.returncode:
        raise SystemExit(result.stderr)
    return result


sql("""
do $$ begin
  if exists(select 1 from pg_class c join pg_namespace n on n.oid = c.relnamespace
            where n.nspname in ('public', 'auth', 'private')
              and c.relkind in ('r', 'p', 'v', 'm')) then
    raise exception 'Refusing to bootstrap a nonempty database';
  end if;
end $$;
create role anon nologin;
create role authenticated nologin;
create role service_role nologin;
create schema auth;
grant usage on schema public, auth to anon, authenticated, service_role;
create table public.profiles(
  id uuid primary key,
  display_name text,
  username text
);
create table public.admin_log(
  id bigint generated by default as identity primary key,
  admin_id uuid,
  action text not null,
  target text,
  detail jsonb,
  created_at timestamptz not null default now()
);
create function auth.uid() returns uuid language sql stable as $$
  select coalesce(
    nullif(current_setting('request.jwt.claim.sub', true), ''),
    nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'sub'
  )::uuid;
$$;
create function public.is_admin() returns boolean language sql stable as $$ select false $$;
create function public.echo_is_admin() returns boolean language sql stable as $$ select false $$;
create function public.is_blocked() returns boolean language sql stable as $$ select false $$;
""")
for name in BASE_MIGRATIONS:
    sql((ROOT / 'supabase/migrations' / name).read_text(encoding='utf-8'))

regression = """
begin;
do $$
declare
  v_promo_id uuid := gen_random_uuid();
  v_user_id uuid := gen_random_uuid();
begin
  insert into public.promo_campaigns(
    id,game,title,source_type,source_name,source_url,
    verification_status,verified_at,status,published,expires_at
  ) values (
    v_promo_id,'Bullet Echo','FIXTURE TRANSACIONAL — NÃO PUBLICAR',
    'official','Bullet Echo — Telegram oficial (RU/global)',
    'https://t.me/bulletecho','verified',now(),'active',true,now()+interval '1 hour'
  );
  insert into private.promo_secrets(promo_id,code)
  values(v_promo_id,'ECHO-RPC-AMBIGUITY-TEST');
  perform set_config('request.jwt.claim.sub',v_user_id::text,true);
  perform * from public.promo_like_and_reveal(v_promo_id);
end $$;
rollback;
"""
before = sql(regression, check=False)
if before.returncode == 0 or '42702' not in before.stderr or '"promo_id" is ambiguous' not in before.stderr:
    raise SystemExit('PROMO RPC DATABASE: regression test did not reproduce the original 42702\n' + before.stderr)
print('PROMO RPC DATABASE: original 42702 reproduced by executing the first like')

sql((ROOT / 'supabase/migrations' / FIX).read_text(encoding='utf-8'))
sql((ROOT / 'supabase/migrations' / QUICK_ADMIN).read_text(encoding='utf-8'))
checks = (ROOT / 'supabase/tests/promo_code_security.sql').read_text(encoding='utf-8')
after = sql(checks)
if after.stdout.strip() != '11|f|f|f|f|t|t|t':
    raise SystemExit('PROMO RPC DATABASE: unexpected security/runtime result\n' + after.stdout)
admin_checks = sql((ROOT / 'supabase/tests/promo_admin_quick_publish.sql').read_text(encoding='utf-8'))
if admin_checks.stdout.strip() != 'promo_admin_quick_publish_ok':
    raise SystemExit('PROMO RPC DATABASE: unexpected quick-admin result\n' + admin_checks.stdout)
counts = sql('select (select count(*) from public.promo_campaigns), '
             '(select count(*) from public.promo_likes), '
             '(select count(*) from private.promo_secrets);')
if counts.stdout.strip() != '0|0|0':
    raise SystemExit('PROMO RPC DATABASE: test fixtures were not rolled back')
print('PROMO RPC DATABASE: 11/11 reveal checks + quick admin publish/remove passed; permissions preserved; fixtures rolled back')
