-- Echo Identity Integrity V2 — hardening adicional em Shadow.
-- Anti-impersonação, deduplicação de Creator/Echo Research e rollout fail-closed.
-- NÃO altera a experiência pública enquanto os gates permanecerem desligados.

begin;

-- ---------------------------------------------------------------------------
-- 1. Gate de rollout: master + capacidades, todas desligadas por padrão.
-- ---------------------------------------------------------------------------
create table if not exists public.echo_identity_rollout_settings (
  singleton boolean primary key default true check (singleton=true),
  schema_version text not null default 'identity-integrity-v2-shadow',
  public_identity_enabled boolean not null default false,
  signup_handle_enabled boolean not null default false,
  public_profiles_enabled boolean not null default false,
  identity_cards_enabled boolean not null default false,
  creator_verification_enabled boolean not null default false,
  research_submission_enabled boolean not null default false,
  updated_by uuid references public.profiles(id) on delete set null,
  last_change_reason text,
  updated_at timestamptz not null default now(),
  constraint echo_identity_rollout_master_guard check (
    public_identity_enabled
    or not (signup_handle_enabled or public_profiles_enabled or identity_cards_enabled or creator_verification_enabled or research_submission_enabled)
  ),
  constraint echo_identity_rollout_reason_length check (last_change_reason is null or char_length(last_change_reason)<=1000)
);

create table if not exists public.echo_identity_rollout_audit (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references public.profiles(id) on delete set null,
  before_state jsonb not null,
  after_state jsonb not null,
  reason text,
  created_at timestamptz not null default now(),
  constraint echo_identity_rollout_audit_reason_length check (reason is null or char_length(reason)<=1000),
  constraint echo_identity_rollout_audit_before_size check (octet_length(before_state::text)<=16384),
  constraint echo_identity_rollout_audit_after_size check (octet_length(after_state::text)<=16384)
);

insert into public.echo_identity_rollout_settings(singleton)
values(true)
on conflict(singleton) do nothing;

create or replace function public.echo_identity_rollout_audit_change()
returns trigger
language plpgsql
security definer
set search_path=''
as $$
begin
  insert into public.echo_identity_rollout_audit(actor_user_id,before_state,after_state,reason)
  values(
    coalesce(new.updated_by,auth.uid()),
    jsonb_build_object(
      'public_identity_enabled',old.public_identity_enabled,
      'signup_handle_enabled',old.signup_handle_enabled,
      'public_profiles_enabled',old.public_profiles_enabled,
      'identity_cards_enabled',old.identity_cards_enabled,
      'creator_verification_enabled',old.creator_verification_enabled,
      'research_submission_enabled',old.research_submission_enabled
    ),
    jsonb_build_object(
      'public_identity_enabled',new.public_identity_enabled,
      'signup_handle_enabled',new.signup_handle_enabled,
      'public_profiles_enabled',new.public_profiles_enabled,
      'identity_cards_enabled',new.identity_cards_enabled,
      'creator_verification_enabled',new.creator_verification_enabled,
      'research_submission_enabled',new.research_submission_enabled
    ),
    new.last_change_reason
  );
  return new;
end;
$$;
revoke all on function public.echo_identity_rollout_audit_change() from public,anon,authenticated,service_role;

drop trigger if exists echo_identity_rollout_settings_audit on public.echo_identity_rollout_settings;
create trigger echo_identity_rollout_settings_audit
after update on public.echo_identity_rollout_settings
for each row execute function public.echo_identity_rollout_audit_change();

create or replace function public.echo_identity_rollout_status_v1()
returns jsonb
language sql
security definer
stable
set search_path=''
as $$
  select jsonb_build_object(
    'schema_version',s.schema_version,
    'public_identity_enabled',s.public_identity_enabled,
    'signup_handle_enabled',s.signup_handle_enabled,
    'public_profiles_enabled',s.public_profiles_enabled,
    'identity_cards_enabled',s.identity_cards_enabled,
    'creator_verification_enabled',s.creator_verification_enabled,
    'research_submission_enabled',s.research_submission_enabled
  )
  from public.echo_identity_rollout_settings s
  where s.singleton=true;
$$;
revoke all on function public.echo_identity_rollout_status_v1() from public;
grant execute on function public.echo_identity_rollout_status_v1() to anon,authenticated;

create or replace function public.admin_set_identity_rollout_v1(
  p_public_identity boolean,
  p_signup_handle boolean,
  p_public_profiles boolean,
  p_identity_cards boolean,
  p_creator_verification boolean,
  p_research_submission boolean,
  p_confirmation text default null,
  p_reason text default null
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
begin
  if not public.echo_is_admin() then
    raise exception 'admin_aal2_required' using errcode='42501';
  end if;
  if (coalesce(p_signup_handle,false) or coalesce(p_public_profiles,false) or coalesce(p_identity_cards,false)
      or coalesce(p_creator_verification,false) or coalesce(p_research_submission,false))
     and not coalesce(p_public_identity,false) then
    raise exception 'identity_rollout_master_required' using errcode='22023';
  end if;
  if (coalesce(p_public_identity,false) or coalesce(p_signup_handle,false) or coalesce(p_public_profiles,false)
      or coalesce(p_identity_cards,false) or coalesce(p_creator_verification,false) or coalesce(p_research_submission,false))
     and coalesce(p_confirmation,'') <> 'ENABLE_IDENTITY_V2' then
    raise exception 'identity_rollout_confirmation_required' using errcode='42501';
  end if;
  if p_reason is not null and char_length(p_reason)>1000 then
    raise exception 'identity_rollout_reason_too_long' using errcode='22023';
  end if;

  update public.echo_identity_rollout_settings
  set public_identity_enabled=coalesce(p_public_identity,false),
      signup_handle_enabled=coalesce(p_signup_handle,false),
      public_profiles_enabled=coalesce(p_public_profiles,false),
      identity_cards_enabled=coalesce(p_identity_cards,false),
      creator_verification_enabled=coalesce(p_creator_verification,false),
      research_submission_enabled=coalesce(p_research_submission,false),
      updated_by=auth.uid(),
      last_change_reason=nullif(btrim(coalesce(p_reason,'')),''),
      updated_at=now()
  where singleton=true;

  return public.echo_identity_rollout_status_v1();
end;
$$;
revoke all on function public.admin_set_identity_rollout_v1(boolean,boolean,boolean,boolean,boolean,boolean,text,text) from public,anon;
grant execute on function public.admin_set_identity_rollout_v1(boolean,boolean,boolean,boolean,boolean,boolean,text,text) to authenticated;

-- ---------------------------------------------------------------------------
-- 2. Display name: Unicode permitido, controles invisíveis e impersonação não.
-- O handle continua ASCII e é a âncora pública principal de identidade.
-- ---------------------------------------------------------------------------
create or replace function public.echo_identity_display_name_has_invisible(p_display text)
returns boolean
language sql
immutable
set search_path=''
as $$
  select coalesce(p_display,'') ~ '[[:cntrl:]]'
    or position(chr(8203) in coalesce(p_display,''))>0
    or position(chr(8204) in coalesce(p_display,''))>0
    or position(chr(8205) in coalesce(p_display,''))>0
    or position(chr(8206) in coalesce(p_display,''))>0
    or position(chr(8207) in coalesce(p_display,''))>0
    or position(chr(8234) in coalesce(p_display,''))>0
    or position(chr(8235) in coalesce(p_display,''))>0
    or position(chr(8236) in coalesce(p_display,''))>0
    or position(chr(8237) in coalesce(p_display,''))>0
    or position(chr(8238) in coalesce(p_display,''))>0
    or position(chr(8288) in coalesce(p_display,''))>0
    or position(chr(8294) in coalesce(p_display,''))>0
    or position(chr(8295) in coalesce(p_display,''))>0
    or position(chr(8296) in coalesce(p_display,''))>0
    or position(chr(8297) in coalesce(p_display,''))>0
    or position(chr(65279) in coalesce(p_display,''))>0;
$$;
revoke all on function public.echo_identity_display_name_has_invisible(text) from public,anon,authenticated;

create or replace function public.echo_identity_display_name_reserved(p_display text)
returns boolean
language sql
immutable
set search_path=''
as $$
  with n as (
    select lower(regexp_replace(btrim(coalesce(p_display,'')),'[[:space:]]+',' ','g')) as value
  )
  select value = any(array[
      'admin','administrator','administrador','moderator','moderador','mod','developer','desenvolvedor','dev',
      'founder','fundador','fundadora','owner','creator','criador','partner','parceiro','support','suporte',
      'staff','official','oficial','echoarena','echo arena','zeptolab','bullet echo','bulletecho'
    ]::text[])
    or value ~ '^(echo ?arena|zeptolab|bullet ?echo)[ ._-]*(admin|staff|support|suporte|official|oficial|moderator|moderador|developer|dev)$'
  from n;
$$;
revoke all on function public.echo_identity_display_name_reserved(text) from public,anon,authenticated;

-- ---------------------------------------------------------------------------
-- 3. Creator: fingerprint de canal e propriedade verificada exclusiva.
-- A normalização é conservadora: trim + remoção de barras finais; não altera path.
-- ---------------------------------------------------------------------------
create or replace function public.echo_creator_channel_fingerprint(p_url text)
returns text
language sql
immutable
set search_path=''
as $$
  select encode(
    extensions.digest(
      convert_to(regexp_replace(btrim(coalesce(p_url,'')),'/+$','','g'),'UTF8'),
      'sha256'
    ),
    'hex'
  );
$$;
revoke all on function public.echo_creator_channel_fingerprint(text) from public,anon,authenticated;

alter table public.echo_creator_claims
  add column if not exists channel_fingerprint text;

update public.echo_creator_claims
set channel_fingerprint=public.echo_creator_channel_fingerprint(channel_url)
where channel_fingerprint is null;

alter table public.echo_creator_claims
  alter column channel_fingerprint set not null;

alter table public.echo_creator_claims
  add constraint echo_creator_claims_channel_fingerprint_format
  check (channel_fingerprint ~ '^[a-f0-9]{64}$');

create index if not exists echo_creator_claims_channel_fingerprint_idx
  on public.echo_creator_claims(channel_fingerprint,status,expires_at);

create unique index if not exists echo_creator_claims_verified_channel_unique
  on public.echo_creator_claims(channel_fingerprint)
  where status='verified';

-- ---------------------------------------------------------------------------
-- 4. Echo Research: fingerprint determinístico e dedupe transacional.
-- ---------------------------------------------------------------------------
create or replace function public.echo_research_submission_fingerprint(
  p_contribution_type text,
  p_subject_key text,
  p_payload jsonb,
  p_hero_id uuid,
  p_skill_id uuid,
  p_game_version text,
  p_evidence_kind text,
  p_evidence_reference text
)
returns text
language sql
immutable
set search_path=''
as $$
  select encode(
    extensions.digest(
      convert_to(
        jsonb_build_object(
          'contribution_type',lower(btrim(coalesce(p_contribution_type,''))),
          'subject_key',lower(btrim(coalesce(p_subject_key,''))),
          'payload',coalesce(p_payload,'{}'::jsonb),
          'hero_id',coalesce(p_hero_id::text,''),
          'skill_id',coalesce(p_skill_id::text,''),
          'game_version',lower(btrim(coalesce(p_game_version,''))),
          'evidence_kind',lower(btrim(coalesce(p_evidence_kind,''))),
          'evidence_reference',btrim(coalesce(p_evidence_reference,''))
        )::text,
        'UTF8'
      ),
      'sha256'
    ),
    'hex'
  );
$$;
revoke all on function public.echo_research_submission_fingerprint(text,text,jsonb,uuid,uuid,text,text,text) from public,anon,authenticated;

alter table public.echo_research_contributions
  add column if not exists submission_fingerprint text;

update public.echo_research_contributions
set submission_fingerprint=public.echo_research_submission_fingerprint(
  contribution_type,subject_key,payload,hero_id,skill_id,game_version,evidence_kind,evidence_reference
)
where submission_fingerprint is null;

alter table public.echo_research_contributions
  alter column submission_fingerprint set not null;

alter table public.echo_research_contributions
  add constraint echo_research_submission_fingerprint_format
  check (submission_fingerprint ~ '^[a-f0-9]{64}$');

create index if not exists echo_research_submission_fingerprint_idx
  on public.echo_research_contributions(contributor_id,submission_fingerprint,submitted_at desc);

-- ---------------------------------------------------------------------------
-- 5. Reforça RPC própria: anti-impersonação + rollout público fail-closed.
-- ---------------------------------------------------------------------------
create or replace function public.echo_set_my_public_identity_v1(
  p_handle text,
  p_display_name text,
  p_bio text default null,
  p_accent text default 'violet',
  p_visibility text default 'public',
  p_allow_messages boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  v_uid uuid := auth.uid();
  v_handle text := lower(btrim(coalesce(p_handle,'')));
  v_display text := btrim(coalesce(p_display_name,''));
  v_bio text := nullif(btrim(coalesce(p_bio,'')), '');
  v_current public.echo_public_profiles%rowtype;
begin
  if v_uid is null then raise exception 'authentication_required' using errcode='42501'; end if;
  if not exists(select 1 from public.profiles p where p.id=v_uid and coalesce(p.is_blocked,false)=false) then
    raise exception 'active_profile_required' using errcode='42501';
  end if;
  if v_handle !~ '^[a-z0-9](?:[a-z0-9._-]{1,22}[a-z0-9])$' then
    raise exception 'invalid_public_handle' using errcode='22023';
  end if;
  if public.echo_identity_handle_reserved(v_handle) then
    raise exception 'reserved_public_handle' using errcode='22023';
  end if;
  if char_length(v_display) not between 2 and 40 then
    raise exception 'invalid_display_name' using errcode='22023';
  end if;
  if public.echo_identity_display_name_has_invisible(v_display) then
    raise exception 'display_name_invisible_characters' using errcode='22023';
  end if;
  if public.echo_identity_display_name_reserved(v_display) then
    raise exception 'display_name_reserved' using errcode='22023';
  end if;
  if v_bio is not null and char_length(v_bio)>240 then raise exception 'bio_too_long' using errcode='22023'; end if;
  if p_accent not in ('violet','cyan','gold','emerald','rose','steel') then raise exception 'invalid_profile_accent' using errcode='22023'; end if;
  if p_visibility not in ('public','private') then raise exception 'invalid_profile_visibility' using errcode='22023'; end if;
  if p_visibility='public' and not exists(
    select 1 from public.echo_identity_rollout_settings s
    where s.singleton=true and s.public_identity_enabled=true and s.public_profiles_enabled=true
  ) then
    raise exception 'identity_public_rollout_disabled' using errcode='42501';
  end if;

  insert into public.echo_public_profiles(user_id,public_handle,profile_visibility)
  values(v_uid,public.echo_identity_generated_handle(v_uid),'private')
  on conflict(user_id) do nothing;

  select * into v_current from public.echo_public_profiles where user_id=v_uid for update;
  if v_current.public_handle<>v_handle
     and v_current.public_handle<>public.echo_identity_generated_handle(v_uid)
     and v_current.handle_changed_at is not null
     and v_current.handle_changed_at>now()-interval '30 days' then
    raise exception 'handle_change_cooldown' using errcode='42501';
  end if;

  begin
    update public.echo_public_profiles
    set public_handle=v_handle,bio=v_bio,profile_accent=p_accent,profile_visibility=p_visibility,
        allow_messages=coalesce(p_allow_messages,false),profile_completed_at=coalesce(profile_completed_at,now()),
        handle_changed_at=case when public_handle is distinct from v_handle then now() else handle_changed_at end
    where user_id=v_uid;
  exception when unique_violation then
    raise exception 'public_handle_unavailable' using errcode='23505';
  end;

  update public.profiles set display_name=v_display where id=v_uid;
  return jsonb_build_object(
    'user_id',v_uid,'public_handle',v_handle,'display_name',v_display,'bio',v_bio,
    'profile_accent',p_accent,'profile_visibility',p_visibility,'allow_messages',coalesce(p_allow_messages,false)
  );
end;
$$;
revoke all on function public.echo_set_my_public_identity_v1(text,text,text,text,text,boolean) from public,anon;
grant execute on function public.echo_set_my_public_identity_v1(text,text,text,text,text,boolean) to authenticated;

-- ---------------------------------------------------------------------------
-- 6. Creator request/review: gate, dedupe e unicidade de propriedade.
-- ---------------------------------------------------------------------------
create or replace function public.echo_request_creator_verification_v1(p_platform text,p_channel_url text)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  v_uid uuid:=auth.uid();
  v_code text;
  v_hash text;
  v_id uuid;
  v_fingerprint text;
begin
  if v_uid is null then raise exception 'authentication_required' using errcode='42501'; end if;
  if not exists(select 1 from public.profiles p where p.id=v_uid and coalesce(p.is_blocked,false)=false) then
    raise exception 'active_profile_required' using errcode='42501';
  end if;
  if not exists(select 1 from public.echo_identity_rollout_settings s where s.singleton=true and s.public_identity_enabled and s.creator_verification_enabled) then
    raise exception 'creator_verification_rollout_disabled' using errcode='42501';
  end if;
  if p_platform not in ('youtube','twitch','tiktok','instagram','facebook','x','other') then
    raise exception 'unsupported_creator_platform' using errcode='22023';
  end if;
  if p_channel_url is null or p_channel_url !~ '^https://' or char_length(p_channel_url)>1000 then
    raise exception 'invalid_creator_channel_url' using errcode='22023';
  end if;

  v_fingerprint:=public.echo_creator_channel_fingerprint(p_channel_url);
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(v_fingerprint,0));

  if exists(select 1 from public.echo_creator_claims c where c.channel_fingerprint=v_fingerprint and c.status='verified') then
    raise exception 'creator_channel_already_verified' using errcode='23505';
  end if;
  if exists(select 1 from public.echo_creator_claims c where c.user_id=v_uid and c.channel_fingerprint=v_fingerprint and c.status='pending' and c.expires_at>now()) then
    raise exception 'creator_claim_already_pending' using errcode='23505';
  end if;
  if (select count(*) from public.echo_creator_claims c where c.user_id=v_uid and c.requested_at>now()-interval '24 hours')>=5 then
    raise exception 'creator_claim_rate_limited' using errcode='42501';
  end if;
  if (select count(*) from public.echo_creator_claims c where c.user_id=v_uid and c.status='pending' and c.expires_at>now())>=3 then
    raise exception 'too_many_pending_creator_claims' using errcode='42501';
  end if;

  v_code:='ECHO-'||upper(substr(encode(extensions.gen_random_bytes(8),'hex'),1,10));
  v_hash:=encode(extensions.digest(convert_to(v_code,'UTF8'),'sha256'),'hex');
  insert into public.echo_creator_claims(user_id,platform,channel_url,channel_fingerprint,proof_code,proof_code_hash,expires_at)
  values(v_uid,p_platform,btrim(p_channel_url),v_fingerprint,v_code,v_hash,now()+interval '7 days')
  returning id into v_id;
  return jsonb_build_object('claim_id',v_id,'proof_code',v_code,'expires_at',now()+interval '7 days');
end;
$$;
revoke all on function public.echo_request_creator_verification_v1(text,text) from public,anon;
grant execute on function public.echo_request_creator_verification_v1(text,text) to authenticated;

create or replace function public.admin_review_creator_claim_v1(p_claim_id uuid,p_decision text,p_note text default null)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  v_claim public.echo_creator_claims%rowtype;
begin
  if not public.echo_is_admin() then raise exception 'admin_aal2_required' using errcode='42501'; end if;
  if p_decision not in ('verified','rejected') then raise exception 'invalid_creator_claim_decision' using errcode='22023'; end if;
  select * into v_claim from public.echo_creator_claims where id=p_claim_id for update;
  if not found then raise exception 'creator_claim_not_found' using errcode='22023'; end if;
  if v_claim.status<>'pending' then raise exception 'creator_claim_already_reviewed' using errcode='22023'; end if;
  if p_decision='verified' and v_claim.expires_at<=now() then
    update public.echo_creator_claims set status='expired',reviewed_by=auth.uid(),reviewed_at=now(),review_note='Desafio expirado antes da verificação.' where id=p_claim_id;
    raise exception 'creator_claim_expired' using errcode='22023';
  end if;
  if p_decision='verified' and exists(
    select 1 from public.echo_creator_claims c
    where c.id<>p_claim_id and c.channel_fingerprint=v_claim.channel_fingerprint and c.status='verified'
  ) then
    raise exception 'creator_channel_already_verified' using errcode='23505';
  end if;

  begin
    update public.echo_creator_claims
    set status=p_decision,reviewed_by=auth.uid(),reviewed_at=now(),review_note=nullif(btrim(coalesce(p_note,'')),'')
    where id=p_claim_id;
  exception when unique_violation then
    raise exception 'creator_channel_already_verified' using errcode='23505';
  end;

  if p_decision='verified' then
    perform public.admin_set_identity_badge_v1(v_claim.user_id,'creator',true,'Canal verificado por desafio EchoArena',v_claim.channel_url);
  end if;
  return jsonb_build_object('claim_id',p_claim_id,'status',p_decision,'user_id',v_claim.user_id);
end;
$$;
revoke all on function public.admin_review_creator_claim_v1(uuid,text,text) from public,anon;
grant execute on function public.admin_review_creator_claim_v1(uuid,text,text) to authenticated;

-- ---------------------------------------------------------------------------
-- 7. Echo Research submit: gate + fingerprint + lock transacional + janela.
-- ---------------------------------------------------------------------------
create or replace function public.echo_submit_research_contribution_v1(
  p_contribution_type text,
  p_subject_key text,
  p_payload jsonb default '{}'::jsonb,
  p_hero_id uuid default null,
  p_skill_id uuid default null,
  p_game_version text default null,
  p_evidence_kind text default 'text',
  p_evidence_reference text default null
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  v_uid uuid:=auth.uid();
  v_id uuid;
  v_payload jsonb:=coalesce(p_payload,'{}'::jsonb);
  v_fingerprint text;
begin
  if v_uid is null then raise exception 'authentication_required' using errcode='42501'; end if;
  if not exists(select 1 from public.profiles p where p.id=v_uid and coalesce(p.is_blocked,false)=false) then
    raise exception 'active_profile_required' using errcode='42501';
  end if;
  if not exists(select 1 from public.echo_identity_rollout_settings s where s.singleton=true and s.public_identity_enabled and s.research_submission_enabled) then
    raise exception 'research_submission_rollout_disabled' using errcode='42501';
  end if;
  if p_contribution_type not in ('hero_skill_level','hero_passive','equipment_stat','patch_change','counter_evidence','other') then
    raise exception 'invalid_contribution_type' using errcode='22023';
  end if;
  if char_length(btrim(coalesce(p_subject_key,''))) not between 1 and 160 then raise exception 'invalid_subject_key' using errcode='22023'; end if;
  if jsonb_typeof(v_payload)<>'object' or octet_length(v_payload::text)>16384 then raise exception 'invalid_contribution_payload' using errcode='22023'; end if;
  if p_evidence_kind not in ('screenshot','video','official_link','community_link','text','other') then raise exception 'invalid_evidence_kind' using errcode='22023'; end if;
  if p_evidence_reference is not null and char_length(p_evidence_reference)>1200 then raise exception 'evidence_reference_too_long' using errcode='22023'; end if;
  if (select count(*) from public.echo_research_contributions c where c.contributor_id=v_uid and c.submitted_at>now()-interval '24 hours')>=30 then
    raise exception 'research_submission_rate_limited' using errcode='42501';
  end if;

  v_fingerprint:=public.echo_research_submission_fingerprint(
    p_contribution_type,p_subject_key,v_payload,p_hero_id,p_skill_id,p_game_version,p_evidence_kind,p_evidence_reference
  );
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(v_uid::text||':'||v_fingerprint,0));

  if exists(
    select 1 from public.echo_research_contributions c
    where c.contributor_id=v_uid and c.submission_fingerprint=v_fingerprint
      and (c.status='pending' or c.submitted_at>now()-interval '7 days')
  ) then
    raise exception 'duplicate_research_submission' using errcode='23505';
  end if;

  insert into public.echo_research_contributions(
    contributor_id,contribution_type,hero_id,skill_id,subject_key,game_version,payload,evidence_kind,evidence_reference,
    submission_fingerprint,status,is_first_discovery
  ) values(
    v_uid,p_contribution_type,p_hero_id,p_skill_id,btrim(p_subject_key),nullif(btrim(coalesce(p_game_version,'')),''),
    v_payload,p_evidence_kind,nullif(btrim(coalesce(p_evidence_reference,'')),''),v_fingerprint,'pending',false
  ) returning id into v_id;
  return jsonb_build_object('contribution_id',v_id,'status','pending');
end;
$$;
revoke all on function public.echo_submit_research_contribution_v1(text,text,jsonb,uuid,uuid,text,text,text) from public,anon;
grant execute on function public.echo_submit_research_contribution_v1(text,text,jsonb,uuid,uuid,text,text,text) to authenticated;

-- ---------------------------------------------------------------------------
-- 8. RPCs públicas de identidade respeitam rollout, mesmo se houver dado público.
-- ---------------------------------------------------------------------------
create or replace function public.echo_public_identity_cards_v1(p_user_ids uuid[])
returns table(
  user_id uuid,public_handle text,display_name text,avatar_url text,profile_accent text,
  community_tier text,reputation_points integer,verified_count integer,first_discoveries integer,
  institutional_role text,institutional_badges jsonb
)
language plpgsql
security definer
stable
set search_path=''
as $$
begin
  if not exists(
    select 1 from public.echo_identity_rollout_settings s
    where s.singleton=true and s.public_identity_enabled and s.public_profiles_enabled and s.identity_cards_enabled
  ) then return; end if;
  if p_user_ids is null or cardinality(p_user_ids)=0 then return; end if;
  if cardinality(p_user_ids)>50 then raise exception 'too_many_identity_cards' using errcode='22023'; end if;
  return query
  select
    p.id,ep.public_handle,p.display_name,p.avatar_url,ep.profile_accent,
    coalesce(r.community_tier,'member'),coalesce(r.reputation_points,0),coalesce(r.verified_count,0),coalesce(r.first_discoveries,0),
    case
      when exists(select 1 from public.echo_founder_authority f where f.user_id=p.id) then 'founder'
      when lower(coalesce(p.role,''))='admin' or coalesce(p.is_admin,false)=true then 'admin'
      when exists(select 1 from public.echo_identity_badges b where b.user_id=p.id and b.badge_type='developer' and b.active=true) then 'developer'
      when exists(select 1 from public.echo_identity_badges b where b.user_id=p.id and b.badge_type='moderator' and b.active=true) then 'moderator'
      when exists(select 1 from public.echo_identity_badges b where b.user_id=p.id and b.badge_type='partner' and b.active=true) then 'partner'
      when exists(select 1 from public.echo_identity_badges b where b.user_id=p.id and b.badge_type='creator' and b.active=true) then 'creator'
      else 'member'
    end,
    coalesce((select jsonb_agg(b.badge_type order by case b.badge_type when 'developer' then 1 when 'moderator' then 2 when 'partner' then 3 else 4 end)
      from public.echo_identity_badges b where b.user_id=p.id and b.active=true),'[]'::jsonb)
  from public.profiles p
  join public.echo_public_profiles ep on ep.user_id=p.id and ep.profile_visibility='public'
  left join public.echo_community_reputation r on r.user_id=p.id
  where p.id=any(p_user_ids) and coalesce(p.is_blocked,false)=false;
end;
$$;
revoke all on function public.echo_public_identity_cards_v1(uuid[]) from public;
grant execute on function public.echo_public_identity_cards_v1(uuid[]) to anon,authenticated;

create or replace function public.echo_public_profile_v1(p_handle text)
returns jsonb
language plpgsql
security definer
stable
set search_path=''
as $$
declare
  v_id uuid;
  v_card jsonb;
  v_recent jsonb;
begin
  if not exists(
    select 1 from public.echo_identity_rollout_settings s
    where s.singleton=true and s.public_identity_enabled and s.public_profiles_enabled and s.identity_cards_enabled
  ) then return null; end if;

  select ep.user_id into v_id
  from public.echo_public_profiles ep
  join public.profiles p on p.id=ep.user_id
  where lower(ep.public_handle)=lower(btrim(coalesce(p_handle,'')))
    and ep.profile_visibility='public' and coalesce(p.is_blocked,false)=false;
  if v_id is null then return null; end if;

  select to_jsonb(c) into v_card from public.echo_public_identity_cards_v1(array[v_id]) c limit 1;
  select coalesce(jsonb_agg(x order by x.submitted_at desc),'[]'::jsonb) into v_recent
  from (
    select c.contribution_type,c.subject_key,c.game_version,c.status,c.is_first_discovery,c.submitted_at,c.reviewed_at
    from public.echo_research_contributions c
    where c.contributor_id=v_id and c.status in ('corroborated','verified')
    order by c.submitted_at desc limit 30
  ) x;
  return jsonb_build_object('identity',v_card,'recent_contributions',v_recent);
end;
$$;
revoke all on function public.echo_public_profile_v1(text) from public;
grant execute on function public.echo_public_profile_v1(text) to anon,authenticated;

-- ---------------------------------------------------------------------------
-- 9. RLS/grants das configurações de rollout.
-- ---------------------------------------------------------------------------
alter table public.echo_identity_rollout_settings enable row level security;
alter table public.echo_identity_rollout_audit enable row level security;

revoke all on table public.echo_identity_rollout_settings from public,anon,authenticated;
revoke all on table public.echo_identity_rollout_audit from public,anon,authenticated;
grant select on table public.echo_identity_rollout_settings to authenticated;
grant select on table public.echo_identity_rollout_audit to authenticated;

drop policy if exists echo_identity_rollout_settings_admin_select on public.echo_identity_rollout_settings;
create policy echo_identity_rollout_settings_admin_select on public.echo_identity_rollout_settings for select to authenticated
using ((select public.echo_is_admin()));

drop policy if exists echo_identity_rollout_audit_admin_select on public.echo_identity_rollout_audit;
create policy echo_identity_rollout_audit_admin_select on public.echo_identity_rollout_audit for select to authenticated
using ((select public.echo_is_admin()));

comment on table public.echo_identity_rollout_settings is 'Gates fail-closed do Echo Identity. Todos nascem desligados; habilitação exige Admin AAL2 e confirmação explícita.';
comment on function public.echo_identity_display_name_has_invisible(text) is 'Bloqueia controles Unicode invisíveis/bidirecionais usados para spoofing sem proibir nomes Unicode legítimos.';
comment on function public.echo_research_submission_fingerprint(text,text,jsonb,uuid,uuid,text,text,text) is 'Fingerprint determinístico para dedupe; nunca transforma evidência em verdade automaticamente.';

commit;
