-- Echo Identity V5 Shadow — Review Ledger + Confirmed Scoring.
-- Toda decisão fica encadeada e imutável. Reputação só usa decisão confirmada
-- por um segundo Admin AAL2 independente do autor e do primeiro revisor.
-- Destino exclusivo: Supabase SNV. Não habilita rollout público.

begin;

-- ---------------------------------------------------------------------------
-- 1. Ledger de decisões por contribuição.
-- ---------------------------------------------------------------------------
create table if not exists public.echo_research_review_events (
  id bigint generated by default as identity primary key,
  contribution_id uuid not null references public.echo_research_contributions(id) on delete restrict,
  contributor_id uuid not null references public.profiles(id) on delete restrict,
  knowledge_fingerprint text not null,
  revision integer not null check (revision>=1),
  previous_status text not null check (previous_status in ('pending','corroborated','verified','rejected','contested','superseded')),
  new_status text not null check (new_status in ('corroborated','verified','rejected','contested','superseded')),
  previous_first_discovery boolean not null,
  new_first_discovery boolean not null,
  reviewer_id uuid not null references public.profiles(id) on delete restrict,
  reviewed_at timestamptz not null,
  review_note_hash text,
  previous_event_hash text,
  event_hash text not null unique,
  guardrail_policy_version text not null,
  created_at timestamptz not null default now(),
  unique(contribution_id,revision),
  constraint echo_research_review_event_knowledge_hash check (knowledge_fingerprint ~ '^[a-f0-9]{64}$'),
  constraint echo_research_review_event_note_hash check (review_note_hash is null or review_note_hash ~ '^[a-f0-9]{64}$'),
  constraint echo_research_review_event_previous_hash check (previous_event_hash is null or previous_event_hash ~ '^[a-f0-9]{64}$'),
  constraint echo_research_review_event_hash check (event_hash ~ '^[a-f0-9]{64}$'),
  constraint echo_research_review_event_first_verified check (not new_first_discovery or new_status='verified')
);

create index if not exists echo_research_review_events_reviewer_idx
  on public.echo_research_review_events(reviewer_id,created_at desc);
create index if not exists echo_research_review_events_contributor_idx
  on public.echo_research_review_events(contributor_id,created_at desc);

create or replace function public.echo_research_review_event_hash_v1(
  p_contribution_id uuid,
  p_contributor_id uuid,
  p_knowledge_fingerprint text,
  p_revision integer,
  p_previous_status text,
  p_new_status text,
  p_previous_first boolean,
  p_new_first boolean,
  p_reviewer_id uuid,
  p_reviewed_at timestamptz,
  p_review_note_hash text,
  p_previous_event_hash text,
  p_policy_version text
)
returns text
language sql
stable
set search_path=''
as $$
  select encode(
    extensions.digest(
      convert_to(
        jsonb_build_object(
          'contribution_id',p_contribution_id,
          'contributor_id',p_contributor_id,
          'knowledge_fingerprint',p_knowledge_fingerprint,
          'revision',p_revision,
          'previous_status',p_previous_status,
          'new_status',p_new_status,
          'previous_first_discovery',p_previous_first,
          'new_first_discovery',p_new_first,
          'reviewer_id',p_reviewer_id,
          'reviewed_at_epoch_us',(extract(epoch from p_reviewed_at)*1000000)::bigint,
          'review_note_hash',p_review_note_hash,
          'previous_event_hash',p_previous_event_hash,
          'guardrail_policy_version',p_policy_version
        )::text,
        'UTF8'
      ),
      'sha256'
    ),
    'hex'
  );
$$;
revoke all on function public.echo_research_review_event_hash_v1(uuid,uuid,text,integer,text,text,boolean,boolean,uuid,timestamptz,text,text,text)
  from public,anon,authenticated,service_role;

alter table public.echo_research_contributions
  add column if not exists review_revision integer not null default 0 check (review_revision>=0),
  add column if not exists current_review_event_id bigint,
  add column if not exists review_confirmation_state text not null default 'not_reviewed';

alter table public.echo_research_contributions
  drop constraint if exists echo_research_confirmation_state_check;
alter table public.echo_research_contributions
  add constraint echo_research_confirmation_state_check
  check (review_confirmation_state in (
    'not_reviewed','awaiting_confirmation','confirmed','disputed','ineligible_self_review','not_applicable'
  ));

-- Um histórico aceito sem revisor identificável não pode ser convertido em
-- reputação por inferência. A implantação para e exige reconciliação humana.
do $$
begin
  if exists(
    select 1 from public.echo_research_contributions c
    where c.status in ('corroborated','verified','rejected','contested') and c.reviewed_by is null
  ) then
    raise exception 'research_review_actor_missing_requires_reconciliation' using errcode='23514';
  end if;
end $$;

-- Backfill fail-closed: decisões existentes ganham evento gênese, mas nenhuma
-- recebe reputação até uma confirmação independente posterior.
do $$
declare
  r record;
  v_note_hash text;
  v_event_hash text;
  v_event_id bigint;
  v_state text;
begin
  for r in
    select c.*
    from public.echo_research_contributions c
    where c.status<>'pending'
    order by coalesce(c.reviewed_at,c.updated_at,c.submitted_at),c.id
  loop
    if r.reviewed_by is null then
      if r.status='superseded' then
        update public.echo_research_contributions
        set review_confirmation_state='not_applicable'
        where id=r.id;
        continue;
      end if;
      raise exception 'research_review_actor_missing_requires_reconciliation' using errcode='23514';
    end if;

    v_note_hash:=case
      when nullif(btrim(coalesce(r.review_note,'')),'') is null then null
      else encode(extensions.digest(convert_to(btrim(r.review_note),'UTF8'),'sha256'),'hex')
    end;
    v_event_hash:=public.echo_research_review_event_hash_v1(
      r.id,r.contributor_id,r.knowledge_fingerprint,1,'pending',r.status,false,r.is_first_discovery,
      r.reviewed_by,coalesce(r.reviewed_at,r.updated_at,r.submitted_at),v_note_hash,null,r.guardrail_policy_version
    );
    insert into public.echo_research_review_events(
      contribution_id,contributor_id,knowledge_fingerprint,revision,previous_status,new_status,
      previous_first_discovery,new_first_discovery,reviewer_id,reviewed_at,review_note_hash,
      previous_event_hash,event_hash,guardrail_policy_version,created_at
    ) values(
      r.id,r.contributor_id,r.knowledge_fingerprint,1,'pending',r.status,false,r.is_first_discovery,
      r.reviewed_by,coalesce(r.reviewed_at,r.updated_at,r.submitted_at),v_note_hash,
      null,v_event_hash,r.guardrail_policy_version,coalesce(r.reviewed_at,r.updated_at,r.submitted_at)
    ) returning id into v_event_id;

    v_state:=case
      when r.status='superseded' then 'not_applicable'
      when r.reviewed_by=r.contributor_id then 'ineligible_self_review'
      else 'awaiting_confirmation'
    end;
    update public.echo_research_contributions
    set review_revision=1,current_review_event_id=v_event_id,review_confirmation_state=v_state
    where id=r.id;
  end loop;
end $$;

alter table public.echo_research_contributions
  drop constraint if exists echo_research_current_review_event_fk;
alter table public.echo_research_contributions
  add constraint echo_research_current_review_event_fk
  foreign key(current_review_event_id) references public.echo_research_review_events(id) on delete restrict;

create index if not exists echo_research_contributor_review_event_v5_idx
  on public.echo_research_contributions(contributor_id,current_review_event_id)
  where current_review_event_id is not null;
create index if not exists echo_research_current_review_event_v5_idx
  on public.echo_research_contributions(current_review_event_id)
  where current_review_event_id is not null;
create index if not exists echo_research_confirmation_queue_v5_idx
  on public.echo_research_contributions(reviewed_at,id)
  where review_confirmation_state='awaiting_confirmation';

create or replace function public.echo_research_review_ledger_before_update_v5()
returns trigger
language plpgsql
security definer
set search_path=''
as $$
declare
  v_previous_hash text;
  v_note_hash text;
  v_event_hash text;
  v_event_id bigint;
  v_revision integer;
begin
  if new.status is not distinct from old.status
     and new.is_first_discovery is not distinct from old.is_first_discovery
     and new.reviewed_by is not distinct from old.reviewed_by
     and new.reviewed_at is not distinct from old.reviewed_at
     and new.review_note is not distinct from old.review_note then
    return new;
  end if;

  if new.status='pending' then
    raise exception 'research_review_cannot_return_pending' using errcode='22023';
  end if;
  if new.reviewed_by is null or new.reviewed_at is null then
    raise exception 'research_review_actor_and_time_required' using errcode='23514';
  end if;
  if new.is_first_discovery and new.status<>'verified' then
    raise exception 'first_discovery_requires_verified' using errcode='22023';
  end if;

  if old.review_revision=0 then
    if old.current_review_event_id is not null then
      raise exception 'research_review_pointer_corrupt' using errcode='23514';
    end if;
    v_previous_hash:=null;
  else
    select e.event_hash into v_previous_hash
    from public.echo_research_review_events e
    where e.id=old.current_review_event_id and e.contribution_id=old.id and e.revision=old.review_revision;
    if v_previous_hash is null then
      raise exception 'research_review_chain_missing' using errcode='23514';
    end if;
  end if;

  v_revision:=old.review_revision+1;
  v_note_hash:=case
    when nullif(btrim(coalesce(new.review_note,'')),'') is null then null
    else encode(extensions.digest(convert_to(btrim(new.review_note),'UTF8'),'sha256'),'hex')
  end;
  v_event_hash:=public.echo_research_review_event_hash_v1(
    new.id,new.contributor_id,new.knowledge_fingerprint,v_revision,old.status,new.status,
    old.is_first_discovery,new.is_first_discovery,new.reviewed_by,new.reviewed_at,
    v_note_hash,v_previous_hash,new.guardrail_policy_version
  );

  insert into public.echo_research_review_events(
    contribution_id,contributor_id,knowledge_fingerprint,revision,previous_status,new_status,
    previous_first_discovery,new_first_discovery,reviewer_id,reviewed_at,review_note_hash,
    previous_event_hash,event_hash,guardrail_policy_version,created_at
  ) values(
    new.id,new.contributor_id,new.knowledge_fingerprint,v_revision,old.status,new.status,
    old.is_first_discovery,new.is_first_discovery,new.reviewed_by,new.reviewed_at,
    v_note_hash,v_previous_hash,v_event_hash,new.guardrail_policy_version,new.reviewed_at
  ) returning id into v_event_id;

  new.review_revision:=v_revision;
  new.current_review_event_id:=v_event_id;
  new.review_confirmation_state:=case
    when new.status='superseded' then 'not_applicable'
    when new.reviewed_by=new.contributor_id then 'ineligible_self_review'
    else 'awaiting_confirmation'
  end;
  return new;
end;
$$;
revoke all on function public.echo_research_review_ledger_before_update_v5() from public,anon,authenticated,service_role;

drop trigger if exists echo_research_review_ledger_v5 on public.echo_research_contributions;
create trigger echo_research_review_ledger_v5
before update of status,is_first_discovery,reviewed_by,reviewed_at,review_note
on public.echo_research_contributions
for each row execute function public.echo_research_review_ledger_before_update_v5();

-- ---------------------------------------------------------------------------
-- 2. Segunda confirmação. Um evento recebe exatamente um desfecho independente.
-- Discordância fecha o evento como disputed e exige nova decisão revisada.
-- ---------------------------------------------------------------------------
create table if not exists public.echo_research_review_confirmations (
  id uuid primary key default extensions.gen_random_uuid(),
  decision_event_id bigint not null unique references public.echo_research_review_events(id) on delete restrict,
  contribution_id uuid not null references public.echo_research_contributions(id) on delete restrict,
  confirmer_id uuid not null references public.profiles(id) on delete restrict,
  outcome text not null check (outcome in ('confirmed','disputed')),
  confirmation_note text,
  confirmation_note_hash text,
  confirmation_hash text not null unique,
  created_at timestamptz not null default now(),
  constraint echo_research_confirmation_note_length check (confirmation_note is null or char_length(confirmation_note)<=1600),
  constraint echo_research_confirmation_note_hash check (confirmation_note_hash is null or confirmation_note_hash ~ '^[a-f0-9]{64}$'),
  constraint echo_research_confirmation_hash check (confirmation_hash ~ '^[a-f0-9]{64}$')
);

create index if not exists echo_research_review_confirmations_contribution_idx
  on public.echo_research_review_confirmations(contribution_id,created_at desc);
create index if not exists echo_research_review_confirmations_confirmer_idx
  on public.echo_research_review_confirmations(confirmer_id,created_at desc);

create or replace function public.echo_immutable_audit_row_v5()
returns trigger
language plpgsql
security definer
set search_path=''
as $$
begin
  raise exception 'immutable_audit_ledger' using errcode='55000';
end;
$$;
revoke all on function public.echo_immutable_audit_row_v5() from public,anon,authenticated,service_role;

drop trigger if exists echo_research_review_events_immutable_v5 on public.echo_research_review_events;
create trigger echo_research_review_events_immutable_v5
before update or delete on public.echo_research_review_events
for each row execute function public.echo_immutable_audit_row_v5();

drop trigger if exists echo_research_review_confirmations_immutable_v5 on public.echo_research_review_confirmations;
create trigger echo_research_review_confirmations_immutable_v5
before update or delete on public.echo_research_review_confirmations
for each row execute function public.echo_immutable_audit_row_v5();

-- ---------------------------------------------------------------------------
-- 3. Revisão primária V5: correções exigem motivo e são limitadas por janela.
-- A função grava o estado; o trigger acima cria a trilha encadeada.
-- ---------------------------------------------------------------------------
create or replace function public.admin_review_research_contribution_v1(
  p_contribution_id uuid,
  p_status text,
  p_note text default null,
  p_first_discovery boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  v_row public.echo_research_contributions%rowtype;
  v_policy public.echo_research_guardrail_policy%rowtype;
  v_event_id bigint;
  v_revision integer;
  v_confirmation_state text;
begin
  if not public.echo_is_admin() then raise exception 'admin_aal2_required' using errcode='42501'; end if;
  if p_status not in ('corroborated','verified','rejected','contested','superseded') then
    raise exception 'invalid_research_review_status' using errcode='22023';
  end if;
  if coalesce(p_first_discovery,false) and p_status<>'verified' then
    raise exception 'first_discovery_requires_verified' using errcode='22023';
  end if;
  if p_note is not null and char_length(p_note)>1600 then
    raise exception 'research_review_note_too_long' using errcode='22023';
  end if;

  select * into v_policy from public.echo_research_guardrail_policy where singleton=true;
  if not found then raise exception 'research_guardrail_policy_missing' using errcode='55000'; end if;

  select * into v_row
  from public.echo_research_contributions
  where id=p_contribution_id
  for update;
  if not found then raise exception 'research_contribution_not_found' using errcode='22023'; end if;

  if v_row.status=p_status
     and v_row.is_first_discovery=coalesce(p_first_discovery,false)
     and v_row.review_confirmation_state<>'disputed' then
    raise exception 'research_review_no_change' using errcode='22023';
  end if;
  if v_row.review_revision>0 and nullif(btrim(coalesce(p_note,'')),'') is null then
    raise exception 'research_rereview_reason_required' using errcode='22023';
  end if;
  if (
    select count(*) from public.echo_research_review_events e
    where e.contribution_id=p_contribution_id
      and e.created_at>now()-(v_policy.submission_window_minutes*interval '1 minute')
  )>=v_policy.max_review_revisions_per_window then
    raise exception 'research_review_revision_limited' using errcode='42501';
  end if;

  if coalesce(p_first_discovery,false) then
    if v_row.contributor_id=auth.uid() then
      raise exception 'first_discovery_self_review_not_allowed' using errcode='42501';
    end if;
    if v_row.knowledge_fingerprint is null then
      raise exception 'first_discovery_knowledge_missing' using errcode='55000';
    end if;
    perform pg_catalog.pg_advisory_xact_lock(
      pg_catalog.hashtextextended('echo-first-discovery:'||v_row.knowledge_fingerprint,0)
    );
    if exists(
      select 1 from public.echo_research_contributions c
      where c.id<>p_contribution_id
        and c.knowledge_fingerprint=v_row.knowledge_fingerprint
        and c.status='verified'
        and c.is_first_discovery=true
    ) then
      raise exception 'first_discovery_already_claimed' using errcode='23505';
    end if;
  end if;

  update public.echo_research_contributions
  set status=p_status,
      is_first_discovery=coalesce(p_first_discovery,false),
      reviewed_by=auth.uid(),
      reviewed_at=now(),
      review_note=nullif(btrim(coalesce(p_note,'')),'')
  where id=p_contribution_id
  returning current_review_event_id,review_revision,review_confirmation_state
  into v_event_id,v_revision,v_confirmation_state;

  -- Uma nova decisão invalida imediatamente qualquer pontuação derivada do
  -- evento anterior. O novo evento só volta a contar depois do segundo parecer.
  perform public.echo_recompute_community_reputation(v_row.contributor_id);

  return jsonb_build_object(
    'contribution_id',p_contribution_id,
    'status',p_status,
    'contributor_id',v_row.contributor_id,
    'first_discovery',coalesce(p_first_discovery,false),
    'decision_event_id',v_event_id,
    'review_revision',v_revision,
    'confirmation_state',v_confirmation_state,
    'independent_review',v_row.contributor_id is distinct from auth.uid(),
    'reputation_effect','none_until_independent_confirmation'
  );
end;
$$;
revoke all on function public.admin_review_research_contribution_v1(uuid,text,text,boolean) from public,anon;
grant execute on function public.admin_review_research_contribution_v1(uuid,text,text,boolean) to authenticated,service_role;

-- ---------------------------------------------------------------------------
-- 4. Reputação V5: somente o evento atual + confirmação independente contam.
-- Um lock por usuário serializa tier e especialidades concorrentes.
-- ---------------------------------------------------------------------------
create or replace function public.echo_recompute_community_reputation(p_user_id uuid)
returns void
language plpgsql
security definer
set search_path=''
as $$
declare
  v_verified integer;
  v_corroborated integer;
  v_first integer;
  v_decided integer;
  v_accepted integer;
  v_points integer;
  v_rate numeric(5,4);
  v_tier text := 'member';
  v_policy text;
  v_verified_points integer;
  v_corroborated_points integer;
  v_first_bonus integer;
begin
  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('echo-community-reputation:'||p_user_id::text,0)
  );

  select m.policy_version,m.verified_points,m.corroborated_points,m.first_discovery_bonus
  into v_policy,v_verified_points,v_corroborated_points,v_first_bonus
  from public.echo_reputation_policy_meta m
  where m.singleton=true;
  if v_policy is null then raise exception 'reputation_policy_missing' using errcode='55000'; end if;

  with eligible as (
    select c.knowledge_fingerprint,c.status,c.is_first_discovery
    from public.echo_research_contributions c
    join public.echo_research_review_events e
      on e.id=c.current_review_event_id
     and e.contribution_id=c.id
     and e.reviewer_id=c.reviewed_by
     and e.new_status=c.status
     and e.new_first_discovery=c.is_first_discovery
    join public.echo_research_review_confirmations f
      on f.decision_event_id=e.id
     and f.contribution_id=c.id
     and f.outcome='confirmed'
    where c.contributor_id=p_user_id
      and c.review_confirmation_state='confirmed'
      and e.reviewer_id is distinct from c.contributor_id
  ), grouped as (
    select
      knowledge_fingerprint,
      bool_or(status='verified') as has_verified,
      bool_or(status='corroborated') as has_corroborated,
      bool_or(status='contested') as has_contested,
      bool_or(status='rejected') as has_rejected,
      bool_or(status='verified' and is_first_discovery=true) as has_first
    from eligible
    group by knowledge_fingerprint
  ), normalized as (
    select
      case
        when has_verified then 'verified'
        when has_corroborated then 'corroborated'
        when has_contested then 'contested'
        when has_rejected then 'rejected'
        else 'neutral'
      end as effective_status,
      has_first
    from grouped
  )
  select
    count(*) filter(where effective_status='verified')::integer,
    count(*) filter(where effective_status='corroborated')::integer,
    count(*) filter(where has_first=true)::integer,
    count(*) filter(where effective_status in ('verified','corroborated','rejected','contested'))::integer
  into v_verified,v_corroborated,v_first,v_decided
  from normalized;

  v_verified:=coalesce(v_verified,0);
  v_corroborated:=coalesce(v_corroborated,0);
  v_first:=coalesce(v_first,0);
  v_decided:=coalesce(v_decided,0);
  v_accepted:=v_verified+v_corroborated;
  v_points:=v_verified*v_verified_points + v_corroborated*v_corroborated_points + v_first*v_first_bonus;
  v_rate:=case when v_decided=0 then 0 else least(1,greatest(0,v_accepted::numeric/v_decided::numeric)) end;

  select r.tier into v_tier
  from public.echo_reputation_tier_rules r
  where r.policy_version=v_policy
    and v_points>=r.min_points
    and v_verified>=r.min_verified
    and v_first>=r.min_first_discoveries
    and v_rate>=r.min_acceptance_rate
  order by r.ordinal desc
  limit 1;
  v_tier:=coalesce(v_tier,'member');

  insert into public.echo_community_reputation(
    user_id,reputation_points,community_tier,verified_count,corroborated_count,first_discoveries,
    acceptance_rate,accepted_count,decided_count,policy_version,updated_at
  ) values(
    p_user_id,v_points,v_tier,v_verified,v_corroborated,v_first,
    v_rate,v_accepted,v_decided,v_policy,now()
  )
  on conflict(user_id) do update set
    reputation_points=excluded.reputation_points,
    community_tier=excluded.community_tier,
    verified_count=excluded.verified_count,
    corroborated_count=excluded.corroborated_count,
    first_discoveries=excluded.first_discoveries,
    acceptance_rate=excluded.acceptance_rate,
    accepted_count=excluded.accepted_count,
    decided_count=excluded.decided_count,
    policy_version=excluded.policy_version,
    updated_at=now();

  delete from public.echo_community_specialty_stats s where s.user_id=p_user_id;

  insert into public.echo_community_specialty_stats(
    user_id,specialty_key,specialty_points,verified_count,corroborated_count,first_discoveries,
    accepted_count,decided_count,acceptance_rate,earned_rank,policy_version,updated_at
  )
  with eligible as (
    select c.contribution_type,c.knowledge_fingerprint,c.status,c.is_first_discovery
    from public.echo_research_contributions c
    join public.echo_research_review_events e
      on e.id=c.current_review_event_id
     and e.contribution_id=c.id
     and e.reviewer_id=c.reviewed_by
     and e.new_status=c.status
     and e.new_first_discovery=c.is_first_discovery
    join public.echo_research_review_confirmations f
      on f.decision_event_id=e.id
     and f.contribution_id=c.id
     and f.outcome='confirmed'
    where c.contributor_id=p_user_id
      and c.review_confirmation_state='confirmed'
      and e.reviewer_id is distinct from c.contributor_id
  ), mapped as (
    select
      case
        when contribution_type in ('hero_skill_level','hero_passive') then 'hero_research'
        when contribution_type='equipment_stat' then 'arsenal'
        when contribution_type='patch_change' then 'patch_hunter'
        when contribution_type='counter_evidence' then 'counter_research'
        else null
      end as specialty_key,
      knowledge_fingerprint,status,is_first_discovery
    from eligible
  ), grouped as (
    select
      specialty_key,knowledge_fingerprint,
      bool_or(status='verified') as has_verified,
      bool_or(status='corroborated') as has_corroborated,
      bool_or(status='contested') as has_contested,
      bool_or(status='rejected') as has_rejected,
      bool_or(status='verified' and is_first_discovery=true) as has_first
    from mapped
    where specialty_key is not null
    group by specialty_key,knowledge_fingerprint
  ), normalized as (
    select
      specialty_key,
      case
        when has_verified then 'verified'
        when has_corroborated then 'corroborated'
        when has_contested then 'contested'
        when has_rejected then 'rejected'
        else 'neutral'
      end as effective_status,
      has_first
    from grouped
  ), aggregated as (
    select
      specialty_key,
      count(*) filter(where effective_status='verified')::integer as verified_count,
      count(*) filter(where effective_status='corroborated')::integer as corroborated_count,
      count(*) filter(where has_first=true)::integer as first_discoveries,
      count(*) filter(where effective_status in ('verified','corroborated','rejected','contested'))::integer as decided_count
    from normalized
    group by specialty_key
  ), scored as (
    select
      a.*,
      (a.verified_count*v_verified_points + a.corroborated_count*v_corroborated_points + a.first_discoveries*v_first_bonus)::integer as specialty_points,
      (a.verified_count+a.corroborated_count)::integer as accepted_count,
      case when a.decided_count=0 then 0::numeric
        else least(1,greatest(0,(a.verified_count+a.corroborated_count)::numeric/a.decided_count::numeric))
      end::numeric(5,4) as acceptance_rate
    from aggregated a
  )
  select
    p_user_id,s.specialty_key,s.specialty_points,s.verified_count,s.corroborated_count,s.first_discoveries,
    s.accepted_count,s.decided_count,s.acceptance_rate,
    coalesce((
      select r.rank_key
      from public.echo_community_specialty_rules r
      where r.policy_version='specialty-v1-shadow'
        and r.specialty_key=s.specialty_key
        and s.specialty_points>=r.min_points
        and s.verified_count>=r.min_verified
        and s.acceptance_rate>=r.min_acceptance_rate
      order by r.ordinal desc
      limit 1
    ),'none'),
    'specialty-v1-shadow',now()
  from scored s;
end;
$$;
revoke all on function public.echo_recompute_community_reputation(uuid) from public,anon,authenticated,service_role;

-- Envios novos sempre nascem pending e não alteram reputação. Evita um
-- recálculo completo/especialidades a cada item aceito na fila anti-spam.
create or replace function public.echo_research_reputation_trigger()
returns trigger
language plpgsql
security definer
set search_path=''
as $$
begin
  if tg_op='INSERT' and new.status='pending' then return new; end if;
  perform public.echo_recompute_community_reputation(coalesce(new.contributor_id,old.contributor_id));
  if tg_op='DELETE' then return old; end if;
  return new;
end;
$$;
revoke all on function public.echo_research_reputation_trigger() from public,anon,authenticated,service_role;

create or replace function public.admin_confirm_research_review_v1(
  p_contribution_id uuid,
  p_decision_event_id bigint,
  p_outcome text,
  p_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  v_uid uuid:=auth.uid();
  v_row public.echo_research_contributions%rowtype;
  v_event public.echo_research_review_events%rowtype;
  v_id uuid:=extensions.gen_random_uuid();
  v_created_at timestamptz:=clock_timestamp();
  v_note text:=nullif(btrim(coalesce(p_note,'')),'');
  v_note_hash text;
  v_confirmation_hash text;
begin
  if not public.echo_is_admin() then raise exception 'admin_aal2_required' using errcode='42501'; end if;
  if p_outcome not in ('confirmed','disputed') then
    raise exception 'invalid_research_confirmation_outcome' using errcode='22023';
  end if;
  if p_note is not null and char_length(p_note)>1600 then
    raise exception 'research_confirmation_note_too_long' using errcode='22023';
  end if;
  if p_outcome='disputed' and v_note is null then
    raise exception 'research_dispute_reason_required' using errcode='22023';
  end if;

  select * into v_row
  from public.echo_research_contributions
  where id=p_contribution_id
  for update;
  if not found then raise exception 'research_contribution_not_found' using errcode='22023'; end if;
  if v_row.current_review_event_id is distinct from p_decision_event_id then
    raise exception 'research_confirmation_stale_decision' using errcode='40001';
  end if;
  if v_row.review_confirmation_state<>'awaiting_confirmation' then
    raise exception 'research_decision_not_awaiting_confirmation' using errcode='22023';
  end if;

  select * into v_event
  from public.echo_research_review_events
  where id=p_decision_event_id and contribution_id=p_contribution_id
  for share;
  if not found then raise exception 'research_review_event_not_found' using errcode='22023'; end if;
  if v_event.reviewer_id=v_uid then
    raise exception 'research_reviewer_cannot_self_confirm' using errcode='42501';
  end if;
  if v_event.contributor_id=v_uid then
    raise exception 'research_contributor_cannot_confirm' using errcode='42501';
  end if;
  if v_event.reviewer_id=v_event.contributor_id then
    raise exception 'self_review_not_confirmation_eligible' using errcode='42501';
  end if;

  v_note_hash:=case when v_note is null then null
    else encode(extensions.digest(convert_to(v_note,'UTF8'),'sha256'),'hex') end;
  v_confirmation_hash:=encode(
    extensions.digest(
      convert_to(
        jsonb_build_object(
          'confirmation_id',v_id,
          'decision_event_id',v_event.id,
          'decision_event_hash',v_event.event_hash,
          'contribution_id',v_row.id,
          'confirmer_id',v_uid,
          'outcome',p_outcome,
          'confirmation_note_hash',v_note_hash,
          'created_at_epoch_us',(extract(epoch from v_created_at)*1000000)::bigint
        )::text,
        'UTF8'
      ),
      'sha256'
    ),
    'hex'
  );

  begin
    insert into public.echo_research_review_confirmations(
      id,decision_event_id,contribution_id,confirmer_id,outcome,confirmation_note,
      confirmation_note_hash,confirmation_hash,created_at
    ) values(
      v_id,v_event.id,v_row.id,v_uid,p_outcome,v_note,v_note_hash,v_confirmation_hash,v_created_at
    );
  exception when unique_violation then
    raise exception 'research_decision_already_confirmed' using errcode='23505';
  end;

  update public.echo_research_contributions
  set review_confirmation_state=p_outcome
  where id=v_row.id;

  perform public.echo_recompute_community_reputation(v_row.contributor_id);

  return jsonb_build_object(
    'contribution_id',v_row.id,
    'decision_event_id',v_event.id,
    'outcome',p_outcome,
    'confirmation_hash',v_confirmation_hash,
    'reputation_recomputed',true
  );
end;
$$;
revoke all on function public.admin_confirm_research_review_v1(uuid,bigint,text,text) from public,anon;
grant execute on function public.admin_confirm_research_review_v1(uuid,bigint,text,text) to authenticated,service_role;

-- A tabela-base contém payload/evidência e notas internas. Membros recebem
-- apenas colunas seguras; o painel AAL2 usa esta fila privilegiada e estreita.
create or replace function public.admin_research_review_queue_v5(
  p_queue text default 'all',
  p_limit integer default 80
)
returns setof public.echo_research_contributions
language plpgsql
security definer
stable
set search_path=''
as $$
declare
  v_limit integer:=least(100,greatest(1,coalesce(p_limit,80)));
begin
  if not public.echo_is_admin() then raise exception 'admin_aal2_required' using errcode='42501'; end if;
  if p_queue not in ('pending','confirmation','all') then
    raise exception 'invalid_research_review_queue' using errcode='22023';
  end if;

  if p_queue = 'pending' then
    return query
    select c.*
    from public.echo_research_contributions c
    where c.status='pending'
    order by c.submitted_at, c.id
    limit v_limit;
    return;
  end if;

  if p_queue = 'confirmation' then
    return query
    select c.*
    from public.echo_research_contributions c
    where c.review_confirmation_state='awaiting_confirmation'
    order by c.reviewed_at, c.id
    limit v_limit;
    return;
  end if;

  return query
  select c.*
  from public.echo_research_contributions c
  where c.status='pending'
     or c.review_confirmation_state='awaiting_confirmation'
  order by coalesce(c.reviewed_at,c.submitted_at),c.id
  limit v_limit;
end;
$$;
revoke all on function public.admin_research_review_queue_v5(text,integer) from public,anon;
grant execute on function public.admin_research_review_queue_v5(text,integer) to authenticated,service_role;

-- ---------------------------------------------------------------------------
-- 5. Encadeamento também para concessões/revogações de autoridade institucional.
-- ---------------------------------------------------------------------------
alter table public.echo_identity_authority_audit
  add column if not exists previous_event_hash text,
  add column if not exists event_hash text,
  add column if not exists chain_version text not null default 'authority-audit-v5';

alter table public.echo_identity_authority_audit
  drop constraint if exists echo_identity_authority_previous_hash_check;
alter table public.echo_identity_authority_audit
  add constraint echo_identity_authority_previous_hash_check
  check (previous_event_hash is null or previous_event_hash ~ '^[a-f0-9]{64}$');
alter table public.echo_identity_authority_audit
  drop constraint if exists echo_identity_authority_event_hash_check;
alter table public.echo_identity_authority_audit
  add constraint echo_identity_authority_event_hash_check
  check (event_hash is null or event_hash ~ '^[a-f0-9]{64}$');

create or replace function public.echo_identity_authority_event_hash_v1(
  p_id bigint,
  p_previous_event_hash text,
  p_target_user_id uuid,
  p_authority_kind text,
  p_authority_value text,
  p_action text,
  p_actor_user_id uuid,
  p_actor_role text,
  p_reason text,
  p_context jsonb,
  p_created_at timestamptz,
  p_chain_version text
)
returns text
language sql
stable
set search_path=''
as $$
  select encode(
    extensions.digest(
      convert_to(
        jsonb_build_object(
          'id',p_id,
          'previous_event_hash',p_previous_event_hash,
          'target_user_id',p_target_user_id,
          'authority_kind',p_authority_kind,
          'authority_value',p_authority_value,
          'action',p_action,
          'actor_user_id',p_actor_user_id,
          'actor_role',p_actor_role,
          'reason',p_reason,
          'context',coalesce(p_context,'{}'::jsonb),
          'created_at_epoch_us',(extract(epoch from p_created_at)*1000000)::bigint,
          'chain_version',p_chain_version
        )::text,
        'UTF8'
      ),
      'sha256'
    ),
    'hex'
  );
$$;
revoke all on function public.echo_identity_authority_event_hash_v1(bigint,text,uuid,text,text,text,uuid,text,text,jsonb,timestamptz,text)
  from public,anon,authenticated,service_role;

do $$
declare
  r record;
  v_previous text:=null;
  v_hash text;
begin
  for r in select * from public.echo_identity_authority_audit order by id loop
    v_hash:=public.echo_identity_authority_event_hash_v1(
      r.id,v_previous,r.target_user_id,r.authority_kind,r.authority_value,r.action,
      r.actor_user_id,r.actor_role,r.reason,r.context,r.created_at,r.chain_version
    );
    update public.echo_identity_authority_audit
    set previous_event_hash=v_previous,event_hash=v_hash
    where id=r.id;
    v_previous:=v_hash;
  end loop;
end $$;

alter table public.echo_identity_authority_audit alter column event_hash set not null;
create unique index if not exists echo_identity_authority_audit_event_hash_uidx
  on public.echo_identity_authority_audit(event_hash);

create table if not exists public.echo_identity_authority_audit_chain_state (
  singleton boolean primary key default true check (singleton=true),
  last_event_id bigint,
  last_event_hash text,
  updated_at timestamptz not null default now(),
  constraint echo_identity_authority_chain_state_hash
    check (last_event_hash is null or last_event_hash ~ '^[a-f0-9]{64}$')
);

insert into public.echo_identity_authority_audit_chain_state(
  singleton,last_event_id,last_event_hash,updated_at
)
select true,a.id,a.event_hash,now()
from public.echo_identity_authority_audit a
order by a.id desc
limit 1
on conflict(singleton) do update set
  last_event_id=excluded.last_event_id,
  last_event_hash=excluded.last_event_hash,
  updated_at=now();

insert into public.echo_identity_authority_audit_chain_state(singleton,last_event_id,last_event_hash)
values(true,null,null)
on conflict(singleton) do nothing;

create or replace function public.echo_identity_authority_audit_chain_v5()
returns trigger
language plpgsql
security definer
set search_path=''
as $$
declare
  v_previous text;
begin
  select s.last_event_hash into v_previous
  from public.echo_identity_authority_audit_chain_state s
  where s.singleton=true
  for update;

  new.previous_event_hash:=v_previous;
  new.chain_version:=coalesce(nullif(new.chain_version,''),'authority-audit-v5');
  new.event_hash:=public.echo_identity_authority_event_hash_v1(
    new.id,new.previous_event_hash,new.target_user_id,new.authority_kind,new.authority_value,new.action,
    new.actor_user_id,new.actor_role,new.reason,new.context,new.created_at,new.chain_version
  );

  update public.echo_identity_authority_audit_chain_state
  set last_event_id=new.id,last_event_hash=new.event_hash,updated_at=now()
  where singleton=true;
  return new;
end;
$$;
revoke all on function public.echo_identity_authority_audit_chain_v5() from public,anon,authenticated,service_role;

drop trigger if exists echo_identity_authority_audit_chain_v5 on public.echo_identity_authority_audit;
create trigger echo_identity_authority_audit_chain_v5
before insert on public.echo_identity_authority_audit
for each row execute function public.echo_identity_authority_audit_chain_v5();

drop trigger if exists echo_identity_authority_audit_immutable_v5 on public.echo_identity_authority_audit;
create trigger echo_identity_authority_audit_immutable_v5
before update or delete on public.echo_identity_authority_audit
for each row execute function public.echo_immutable_audit_row_v5();

-- ---------------------------------------------------------------------------
-- 6. RLS/grants e recálculo fail-closed dos registros existentes.
-- ---------------------------------------------------------------------------
alter table public.echo_research_review_events enable row level security;
alter table public.echo_research_review_confirmations enable row level security;
alter table public.echo_identity_authority_audit_chain_state enable row level security;

revoke all on table public.echo_research_review_events from public,anon,authenticated;
revoke all on table public.echo_research_review_confirmations from public,anon,authenticated;
revoke all on table public.echo_identity_authority_audit_chain_state from public,anon,authenticated;
revoke all on sequence public.echo_research_review_events_id_seq from public,anon,authenticated;
grant select on table public.echo_research_review_events to authenticated;
grant select on table public.echo_research_review_confirmations to authenticated;

revoke select on table public.echo_research_contributions from authenticated;
grant select(
  id,contributor_id,contribution_type,hero_id,skill_id,subject_key,game_version,status,
  is_first_discovery,submitted_at,reviewed_at,updated_at,guardrail_policy_version,
  review_revision,current_review_event_id,review_confirmation_state
) on table public.echo_research_contributions to authenticated;

drop policy if exists echo_research_review_events_admin_read on public.echo_research_review_events;
create policy echo_research_review_events_admin_read on public.echo_research_review_events
for select to authenticated using ((select public.echo_is_admin()));

drop policy if exists echo_research_review_confirmations_admin_read on public.echo_research_review_confirmations;
create policy echo_research_review_confirmations_admin_read on public.echo_research_review_confirmations
for select to authenticated using ((select public.echo_is_admin()));

do $$
declare r record;
begin
  for r in select p.id from public.profiles p loop
    perform public.echo_recompute_community_reputation(r.id);
  end loop;
end $$;

comment on table public.echo_research_review_events is
  'Ledger append-only e hash-chained por contribuição. Toda mudança de decisão cria uma nova revisão imutável.';
comment on table public.echo_research_review_confirmations is
  'Segundo parecer Admin AAL2, independente do autor e do revisor primário. Um evento recebe um único desfecho.';
comment on column public.echo_research_contributions.review_confirmation_state is
  'Efeito atual da decisão sobre reputação: somente confirmed pode entrar no cálculo V5.';
comment on function public.echo_recompute_community_reputation(uuid) is
  'Recalcula tier e especialidades sob lock por usuário, usando conhecimento único com decisão atual e confirmação independente.';
comment on function public.admin_confirm_research_review_v1(uuid,bigint,text,text) is
  'Confirma ou disputa o evento atual. Revisor primário, contribuidor e auto-revisão são inelegíveis para confirmar reputação.';
comment on function public.admin_research_review_queue_v5(text,integer) is
  'Fila AAL2 de decisões pendentes/aguardando confirmação; evita conceder SELECT de payload, evidência e notas internas ao membro.';
comment on table public.echo_identity_authority_audit is
  'Auditoria append-only de autoridade institucional, encadeada por SHA-256 desde authority-audit-v5.';

commit;
