-- Fila persistente de auditoria de equipamentos.
-- O cadastro do equipamento nunca depende desta tabela para existir;
-- quando ela está instalada, cada salvamento revalida os atributos e
-- mantém aqui somente as pendências atuais, preservando o histórico resolvido.

create table if not exists public.equipment_audit_queue (
  id bigint generated by default as identity primary key,
  equipment_id text not null,
  equipment_name text not null default '',
  issue_key text not null,
  source text not null default 'equipment-save',
  severity text not null check (severity in ('blocking','attention','info')),
  issue_type text not null check (issue_type in ('unknown_attribute','invalid_value')),
  status text not null default 'pending' check (status in ('pending','resolved','ignored')),
  rarity_slug text,
  rarity_name text,
  attribute_key text,
  attribute_value text,
  normalized_key text,
  suggested_target text,
  suggested_operation text,
  confidence numeric,
  details jsonb not null default '{}'::jsonb,
  first_seen_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  resolved_at timestamptz,
  unique (equipment_id, issue_key)
);

create index if not exists equipment_audit_queue_status_idx
  on public.equipment_audit_queue (status, severity, updated_at desc);

create index if not exists equipment_audit_queue_equipment_idx
  on public.equipment_audit_queue (equipment_id, status);

alter table public.equipment_audit_queue enable row level security;

-- A área é administrativa e já exige sessão autenticada no frontend.
-- Mantemos as políticas explícitas para leitura e manutenção da fila.
drop policy if exists equipment_audit_queue_authenticated_select on public.equipment_audit_queue;
create policy equipment_audit_queue_authenticated_select
  on public.equipment_audit_queue
  for select
  to authenticated
  using (true);

drop policy if exists equipment_audit_queue_authenticated_insert on public.equipment_audit_queue;
create policy equipment_audit_queue_authenticated_insert
  on public.equipment_audit_queue
  for insert
  to authenticated
  with check (true);

drop policy if exists equipment_audit_queue_authenticated_update on public.equipment_audit_queue;
create policy equipment_audit_queue_authenticated_update
  on public.equipment_audit_queue
  for update
  to authenticated
  using (true)
  with check (true);

drop policy if exists equipment_audit_queue_authenticated_delete on public.equipment_audit_queue;
create policy equipment_audit_queue_authenticated_delete
  on public.equipment_audit_queue
  for delete
  to authenticated
  using (true);
