-- EchoArena — Echo Identity + Echo Scouts V1 em Shadow.
-- Identidade pública, reputação comunitária e autoridade institucional são domínios separados.
-- Destino exclusivo desta migration: Supabase SNV.
-- Nenhum cargo institucional é derivado de cadastro, metadata Auth ou pontos comunitários.

begin;

-- ---------------------------------------------------------------------------
-- 1. Identidade pública: separada da tabela profiles e sem e-mail.
-- ---------------------------------------------------------------------------
create table if not exists public.echo_public_profiles (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  public_handle text not null,
  bio text,
  profile_accent text not null default 'violet'
    check (profile_accent in ('violet','cyan','gold','emerald','rose','steel')),
  profile_visibility text not null default 'private'
    check (profile_visibility in ('public','private')),
  allow_messages boolean not null default false,
  profile_completed_at timestamptz,
  handle_changed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint echo_public_profiles_handle_format check (
    public_handle ~ '^[a-z0-9](?:[a-z0-9._-]{1,22}[a-z0-9])$'
  ),
  constraint echo_public_profiles_bio_length check (bio is null or char_length(bio) <= 240)
);

create unique index if not exists echo_public_profiles_handle_unique_ci
  on public.echo_public_profiles(lower(public_handle));

create or replace function public.echo_identity_generated_handle(p_user_id uuid)
returns text
language sql
immutable
set search_path=''
as $$
  select 'player-' || substr(replace(p_user_id::text, '-', ''), 1, 16);
$$;
revoke all on function public.echo_identity_generated_handle(uuid) from public, anon, authenticated;

create or replace function public.echo_identity_handle_reserved(p_handle text)
returns boolean
language sql
immutable
set search_path=''
as $$
  select lower(coalesce(p_handle,'')) = any(array[
    'admin','administrator','administrador','moderator','moderador','mod','developer','dev',
    'founder','owner','creator','partner','support','suporte','staff','official','oficial',
    'echoarena','echo-arena','echo_arena','zeptolab','bulletecho','bullet-echo'
  ]::text[]);
$$;
revoke all on function public.echo_identity_handle_reserved(text) from public, anon, authenticated;

-- ---------------------------------------------------------------------------
-- 2. Reputação comunitária: conquistada, sem qualquer privilégio administrativo.
-- ---------------------------------------------------------------------------
create table if not exists public.echo_community_reputation (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  reputation_points integer not null default 0 check (reputation_points >= 0),
  community_tier text not null default 'member'
    check (community_tier in ('member','echo_scout','tracker','cartographer','analyst','vanguard','arena_legend')),
  verified_count integer not null default 0 check (verified_count >= 0),
  corroborated_count integer not null default 0 check (corroborated_count >= 0),
  first_discoveries integer not null default 0 check (first_discoveries >= 0),
  acceptance_rate numeric(5,4) not null default 0 check (acceptance_rate between 0 and 1),
  updated_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- 3. Autoridade institucional: concedida, nunca conquistada por pontos.
-- ADMIN é derivado da autoridade técnica existente. FOUNDER não é badge.
-- ---------------------------------------------------------------------------
create table if not exists public.echo_identity_authority_audit (
  id bigint generated by default as identity primary key,
  target_user_id uuid references public.profiles(id) on delete set null,
  authority_kind text not null check (authority_kind in ('badge','founder')),
  authority_value text not null,
  action text not null check (action in ('grant','revoke','transfer','replace')),
  actor_user_id uuid references public.profiles(id) on delete set null,
  actor_role text,
  reason text,
  context jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint echo_identity_authority_audit_reason_length check (reason is null or char_length(reason) <= 1000),
  constraint echo_identity_authority_audit_context_size check (octet_length(context::text) <= 16384)
);

create table if not exists public.echo_identity_badges (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  badge_type text not null check (badge_type in ('creator','partner','moderator','developer')),
  active boolean not null default true,
  reference_url text,
  grant_reason text,
  granted_by uuid references public.profiles(id) on delete set null,
  granted_at timestamptz not null default now(),
  revoked_by uuid references public.profiles(id) on delete set null,
  revoked_at timestamptz,
  updated_at timestamptz not null default now(),
  unique(user_id, badge_type),
  constraint echo_identity_badges_reference_https check (reference_url is null or reference_url ~ '^https://'),
  constraint echo_identity_badges_reason_length check (grant_reason is null or char_length(grant_reason) <= 1000)
);

-- FOUNDER é singleton e só pode ser trocado pelo caminho server-only abaixo.
create table if not exists public.echo_founder_authority (
  singleton boolean primary key default true check (singleton = true),
  user_id uuid not null unique references public.profiles(id) on delete restrict,
  assigned_at timestamptz not null default now(),
  assigned_by uuid references public.profiles(id) on delete set null,
  assignment_reason text,
  updated_at timestamptz not null default now(),
  constraint echo_founder_authority_reason_length check (assignment_reason is null or char_length(assignment_reason) <= 1000)
);

-- ---------------------------------------------------------------------------
-- 4. Creator Verification: desafio de posse de canal, nunca autoatribuição.
-- O proof_code não é credencial do EchoArena: é um desafio público temporário.
-- Mesmo assim, também armazenamos o hash para integridade/auditoria.
-- ---------------------------------------------------------------------------
create table if not exists public.echo_creator_claims (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  platform text not null check (platform in ('youtube','twitch','tiktok','instagram','facebook','x','other')),
  channel_url text not null,
  proof_code text not null,
  proof_code_hash text not null,
  status text not null default 'pending'
    check (status in ('pending','verified','rejected','expired')),
  requested_at timestamptz not null default now(),
  expires_at timestamptz not null,
  reviewed_by uuid references public.profiles(id) on delete set null,
  reviewed_at timestamptz,
  review_note text,
  constraint echo_creator_claims_https check (channel_url ~ '^https://'),
  constraint echo_creator_claims_code_format check (proof_code ~ '^ECHO-[A-F0-9]{10}$'),
  constraint echo_creator_claims_hash_format check (proof_code_hash ~ '^[a-f0-9]{64}$'),
  constraint echo_creator_claims_review_note_length check (review_note is null or char_length(review_note) <= 1200)
);

create index if not exists echo_creator_claims_user_idx
  on public.echo_creator_claims(user_id, requested_at desc);
create index if not exists echo_creator_claims_pending_idx
  on public.echo_creator_claims(status, expires_at, requested_at desc);

-- ---------------------------------------------------------------------------
-- 5. Echo Research: contribuição é evidência pendente; nunca verdade automática.
-- ---------------------------------------------------------------------------
create table if not exists public.echo_research_contributions (
  id uuid primary key default gen_random_uuid(),
  contributor_id uuid not null references public.profiles(id) on delete cascade,
  contribution_type text not null check (contribution_type in (
    'hero_skill_level','hero_passive','equipment_stat','patch_change','counter_evidence','other'
  )),
  hero_id uuid references public.heroes(id) on delete set null,
  skill_id uuid references public.hero_skills(id) on delete set null,
  subject_key text not null,
  game_version text,
  payload jsonb not null default '{}'::jsonb,
  evidence_kind text not null default 'text'
    check (evidence_kind in ('screenshot','video','official_link','community_link','text','other')),
  evidence_reference text,
  status text not null default 'pending'
    check (status in ('pending','corroborated','verified','rejected','contested','superseded')),
  is_first_discovery boolean not null default false,
  submitted_at timestamptz not null default now(),
  reviewed_by uuid references public.profiles(id) on delete set null,
  reviewed_at timestamptz,
  review_note text,
  updated_at timestamptz not null default now(),
  constraint echo_research_subject_length check (char_length(btrim(subject_key)) between 1 and 160),
  constraint echo_research_game_version_length check (game_version is null or char_length(game_version) <= 80),
  constraint echo_research_payload_object check (jsonb_typeof(payload) = 'object'),
  constraint echo_research_payload_size check (octet_length(payload::text) <= 16384),
  constraint echo_research_evidence_length check (evidence_reference is null or char_length(evidence_reference) <= 1200),
  constraint echo_research_review_note_length check (review_note is null or char_length(review_note) <= 1600),
  constraint echo_research_first_discovery_verified check (not is_first_discovery or status = 'verified')
);

create index if not exists echo_research_contributor_idx
  on public.echo_research_contributions(contributor_id, submitted_at desc);
create index if not exists echo_research_review_queue_idx
  on public.echo_research_contributions(status, submitted_at asc);
create index if not exists echo_research_subject_idx
  on public.echo_research_contributions(contribution_type, subject_key, game_version);
create unique index if not exists echo_research_first_discovery_unique
  on public.echo_research_contributions(contribution_type, subject_key, coalesce(game_version,''))
  where is_first_discovery = true and status = 'verified';

-- ---------------------------------------------------------------------------
-- 6. Bootstrap seguro para perfis existentes e novos.
-- O handle automático nunca usa e-mail e começa PRIVADO até escolha explícita.
-- ---------------------------------------------------------------------------
insert into public.echo_public_profiles(user_id, public_handle, profile_visibility)
select p.id, public.echo_identity_generated_handle(p.id), 'private'
from public.profiles p
on conflict (user_id) do nothing;

insert into public.echo_community_reputation(user_id)
select p.id from public.profiles p
on conflict (user_id) do nothing;

create or replace function public.echo_identity_bootstrap_profile()
returns trigger
language plpgsql
security definer
set search_path=''
as $$
begin
  insert into public.echo_public_profiles(user_id, public_handle, profile_visibility)
  values (new.id, public.echo_identity_generated_handle(new.id), 'private')
  on conflict (user_id) do nothing;

  insert into public.echo_community_reputation(user_id)
  values (new.id)
  on conflict (user_id) do nothing;
  return new;
end;
$$;
revoke all on function public.echo_identity_bootstrap_profile() from public, anon, authenticated, service_role;

drop trigger if exists profiles_echo_identity_bootstrap on public.profiles;
create trigger profiles_echo_identity_bootstrap
after insert on public.profiles
for each row execute function public.echo_identity_bootstrap_profile();

-- updated_at compartilhado.
drop trigger if exists echo_public_profiles_set_updated_at on public.echo_public_profiles;
create trigger echo_public_profiles_set_updated_at
before update on public.echo_public_profiles
for each row execute function public.set_updated_at();

drop trigger if exists echo_identity_badges_set_updated_at on public.echo_identity_badges;
create trigger echo_identity_badges_set_updated_at
before update on public.echo_identity_badges
for each row execute function public.set_updated_at();

drop trigger if exists echo_research_contributions_set_updated_at on public.echo_research_contributions;
create trigger echo_research_contributions_set_updated_at
before update on public.echo_research_contributions
for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- 7. RPC de identidade própria. Apelido é ASCII normalizado para evitar homógrafos.
-- ---------------------------------------------------------------------------
create or replace function public.echo_set_my_public_identity_v1(
  p_handle text,
  p_display_name text,
  p_bio text default null,
  p_accent text default 'violet',
  p_visibility text default 'public',
  p_allow_messages boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  v_uid uuid := auth.uid();
  v_handle text := lower(btrim(coalesce(p_handle,'')));
  v_display text := btrim(coalesce(p_display_name,''));
  v_bio text := nullif(btrim(coalesce(p_bio,'')), '');
  v_current public.echo_public_profiles%rowtype;
begin
  if v_uid is null then
    raise exception 'authentication_required' using errcode='42501';
  end if;
  if not exists (select 1 from public.profiles p where p.id=v_uid and coalesce(p.is_blocked,false)=false) then
    raise exception 'active_profile_required' using errcode='42501';
  end if;
  if v_handle !~ '^[a-z0-9](?:[a-z0-9._-]{1,22}[a-z0-9])$' then
    raise exception 'invalid_public_handle' using errcode='22023';
  end if;
  if public.echo_identity_handle_reserved(v_handle) then
    raise exception 'reserved_public_handle' using errcode='22023';
  end if;
  if char_length(v_display) not between 2 and 40 then
    raise exception 'invalid_display_name' using errcode='22023';
  end if;
  if v_bio is not null and char_length(v_bio) > 240 then
    raise exception 'bio_too_long' using errcode='22023';
  end if;
  if p_accent not in ('violet','cyan','gold','emerald','rose','steel') then
    raise exception 'invalid_profile_accent' using errcode='22023';
  end if;
  if p_visibility not in ('public','private') then
    raise exception 'invalid_profile_visibility' using errcode='22023';
  end if;

  insert into public.echo_public_profiles(user_id,public_handle,profile_visibility)
  values(v_uid,public.echo_identity_generated_handle(v_uid),'private')
  on conflict(user_id) do nothing;

  select * into v_current
  from public.echo_public_profiles
  where user_id=v_uid
  for update;

  if v_current.public_handle <> v_handle
     and v_current.public_handle <> public.echo_identity_generated_handle(v_uid)
     and v_current.handle_changed_at is not null
     and v_current.handle_changed_at > now() - interval '30 days' then
    raise exception 'handle_change_cooldown' using errcode='42501';
  end if;

  begin
    update public.echo_public_profiles
    set public_handle=v_handle,
        bio=v_bio,
        profile_accent=p_accent,
        profile_visibility=p_visibility,
        allow_messages=coalesce(p_allow_messages,false),
        profile_completed_at=coalesce(profile_completed_at,now()),
        handle_changed_at=case when public_handle is distinct from v_handle then now() else handle_changed_at end
    where user_id=v_uid;
  exception when unique_violation then
    raise exception 'public_handle_unavailable' using errcode='23505';
  end;

  update public.profiles set display_name=v_display where id=v_uid;

  return jsonb_build_object(
    'user_id',v_uid,'public_handle',v_handle,'display_name',v_display,
    'bio',v_bio,'profile_accent',p_accent,'profile_visibility',p_visibility,
    'allow_messages',coalesce(p_allow_messages,false)
  );
end;
$$;
revoke all on function public.echo_set_my_public_identity_v1(text,text,text,text,text,boolean) from public, anon;
grant execute on function public.echo_set_my_public_identity_v1(text,text,text,text,text,boolean) to authenticated;

-- ---------------------------------------------------------------------------
-- 8. Auditoria de badges e Founder.
-- ---------------------------------------------------------------------------
create or replace function public.echo_identity_audit_authority_change()
returns trigger
language plpgsql
security definer
set search_path=''
as $$
declare
  v_target uuid;
  v_value text;
  v_action text;
  v_reason text;
begin
  if tg_table_name='echo_identity_badges' then
    v_target := coalesce(new.user_id,old.user_id);
    v_value := coalesce(new.badge_type,old.badge_type);
    v_reason := coalesce(new.grant_reason,old.grant_reason);
    v_action := case
      when tg_op='INSERT' then 'grant'
      when tg_op='DELETE' then 'revoke'
      when old.active=false and new.active=true then 'grant'
      when old.active=true and new.active=false then 'revoke'
      else 'replace'
    end;
    insert into public.echo_identity_authority_audit(
      target_user_id,authority_kind,authority_value,action,actor_user_id,actor_role,reason,context
    ) values (
      v_target,'badge',v_value,v_action,auth.uid(),auth.role(),v_reason,
      jsonb_build_object('operation',tg_op)
    );
  else
    v_target := coalesce(new.user_id,old.user_id);
    v_value := 'founder';
    v_reason := coalesce(new.assignment_reason,old.assignment_reason);
    v_action := case when tg_op='INSERT' then 'grant' when tg_op='DELETE' then 'revoke' else 'transfer' end;
    insert into public.echo_identity_authority_audit(
      target_user_id,authority_kind,authority_value,action,actor_user_id,actor_role,reason,context
    ) values (
      v_target,'founder',v_value,v_action,auth.uid(),auth.role(),v_reason,
      jsonb_build_object('operation',tg_op,'previous_user_id',case when tg_op='UPDATE' then old.user_id else null end)
    );
  end if;
  return null;
end;
$$;
revoke all on function public.echo_identity_audit_authority_change() from public, anon, authenticated, service_role;

drop trigger if exists echo_identity_badges_audit on public.echo_identity_badges;
create trigger echo_identity_badges_audit
after insert or update or delete on public.echo_identity_badges
for each row execute function public.echo_identity_audit_authority_change();

drop trigger if exists echo_founder_authority_audit on public.echo_founder_authority;
create trigger echo_founder_authority_audit
after insert or update or delete on public.echo_founder_authority
for each row execute function public.echo_identity_audit_authority_change();

-- Badges institucionais: Admin AAL2 pode conceder somente os tipos não técnicos.
create or replace function public.admin_set_identity_badge_v1(
  p_user_id uuid,
  p_badge_type text,
  p_active boolean,
  p_reason text default null,
  p_reference_url text default null
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
begin
  if not public.echo_is_admin() then
    raise exception 'admin_aal2_required' using errcode='42501';
  end if;
  if p_badge_type not in ('creator','partner','moderator','developer') then
    raise exception 'institutional_badge_not_allowed' using errcode='22023';
  end if;
  if not exists (select 1 from public.profiles p where p.id=p_user_id and coalesce(p.is_blocked,false)=false) then
    raise exception 'target_profile_unavailable' using errcode='22023';
  end if;
  if p_reference_url is not null and p_reference_url !~ '^https://' then
    raise exception 'reference_url_must_be_https' using errcode='22023';
  end if;

  insert into public.echo_identity_badges(
    user_id,badge_type,active,reference_url,grant_reason,granted_by,granted_at,revoked_by,revoked_at
  ) values (
    p_user_id,p_badge_type,coalesce(p_active,false),p_reference_url,nullif(btrim(coalesce(p_reason,'')),''),
    case when p_active then auth.uid() else null end,now(),
    case when not p_active then auth.uid() else null end,case when not p_active then now() else null end
  )
  on conflict(user_id,badge_type) do update set
    active=excluded.active,
    reference_url=coalesce(excluded.reference_url,public.echo_identity_badges.reference_url),
    grant_reason=coalesce(excluded.grant_reason,public.echo_identity_badges.grant_reason),
    granted_by=case when excluded.active then auth.uid() else public.echo_identity_badges.granted_by end,
    granted_at=case when excluded.active then now() else public.echo_identity_badges.granted_at end,
    revoked_by=case when excluded.active then null else auth.uid() end,
    revoked_at=case when excluded.active then null else now() end;

  return jsonb_build_object('user_id',p_user_id,'badge_type',p_badge_type,'active',coalesce(p_active,false));
end;
$$;
revoke all on function public.admin_set_identity_badge_v1(uuid,text,boolean,text,text) from public, anon;
grant execute on function public.admin_set_identity_badge_v1(uuid,text,boolean,text,text) to authenticated;

-- FOUNDER: nenhum Admin normal recebe EXECUTE. Somente service_role pode transferir.
create or replace function public.echo_set_founder_server_only(p_user_id uuid,p_reason text default null)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
begin
  if coalesce(auth.role(),'') <> 'service_role' then
    raise exception 'service_role_required' using errcode='42501';
  end if;
  if not exists (
    select 1 from public.profiles p
    where p.id=p_user_id
      and coalesce(p.is_blocked,false)=false
      and (lower(coalesce(p.role,''))='admin' or coalesce(p.is_admin,false)=true)
  ) then
    raise exception 'founder_must_be_active_admin' using errcode='22023';
  end if;

  insert into public.echo_founder_authority(singleton,user_id,assigned_at,assigned_by,assignment_reason)
  values(true,p_user_id,now(),auth.uid(),nullif(btrim(coalesce(p_reason,'')),''))
  on conflict(singleton) do update set
    user_id=excluded.user_id,assigned_at=now(),assigned_by=auth.uid(),assignment_reason=excluded.assignment_reason,updated_at=now();

  return jsonb_build_object('user_id',p_user_id,'authority','founder');
end;
$$;
revoke all on function public.echo_set_founder_server_only(uuid,text) from public, anon, authenticated;
grant execute on function public.echo_set_founder_server_only(uuid,text) to service_role;

-- ---------------------------------------------------------------------------
-- 9. Creator claims.
-- ---------------------------------------------------------------------------
create or replace function public.echo_request_creator_verification_v1(p_platform text,p_channel_url text)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  v_uid uuid := auth.uid();
  v_code text;
  v_hash text;
  v_id uuid;
begin
  if v_uid is null then raise exception 'authentication_required' using errcode='42501'; end if;
  if not exists (select 1 from public.profiles p where p.id=v_uid and coalesce(p.is_blocked,false)=false) then
    raise exception 'active_profile_required' using errcode='42501';
  end if;
  if p_platform not in ('youtube','twitch','tiktok','instagram','facebook','x','other') then
    raise exception 'unsupported_creator_platform' using errcode='22023';
  end if;
  if p_channel_url is null or p_channel_url !~ '^https://' or char_length(p_channel_url)>1000 then
    raise exception 'invalid_creator_channel_url' using errcode='22023';
  end if;
  if (select count(*) from public.echo_creator_claims c where c.user_id=v_uid and c.requested_at>now()-interval '24 hours') >= 5 then
    raise exception 'creator_claim_rate_limited' using errcode='42501';
  end if;
  if (select count(*) from public.echo_creator_claims c where c.user_id=v_uid and c.status='pending' and c.expires_at>now()) >= 3 then
    raise exception 'too_many_pending_creator_claims' using errcode='42501';
  end if;

  v_code := 'ECHO-' || upper(substr(encode(extensions.gen_random_bytes(8),'hex'),1,10));
  v_hash := encode(extensions.digest(convert_to(v_code,'UTF8'),'sha256'),'hex');
  insert into public.echo_creator_claims(user_id,platform,channel_url,proof_code,proof_code_hash,expires_at)
  values(v_uid,p_platform,p_channel_url,v_code,v_hash,now()+interval '7 days')
  returning id into v_id;
  return jsonb_build_object('claim_id',v_id,'proof_code',v_code,'expires_at',now()+interval '7 days');
end;
$$;
revoke all on function public.echo_request_creator_verification_v1(text,text) from public, anon;
grant execute on function public.echo_request_creator_verification_v1(text,text) to authenticated;

create or replace function public.admin_review_creator_claim_v1(p_claim_id uuid,p_decision text,p_note text default null)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  v_claim public.echo_creator_claims%rowtype;
begin
  if not public.echo_is_admin() then raise exception 'admin_aal2_required' using errcode='42501'; end if;
  if p_decision not in ('verified','rejected') then raise exception 'invalid_creator_claim_decision' using errcode='22023'; end if;
  select * into v_claim from public.echo_creator_claims where id=p_claim_id for update;
  if not found then raise exception 'creator_claim_not_found' using errcode='22023'; end if;
  if v_claim.status <> 'pending' then raise exception 'creator_claim_already_reviewed' using errcode='22023'; end if;
  if p_decision='verified' and v_claim.expires_at <= now() then
    update public.echo_creator_claims set status='expired',reviewed_by=auth.uid(),reviewed_at=now(),review_note='Desafio expirado antes da verificação.' where id=p_claim_id;
    raise exception 'creator_claim_expired' using errcode='22023';
  end if;

  update public.echo_creator_claims
  set status=p_decision,reviewed_by=auth.uid(),reviewed_at=now(),review_note=nullif(btrim(coalesce(p_note,'')),'')
  where id=p_claim_id;

  if p_decision='verified' then
    perform public.admin_set_identity_badge_v1(v_claim.user_id,'creator',true,'Canal verificado por desafio EchoArena',v_claim.channel_url);
  end if;
  return jsonb_build_object('claim_id',p_claim_id,'status',p_decision,'user_id',v_claim.user_id);
end;
$$;
revoke all on function public.admin_review_creator_claim_v1(uuid,text,text) from public, anon;
grant execute on function public.admin_review_creator_claim_v1(uuid,text,text) to authenticated;

-- ---------------------------------------------------------------------------
-- 10. Echo Research + reputação determinística.
-- ---------------------------------------------------------------------------
create or replace function public.echo_recompute_community_reputation(p_user_id uuid)
returns void
language plpgsql
security definer
set search_path=''
as $$
declare
  v_verified integer;
  v_corroborated integer;
  v_first integer;
  v_decided integer;
  v_accepted integer;
  v_points integer;
  v_rate numeric(5,4);
  v_tier text;
begin
  select
    count(*) filter(where status='verified')::integer,
    count(*) filter(where status='corroborated')::integer,
    count(*) filter(where status='verified' and is_first_discovery=true)::integer,
    count(*) filter(where status in ('verified','corroborated','rejected','contested'))::integer
  into v_verified,v_corroborated,v_first,v_decided
  from public.echo_research_contributions
  where contributor_id=p_user_id;

  v_verified:=coalesce(v_verified,0); v_corroborated:=coalesce(v_corroborated,0); v_first:=coalesce(v_first,0); v_decided:=coalesce(v_decided,0);
  v_accepted:=v_verified+v_corroborated;
  v_points:=v_verified*10+v_corroborated*4+v_first*15;
  v_rate:=case when v_decided=0 then 0 else least(1,greatest(0,v_accepted::numeric/v_decided::numeric)) end;
  v_tier:=case
    when v_points>=8000 and v_verified>=400 and v_first>=10 then 'arena_legend'
    when v_points>=2500 and v_verified>=150 then 'vanguard'
    when v_points>=900 and v_verified>=60 then 'analyst'
    when v_points>=350 and v_verified>=25 then 'cartographer'
    when v_points>=120 and v_verified>=10 then 'tracker'
    when v_points>=30 and v_verified>=3 then 'echo_scout'
    else 'member'
  end;

  insert into public.echo_community_reputation(user_id,reputation_points,community_tier,verified_count,corroborated_count,first_discoveries,acceptance_rate,updated_at)
  values(p_user_id,v_points,v_tier,v_verified,v_corroborated,v_first,v_rate,now())
  on conflict(user_id) do update set
    reputation_points=excluded.reputation_points,community_tier=excluded.community_tier,
    verified_count=excluded.verified_count,corroborated_count=excluded.corroborated_count,
    first_discoveries=excluded.first_discoveries,acceptance_rate=excluded.acceptance_rate,updated_at=now();
end;
$$;
revoke all on function public.echo_recompute_community_reputation(uuid) from public, anon, authenticated, service_role;

create or replace function public.echo_research_reputation_trigger()
returns trigger
language plpgsql
security definer
set search_path=''
as $$
begin
  perform public.echo_recompute_community_reputation(coalesce(new.contributor_id,old.contributor_id));
  if tg_op='DELETE' then return old; end if;
  return new;
end;
$$;
revoke all on function public.echo_research_reputation_trigger() from public, anon, authenticated, service_role;

drop trigger if exists echo_research_recompute_reputation on public.echo_research_contributions;
create trigger echo_research_recompute_reputation
after insert or update of status,is_first_discovery or delete on public.echo_research_contributions
for each row execute function public.echo_research_reputation_trigger();

create or replace function public.echo_submit_research_contribution_v1(
  p_contribution_type text,
  p_subject_key text,
  p_payload jsonb default '{}'::jsonb,
  p_hero_id uuid default null,
  p_skill_id uuid default null,
  p_game_version text default null,
  p_evidence_kind text default 'text',
  p_evidence_reference text default null
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  v_uid uuid:=auth.uid();
  v_id uuid;
  v_payload jsonb:=coalesce(p_payload,'{}'::jsonb);
begin
  if v_uid is null then raise exception 'authentication_required' using errcode='42501'; end if;
  if not exists(select 1 from public.profiles p where p.id=v_uid and coalesce(p.is_blocked,false)=false) then
    raise exception 'active_profile_required' using errcode='42501';
  end if;
  if p_contribution_type not in ('hero_skill_level','hero_passive','equipment_stat','patch_change','counter_evidence','other') then
    raise exception 'invalid_contribution_type' using errcode='22023';
  end if;
  if char_length(btrim(coalesce(p_subject_key,''))) not between 1 and 160 then raise exception 'invalid_subject_key' using errcode='22023'; end if;
  if jsonb_typeof(v_payload)<>'object' or octet_length(v_payload::text)>16384 then raise exception 'invalid_contribution_payload' using errcode='22023'; end if;
  if p_evidence_kind not in ('screenshot','video','official_link','community_link','text','other') then raise exception 'invalid_evidence_kind' using errcode='22023'; end if;
  if p_evidence_reference is not null and char_length(p_evidence_reference)>1200 then raise exception 'evidence_reference_too_long' using errcode='22023'; end if;
  if (select count(*) from public.echo_research_contributions c where c.contributor_id=v_uid and c.submitted_at>now()-interval '24 hours') >= 30 then
    raise exception 'research_submission_rate_limited' using errcode='42501';
  end if;

  insert into public.echo_research_contributions(
    contributor_id,contribution_type,hero_id,skill_id,subject_key,game_version,payload,evidence_kind,evidence_reference,status,is_first_discovery
  ) values(
    v_uid,p_contribution_type,p_hero_id,p_skill_id,btrim(p_subject_key),nullif(btrim(coalesce(p_game_version,'')),''),
    v_payload,p_evidence_kind,nullif(btrim(coalesce(p_evidence_reference,'')),''),'pending',false
  ) returning id into v_id;
  return jsonb_build_object('contribution_id',v_id,'status','pending');
end;
$$;
revoke all on function public.echo_submit_research_contribution_v1(text,text,jsonb,uuid,uuid,text,text,text) from public, anon;
grant execute on function public.echo_submit_research_contribution_v1(text,text,jsonb,uuid,uuid,text,text,text) to authenticated;

create or replace function public.admin_review_research_contribution_v1(
  p_contribution_id uuid,
  p_status text,
  p_note text default null,
  p_first_discovery boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  v_row public.echo_research_contributions%rowtype;
begin
  if not public.echo_is_admin() then raise exception 'admin_aal2_required' using errcode='42501'; end if;
  if p_status not in ('corroborated','verified','rejected','contested','superseded') then raise exception 'invalid_research_review_status' using errcode='22023'; end if;
  if coalesce(p_first_discovery,false) and p_status<>'verified' then raise exception 'first_discovery_requires_verified' using errcode='22023'; end if;
  select * into v_row from public.echo_research_contributions where id=p_contribution_id for update;
  if not found then raise exception 'research_contribution_not_found' using errcode='22023'; end if;

  update public.echo_research_contributions set
    status=p_status,is_first_discovery=coalesce(p_first_discovery,false),reviewed_by=auth.uid(),reviewed_at=now(),
    review_note=nullif(btrim(coalesce(p_note,'')),'')
  where id=p_contribution_id;
  return jsonb_build_object('contribution_id',p_contribution_id,'status',p_status,'contributor_id',v_row.contributor_id);
end;
$$;
revoke all on function public.admin_review_research_contribution_v1(uuid,text,text,boolean) from public, anon;
grant execute on function public.admin_review_research_contribution_v1(uuid,text,text,boolean) to authenticated;

-- ---------------------------------------------------------------------------
-- 11. Superfície pública mínima. Nunca retorna e-mail, role bruto ou flags internas.
-- ---------------------------------------------------------------------------
create or replace function public.echo_public_identity_cards_v1(p_user_ids uuid[])
returns table(
  user_id uuid,
  public_handle text,
  display_name text,
  avatar_url text,
  profile_accent text,
  community_tier text,
  reputation_points integer,
  verified_count integer,
  first_discoveries integer,
  institutional_role text,
  institutional_badges jsonb
)
language plpgsql
security definer
stable
set search_path=''
as $$
begin
  if p_user_ids is null or cardinality(p_user_ids)=0 then return; end if;
  if cardinality(p_user_ids)>50 then raise exception 'too_many_identity_cards' using errcode='22023'; end if;
  return query
  select
    p.id,ep.public_handle,p.display_name,p.avatar_url,ep.profile_accent,
    coalesce(r.community_tier,'member'),coalesce(r.reputation_points,0),coalesce(r.verified_count,0),coalesce(r.first_discoveries,0),
    case
      when exists(select 1 from public.echo_founder_authority f where f.user_id=p.id) then 'founder'
      when lower(coalesce(p.role,''))='admin' or coalesce(p.is_admin,false)=true then 'admin'
      when exists(select 1 from public.echo_identity_badges b where b.user_id=p.id and b.badge_type='developer' and b.active=true) then 'developer'
      when exists(select 1 from public.echo_identity_badges b where b.user_id=p.id and b.badge_type='moderator' and b.active=true) then 'moderator'
      when exists(select 1 from public.echo_identity_badges b where b.user_id=p.id and b.badge_type='partner' and b.active=true) then 'partner'
      when exists(select 1 from public.echo_identity_badges b where b.user_id=p.id and b.badge_type='creator' and b.active=true) then 'creator'
      else 'member'
    end,
    coalesce((select jsonb_agg(b.badge_type order by case b.badge_type when 'developer' then 1 when 'moderator' then 2 when 'partner' then 3 else 4 end)
      from public.echo_identity_badges b where b.user_id=p.id and b.active=true),'[]'::jsonb)
  from public.profiles p
  join public.echo_public_profiles ep on ep.user_id=p.id and ep.profile_visibility='public'
  left join public.echo_community_reputation r on r.user_id=p.id
  where p.id=any(p_user_ids) and coalesce(p.is_blocked,false)=false;
end;
$$;
revoke all on function public.echo_public_identity_cards_v1(uuid[]) from public;
grant execute on function public.echo_public_identity_cards_v1(uuid[]) to anon, authenticated;

create or replace function public.echo_public_profile_v1(p_handle text)
returns jsonb
language plpgsql
security definer
stable
set search_path=''
as $$
declare
  v_id uuid;
  v_card jsonb;
  v_recent jsonb;
begin
  select ep.user_id into v_id
  from public.echo_public_profiles ep
  join public.profiles p on p.id=ep.user_id
  where lower(ep.public_handle)=lower(btrim(coalesce(p_handle,'')))
    and ep.profile_visibility='public' and coalesce(p.is_blocked,false)=false;
  if v_id is null then return null; end if;

  select to_jsonb(c) into v_card from public.echo_public_identity_cards_v1(array[v_id]) c limit 1;
  select coalesce(jsonb_agg(x order by x.submitted_at desc),'[]'::jsonb) into v_recent
  from (
    select c.contribution_type,c.subject_key,c.game_version,c.status,c.is_first_discovery,c.submitted_at,c.reviewed_at
    from public.echo_research_contributions c
    where c.contributor_id=v_id and c.status in ('corroborated','verified')
    order by c.submitted_at desc limit 30
  ) x;
  return jsonb_build_object('identity',v_card,'recent_contributions',v_recent);
end;
$$;
revoke all on function public.echo_public_profile_v1(text) from public;
grant execute on function public.echo_public_profile_v1(text) to anon, authenticated;

-- ---------------------------------------------------------------------------
-- 12. RLS e grants: tabelas internas não são superfícies públicas acidentais.
-- ---------------------------------------------------------------------------
alter table public.echo_public_profiles enable row level security;
alter table public.echo_community_reputation enable row level security;
alter table public.echo_identity_authority_audit enable row level security;
alter table public.echo_identity_badges enable row level security;
alter table public.echo_founder_authority enable row level security;
alter table public.echo_creator_claims enable row level security;
alter table public.echo_research_contributions enable row level security;

revoke all on table public.echo_public_profiles from public,anon,authenticated;
revoke all on table public.echo_community_reputation from public,anon,authenticated;
revoke all on table public.echo_identity_authority_audit from public,anon,authenticated;
revoke all on table public.echo_identity_badges from public,anon,authenticated;
revoke all on table public.echo_founder_authority from public,anon,authenticated;
revoke all on table public.echo_creator_claims from public,anon,authenticated;
revoke all on table public.echo_research_contributions from public,anon,authenticated;

grant select on table public.echo_public_profiles to authenticated;
grant select on table public.echo_community_reputation to authenticated;
grant select on table public.echo_identity_authority_audit to authenticated;
grant select on table public.echo_identity_badges to authenticated;
grant select on table public.echo_creator_claims to authenticated;
grant select on table public.echo_research_contributions to authenticated;
-- Sem grant para echo_founder_authority: Founder só é exposto como identidade derivada pela RPC segura.

drop policy if exists echo_public_profiles_self_or_admin on public.echo_public_profiles;
create policy echo_public_profiles_self_or_admin on public.echo_public_profiles for select to authenticated
using (user_id=(select auth.uid()) or (select public.echo_is_admin()));

drop policy if exists echo_community_reputation_self_or_admin on public.echo_community_reputation;
create policy echo_community_reputation_self_or_admin on public.echo_community_reputation for select to authenticated
using (user_id=(select auth.uid()) or (select public.echo_is_admin()));

drop policy if exists echo_identity_authority_audit_admin on public.echo_identity_authority_audit;
create policy echo_identity_authority_audit_admin on public.echo_identity_authority_audit for select to authenticated
using ((select public.echo_is_admin()));

drop policy if exists echo_identity_badges_self_or_admin on public.echo_identity_badges;
create policy echo_identity_badges_self_or_admin on public.echo_identity_badges for select to authenticated
using (user_id=(select auth.uid()) or (select public.echo_is_admin()));

drop policy if exists echo_creator_claims_self_or_admin on public.echo_creator_claims;
create policy echo_creator_claims_self_or_admin on public.echo_creator_claims for select to authenticated
using (user_id=(select auth.uid()) or (select public.echo_is_admin()));

drop policy if exists echo_research_contributions_self_or_admin on public.echo_research_contributions;
create policy echo_research_contributions_self_or_admin on public.echo_research_contributions for select to authenticated
using (contributor_id=(select auth.uid()) or (select public.echo_is_admin()));

comment on table public.echo_public_profiles is 'Identidade pública EchoArena separada de Auth; nenhum e-mail é armazenado nesta superfície.';
comment on table public.echo_community_reputation is 'Progressão Echo Scout conquistada por contribuições revisadas. Não concede qualquer autoridade.';
comment on table public.echo_identity_badges is 'Reconhecimentos institucionais concedidos: Creator, Partner, Moderator e Developer. Admin/Founder são deliberadamente externos a esta tabela.';
comment on table public.echo_founder_authority is 'Autoridade Founder singleton. Transferência somente por caminho service_role/server-only.';
comment on table public.echo_research_contributions is 'Evidências comunitárias. Todo envio nasce pending e só revisão explícita altera seu valor de confiança.';

commit;
