-- Echo Brain — memória versionada de evolução de equipamentos.
-- Objetivo: buffs, nerfs, mudanças de comportamento, raridade e bônus de conjunto
-- nunca sobrescrevem silenciosamente o conhecimento anterior do Brain.

create table if not exists public.equipment_brain_versions (
  id bigint generated by default as identity primary key,
  equipment_id text not null,
  version integer not null check (version > 0),
  season_id uuid references public.seasons(id) on delete set null,
  game_version text,
  source text not null default 'admin-editor',
  change_class text not null default 'mixed_change',
  severity text not null default 'medium' check (severity in ('none','low','medium','high','critical')),
  affects_brain boolean not null default false,
  requires_reevaluation boolean not null default false,
  requires_retraining boolean not null default false,
  semantic_fingerprint text not null,
  before_snapshot jsonb,
  after_snapshot jsonb not null,
  analysis jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  unique (equipment_id, version)
);

create index if not exists equipment_brain_versions_equipment_idx
  on public.equipment_brain_versions (equipment_id, version desc);
create index if not exists equipment_brain_versions_season_idx
  on public.equipment_brain_versions (season_id, created_at desc);
create index if not exists equipment_brain_versions_change_idx
  on public.equipment_brain_versions (affects_brain, requires_retraining, created_at desc);

create table if not exists public.equipment_brain_invalidations (
  id bigint generated by default as identity primary key,
  equipment_id text not null,
  equipment_version_id bigint not null references public.equipment_brain_versions(id) on delete cascade,
  scope text not null check (scope in ('item_fit','build_recommendations','composition_recommendations','training')),
  status text not null default 'pending' check (status in ('pending','resolved','ignored')),
  reason text not null default '',
  affected_rarities text[] not null default '{}'::text[],
  affected_attributes text[] not null default '{}'::text[],
  metadata jsonb not null default '{}'::jsonb,
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  unique (equipment_version_id, scope)
);

create index if not exists equipment_brain_invalidations_pending_idx
  on public.equipment_brain_invalidations (status, scope, created_at desc);
create index if not exists equipment_brain_invalidations_equipment_idx
  on public.equipment_brain_invalidations (equipment_id, status, created_at desc);

-- Fila fail-safe: os triggers marcam o item como alterado mesmo se a etapa de
-- análise semântica no navegador falhar. Assim o Brain nunca considera silêncio
-- de integração como prova de que o conhecimento está atualizado.
create table if not exists public.equipment_brain_change_queue (
  equipment_id text primary key,
  source text not null default 'database-trigger',
  reasons jsonb not null default '[]'::jsonb,
  status text not null default 'pending' check (status in ('pending','processing','resolved','ignored')),
  first_seen_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  resolved_at timestamptz
);

create index if not exists equipment_brain_change_queue_status_idx
  on public.equipment_brain_change_queue (status, updated_at desc);

-- A primeira instalação NÃO considera 0 versões como conhecimento atual.
-- Todo equipamento já existente começa como baseline pendente e só sai da fila
-- depois de receber um snapshot versionado pelo reconciliador administrativo.
insert into public.equipment_brain_change_queue(
  equipment_id, source, reasons, status, first_seen_at, updated_at, resolved_at
)
select
  e.id::text,
  'migration-bootstrap',
  jsonb_build_array(jsonb_build_object(
    'table','equipments',
    'operation','BASELINE_REQUIRED',
    'at',now()
  )),
  'pending',
  now(),
  now(),
  null
from public.equipments e
on conflict (equipment_id) do nothing;

alter table public.equipment_brain_versions enable row level security;
alter table public.equipment_brain_invalidations enable row level security;
alter table public.equipment_brain_change_queue enable row level security;

revoke all on table public.equipment_brain_versions from anon, authenticated;
revoke all on table public.equipment_brain_invalidations from anon, authenticated;
revoke all on table public.equipment_brain_change_queue from anon, authenticated;

grant select on table public.equipment_brain_versions to authenticated;
grant select, update on table public.equipment_brain_invalidations to authenticated;
grant select, update on table public.equipment_brain_change_queue to authenticated;

create policy equipment_brain_versions_admin_select
  on public.equipment_brain_versions for select to authenticated
  using (public.echo_is_admin());

create policy equipment_brain_invalidations_admin_select
  on public.equipment_brain_invalidations for select to authenticated
  using (public.echo_is_admin());
create policy equipment_brain_invalidations_admin_update
  on public.equipment_brain_invalidations for update to authenticated
  using (public.echo_is_admin()) with check (public.echo_is_admin());

create policy equipment_brain_change_queue_admin_select
  on public.equipment_brain_change_queue for select to authenticated
  using (public.echo_is_admin());
create policy equipment_brain_change_queue_admin_update
  on public.equipment_brain_change_queue for update to authenticated
  using (public.echo_is_admin()) with check (public.echo_is_admin());

create or replace function public.echo_brain_mark_equipment_dirty()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_equipment_id text;
  v_reason jsonb;
begin
  v_reason := jsonb_build_object(
    'table', tg_table_name,
    'operation', tg_op,
    'at', now()
  );

  if tg_table_name = 'equipments' then
    v_equipment_id := case when tg_op = 'DELETE' then old.id::text else new.id::text end;
    insert into public.equipment_brain_change_queue(equipment_id,source,reasons,status,updated_at,resolved_at)
    values(v_equipment_id,'database-trigger',jsonb_build_array(v_reason),'pending',now(),null)
    on conflict (equipment_id) do update set
      reasons = public.equipment_brain_change_queue.reasons || jsonb_build_array(v_reason),
      source = 'database-trigger', status = 'pending', updated_at = now(), resolved_at = null;

  elsif tg_table_name = 'equipment_variants' then
    v_equipment_id := case when tg_op = 'DELETE' then old.equipment_id::text else new.equipment_id::text end;
    insert into public.equipment_brain_change_queue(equipment_id,source,reasons,status,updated_at,resolved_at)
    values(v_equipment_id,'database-trigger',jsonb_build_array(v_reason),'pending',now(),null)
    on conflict (equipment_id) do update set
      reasons = public.equipment_brain_change_queue.reasons || jsonb_build_array(v_reason),
      source = 'database-trigger', status = 'pending', updated_at = now(), resolved_at = null;

  elsif tg_table_name = 'equipment_set_bonuses' then
    for v_equipment_id in
      select e.id::text
      from public.equipments e
      where e.set_id::text in (
        case when tg_op = 'INSERT' then new.set_id::text else old.set_id::text end,
        case when tg_op = 'DELETE' then old.set_id::text else new.set_id::text end
      )
    loop
      insert into public.equipment_brain_change_queue(equipment_id,source,reasons,status,updated_at,resolved_at)
      values(v_equipment_id,'database-trigger',jsonb_build_array(v_reason),'pending',now(),null)
      on conflict (equipment_id) do update set
        reasons = public.equipment_brain_change_queue.reasons || jsonb_build_array(v_reason),
        source = 'database-trigger', status = 'pending', updated_at = now(), resolved_at = null;
    end loop;
  end if;

  return null;
end;
$$;

revoke all on function public.echo_brain_mark_equipment_dirty() from public, anon, authenticated;

drop trigger if exists trg_echo_brain_equipment_dirty on public.equipments;
create trigger trg_echo_brain_equipment_dirty
after insert or update or delete on public.equipments
for each row execute function public.echo_brain_mark_equipment_dirty();

drop trigger if exists trg_echo_brain_equipment_variant_dirty on public.equipment_variants;
create trigger trg_echo_brain_equipment_variant_dirty
after insert or update or delete on public.equipment_variants
for each row execute function public.echo_brain_mark_equipment_dirty();

drop trigger if exists trg_echo_brain_equipment_set_bonus_dirty on public.equipment_set_bonuses;
create trigger trg_echo_brain_equipment_set_bonus_dirty
after insert or update or delete on public.equipment_set_bonuses
for each row execute function public.echo_brain_mark_equipment_dirty();

create or replace function public.admin_echo_brain_record_equipment_change(
  p_equipment_id text,
  p_source text,
  p_analysis jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_season_id uuid;
  v_game_version text;
  v_version integer;
  v_version_id bigint;
  v_after jsonb;
  v_before jsonb;
  v_fingerprint text;
  v_last_fingerprint text;
  v_affects boolean;
  v_reevaluate boolean;
  v_retrain boolean;
  v_severity text;
  v_change_class text;
  v_rarities text[] := '{}'::text[];
  v_attributes text[] := '{}'::text[];
begin
  if not public.echo_is_admin() then
    raise exception 'admin_required' using errcode = '42501';
  end if;
  if coalesce(trim(p_equipment_id),'') = '' then raise exception 'equipment_id_required'; end if;
  if p_analysis is null then raise exception 'analysis_required'; end if;

  v_after := p_analysis -> 'after';
  v_before := p_analysis -> 'before';
  if v_after is null then raise exception 'after_snapshot_required'; end if;
  if coalesce(v_after #>> '{equipment,id}','') <> p_equipment_id then
    raise exception 'equipment_snapshot_mismatch';
  end if;

  -- Serializa versões por equipamento. Dois admins salvando o mesmo item ao
  -- mesmo tempo não podem calcular o mesmo max(version)+1.
  perform pg_advisory_xact_lock(hashtextextended(p_equipment_id, 0));

  select s.id, s.game_version into v_season_id, v_game_version
  from public.seasons s
  where s.active is true
  order by s.starts_at desc nulls last, s.created_at desc
  limit 1;

  v_fingerprint := md5(v_after::text);
  select semantic_fingerprint into v_last_fingerprint
  from public.equipment_brain_versions
  where equipment_id = p_equipment_id
  order by version desc
  limit 1;

  if v_last_fingerprint = v_fingerprint then
    update public.equipment_brain_change_queue
    set status='resolved', resolved_at=now(), updated_at=now()
    where equipment_id=p_equipment_id;
    return jsonb_build_object('ok',true,'status','unchanged','fingerprint',v_fingerprint);
  end if;

  select coalesce(max(version),0)+1 into v_version
  from public.equipment_brain_versions
  where equipment_id=p_equipment_id;

  v_affects := coalesce((p_analysis->>'affectsBrain')::boolean,false);
  v_reevaluate := coalesce((p_analysis->>'requiresReevaluation')::boolean,v_affects);
  v_retrain := coalesce((p_analysis->>'requiresRetraining')::boolean,false);
  v_severity := coalesce(nullif(p_analysis->>'severity',''),'medium');
  if v_severity not in ('none','low','medium','high','critical') then v_severity := 'medium'; end if;
  v_change_class := coalesce(nullif(p_analysis->>'changeClass',''),'mixed_change');

  select coalesce(array_agg(value order by value),'{}'::text[]) into v_rarities
  from jsonb_array_elements_text(coalesce(p_analysis->'affectedRarities','[]'::jsonb));
  select coalesce(array_agg(value order by value),'{}'::text[]) into v_attributes
  from jsonb_array_elements_text(coalesce(p_analysis->'affectedAttributes','[]'::jsonb));

  insert into public.equipment_brain_versions(
    equipment_id,version,season_id,game_version,source,change_class,severity,
    affects_brain,requires_reevaluation,requires_retraining,semantic_fingerprint,
    before_snapshot,after_snapshot,analysis,created_by
  ) values (
    p_equipment_id,v_version,v_season_id,v_game_version,coalesce(nullif(p_source,''),'admin-editor'),
    v_change_class,v_severity,v_affects,v_reevaluate,v_retrain,v_fingerprint,
    v_before,v_after,p_analysis,auth.uid()
  ) returning id into v_version_id;

  if v_affects then
    insert into public.equipment_brain_invalidations(
      equipment_id,equipment_version_id,scope,reason,affected_rarities,affected_attributes,metadata
    ) values
      (p_equipment_id,v_version_id,'item_fit',v_change_class,v_rarities,v_attributes,jsonb_build_object('severity',v_severity,'game_version',v_game_version)),
      (p_equipment_id,v_version_id,'build_recommendations',v_change_class,v_rarities,v_attributes,jsonb_build_object('severity',v_severity,'game_version',v_game_version)),
      (p_equipment_id,v_version_id,'composition_recommendations',v_change_class,v_rarities,v_attributes,jsonb_build_object('severity',v_severity,'game_version',v_game_version))
    on conflict (equipment_version_id,scope) do nothing;
  end if;

  if v_retrain then
    insert into public.equipment_brain_invalidations(
      equipment_id,equipment_version_id,scope,reason,affected_rarities,affected_attributes,metadata
    ) values (
      p_equipment_id,v_version_id,'training','equipment_behavior_changed',v_rarities,v_attributes,
      jsonb_build_object('severity',v_severity,'game_version',v_game_version)
    ) on conflict (equipment_version_id,scope) do nothing;
  end if;

  update public.equipment_brain_change_queue
  set status='resolved', resolved_at=now(), updated_at=now()
  where equipment_id=p_equipment_id;

  return jsonb_build_object(
    'ok',true,
    'status','versioned',
    'equipmentId',p_equipment_id,
    'equipmentVersion',v_version,
    'equipmentVersionId',v_version_id,
    'seasonId',v_season_id,
    'gameVersion',v_game_version,
    'changeClass',v_change_class,
    'severity',v_severity,
    'affectsBrain',v_affects,
    'requiresRetraining',v_retrain,
    'fingerprint',v_fingerprint
  );
end;
$$;

revoke all on function public.admin_echo_brain_record_equipment_change(text,text,jsonb) from public, anon;
grant execute on function public.admin_echo_brain_record_equipment_change(text,text,jsonb) to authenticated;

-- Leitura pública mínima de frescor. Não expõe snapshots, diff nem pesos do Brain.
create or replace function public.echo_brain_equipment_freshness(p_equipment_ids text[])
returns jsonb
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select coalesce(jsonb_agg(jsonb_build_object(
    'equipmentId', latest.equipment_id,
    'version', latest.version,
    'gameVersion', latest.game_version,
    'fingerprint', latest.semantic_fingerprint,
    'changedAt', latest.created_at,
    'pendingInvalidations', latest.pending_invalidations
  ) order by latest.equipment_id),'[]'::jsonb)
  from (
    select distinct on (v.equipment_id)
      v.equipment_id,
      v.version,
      v.game_version,
      v.semantic_fingerprint,
      v.created_at,
      (select count(*) from public.equipment_brain_invalidations i where i.equipment_version_id=v.id and i.status='pending') as pending_invalidations
    from public.equipment_brain_versions v
    where v.equipment_id = any(coalesce(p_equipment_ids,'{}'::text[]))
    order by v.equipment_id, v.version desc
  ) latest;
$$;

revoke all on function public.echo_brain_equipment_freshness(text[]) from public;
grant execute on function public.echo_brain_equipment_freshness(text[]) to anon, authenticated;

comment on table public.equipment_brain_versions is
  'Echo Brain: histórico imutável de cada estado semântico de equipamento por temporada/versão do jogo.';
comment on table public.equipment_brain_invalidations is
  'Echo Brain: recomendações/caches que ficaram obsoletos após buff, nerf ou mudança de comportamento de equipamento.';
comment on table public.equipment_brain_change_queue is
  'Echo Brain: fila fail-safe marcada por triggers sempre que equipamento, variante ou bônus de conjunto muda.';
