-- Histórico permanente da Auditoria e políticas administrativas.
-- Objetivos:
-- 1) registrar decisões de classificação e mudanças nas regras de bônus;
-- 2) permitir rastreabilidade quando várias pessoas trabalham no painel;
-- 3) impedir que usuários autenticados comuns alterem a fila/classificações.

create or replace function public.echo_is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles p
    left join public.roles r on r.id = p.role_id
    where p.id = auth.uid()
      and (
        coalesce(p.is_admin, false) = true
        or lower(coalesce(p.role, '')) = 'admin'
        or lower(coalesce(r.name, '')) = 'admin'
      )
  );
$$;

revoke all on function public.echo_is_admin() from public;
grant execute on function public.echo_is_admin() to authenticated;

-- Mantém leitura pública somente das classificações ativas, pois o frontend
-- usa essas decisões para explicar efeitos não calculados. Escritas ficam
-- restritas a administradores reais do painel.
drop policy if exists equipment_attribute_classifications_authenticated_insert on public.equipment_attribute_classifications;
drop policy if exists equipment_attribute_classifications_authenticated_update on public.equipment_attribute_classifications;
drop policy if exists equipment_attribute_classifications_authenticated_delete on public.equipment_attribute_classifications;

create policy equipment_attribute_classifications_admin_insert
  on public.equipment_attribute_classifications
  for insert to authenticated
  with check (public.echo_is_admin());

create policy equipment_attribute_classifications_admin_update
  on public.equipment_attribute_classifications
  for update to authenticated
  using (public.echo_is_admin())
  with check (public.echo_is_admin());

create policy equipment_attribute_classifications_admin_delete
  on public.equipment_attribute_classifications
  for delete to authenticated
  using (public.echo_is_admin());

-- A fila da Auditoria é administrativa. Usuários autenticados comuns não
-- devem ler nem alterar pendências internas do projeto.
drop policy if exists equipment_audit_queue_authenticated_select on public.equipment_audit_queue;
drop policy if exists equipment_audit_queue_authenticated_insert on public.equipment_audit_queue;
drop policy if exists equipment_audit_queue_authenticated_update on public.equipment_audit_queue;
drop policy if exists equipment_audit_queue_authenticated_delete on public.equipment_audit_queue;

create policy equipment_audit_queue_admin_select
  on public.equipment_audit_queue
  for select to authenticated
  using (public.echo_is_admin());

create policy equipment_audit_queue_admin_insert
  on public.equipment_audit_queue
  for insert to authenticated
  with check (public.echo_is_admin());

create policy equipment_audit_queue_admin_update
  on public.equipment_audit_queue
  for update to authenticated
  using (public.echo_is_admin())
  with check (public.echo_is_admin());

create policy equipment_audit_queue_admin_delete
  on public.equipment_audit_queue
  for delete to authenticated
  using (public.echo_is_admin());

create table if not exists public.equipment_audit_history (
  id bigint generated by default as identity primary key,
  entity_type text not null check (entity_type in ('attribute_classification','set_bonus')),
  entity_id text not null,
  action text not null,
  summary text not null default '',
  before_data jsonb,
  after_data jsonb,
  actor_id uuid,
  actor_email text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists equipment_audit_history_created_idx
  on public.equipment_audit_history (created_at desc);
create index if not exists equipment_audit_history_entity_idx
  on public.equipment_audit_history (entity_type, entity_id, created_at desc);

alter table public.equipment_audit_history enable row level security;

drop policy if exists equipment_audit_history_admin_select on public.equipment_audit_history;
create policy equipment_audit_history_admin_select
  on public.equipment_audit_history
  for select to authenticated
  using (public.echo_is_admin());

grant select on public.equipment_audit_history to authenticated;

create or replace function public.log_equipment_attribute_classification_history()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_action text;
  v_email text;
begin
  if tg_op = 'INSERT' then
    v_action := case when new.active then 'classificacao_criada' else 'classificacao_criada_inativa' end;
  elsif old.active is distinct from new.active then
    v_action := case when new.active then 'classificacao_reativada' else 'classificacao_reaberta' end;
  else
    v_action := 'classificacao_atualizada';
  end if;

  begin
    v_email := auth.jwt() ->> 'email';
  exception when others then
    v_email := null;
  end;

  insert into public.equipment_audit_history (
    entity_type,
    entity_id,
    action,
    summary,
    before_data,
    after_data,
    actor_id,
    actor_email,
    metadata
  ) values (
    'attribute_classification',
    new.normalized_key,
    v_action,
    coalesce(new.display_label, new.raw_label, new.normalized_key),
    case when tg_op = 'UPDATE' then to_jsonb(old) else null end,
    to_jsonb(new),
    auth.uid(),
    v_email,
    jsonb_build_object('classification', new.classification)
  );

  return new;
end;
$$;

revoke all on function public.log_equipment_attribute_classification_history() from public;

create or replace function public.log_equipment_set_bonus_stats_history()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_email text;
begin
  if old.stats is not distinct from new.stats then
    return new;
  end if;

  begin
    v_email := auth.jwt() ->> 'email';
  exception when others then
    v_email := null;
  end;

  insert into public.equipment_audit_history (
    entity_type,
    entity_id,
    action,
    summary,
    before_data,
    after_data,
    actor_id,
    actor_email,
    metadata
  ) values (
    'set_bonus',
    new.id::text,
    'regra_calculo_alterada',
    concat(coalesce(new.title, 'Bônus'), ' · ', coalesce(new.required_pieces::text, '?'), ' peças'),
    jsonb_build_object('stats', old.stats, 'description', old.description),
    jsonb_build_object('stats', new.stats, 'description', new.description),
    auth.uid(),
    v_email,
    jsonb_build_object('set_id', new.set_id, 'required_pieces', new.required_pieces)
  );

  return new;
end;
$$;

revoke all on function public.log_equipment_set_bonus_stats_history() from public;

drop trigger if exists trg_equipment_attribute_classification_history on public.equipment_attribute_classifications;
create trigger trg_equipment_attribute_classification_history
after insert or update on public.equipment_attribute_classifications
for each row execute function public.log_equipment_attribute_classification_history();

drop trigger if exists trg_equipment_set_bonus_stats_history on public.equipment_set_bonuses;
create trigger trg_equipment_set_bonus_stats_history
after update of stats on public.equipment_set_bonuses
for each row execute function public.log_equipment_set_bonus_stats_history();

-- Baseline para que a primeira pessoa que abrir o histórico saiba que as
-- classificações atuais já existiam antes deste mecanismo de rastreio.
insert into public.equipment_audit_history (
  entity_type, entity_id, action, summary, after_data, metadata
)
select
  'attribute_classification',
  normalized_key,
  'baseline_classificacao',
  coalesce(display_label, raw_label, normalized_key),
  to_jsonb(c),
  jsonb_build_object('classification', classification, 'baseline', true)
from public.equipment_attribute_classifications c
where not exists (
  select 1 from public.equipment_audit_history h
  where h.entity_type = 'attribute_classification'
    and h.entity_id = c.normalized_key
    and h.action = 'baseline_classificacao'
);
