-- Echo Brain — fonte de verdade versionada, grafo, contrafactuais e proveniência.
-- Esta migration NÃO substitui equipment_brain_versions. Ela agrega a memória de
-- equipamentos existente com perfis completos de herói e contratos de decisão.

create table if not exists public.echo_brain_knowledge_versions (
  id bigint generated by default as identity primary key,
  entity_type text not null check (entity_type in ('hero_profile','ruleset')),
  entity_id text not null,
  version integer not null check (version > 0),
  season_id uuid references public.seasons(id) on delete set null,
  game_version text,
  source text not null default 'knowledge-reconcile',
  change_class text not null default 'knowledge_change',
  semantic_fingerprint text not null,
  snapshot jsonb not null,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  unique(entity_type, entity_id, version)
);

create index if not exists echo_brain_knowledge_versions_entity_idx
  on public.echo_brain_knowledge_versions(entity_type, entity_id, version desc);
create index if not exists echo_brain_knowledge_versions_season_idx
  on public.echo_brain_knowledge_versions(season_id, created_at desc);

create table if not exists public.echo_brain_knowledge_change_queue (
  entity_type text not null check (entity_type in ('hero_profile','ruleset')),
  entity_id text not null,
  source text not null default 'database-trigger',
  reasons jsonb not null default '[]'::jsonb,
  status text not null default 'pending' check (status in ('pending','processing','resolved','ignored')),
  first_seen_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  resolved_at timestamptz,
  primary key(entity_type, entity_id)
);

create table if not exists public.echo_brain_knowledge_invalidations (
  id bigint generated by default as identity primary key,
  knowledge_version_id bigint not null references public.echo_brain_knowledge_versions(id) on delete cascade,
  entity_type text not null,
  entity_id text not null,
  scope text not null check (scope in ('build_recommendations','composition_recommendations','training','simulation_readiness')),
  status text not null default 'pending' check (status in ('pending','resolved','ignored')),
  reason text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  resolved_at timestamptz,
  unique(knowledge_version_id, scope)
);

create index if not exists echo_brain_knowledge_invalidations_pending_idx
  on public.echo_brain_knowledge_invalidations(status, scope, created_at desc);

create table if not exists public.echo_brain_semantic_edges (
  id bigint generated by default as identity primary key,
  season_id uuid references public.seasons(id) on delete set null,
  game_version text,
  source_type text not null,
  source_id text not null,
  relation text not null,
  target_type text not null,
  target_id text not null,
  weight numeric(7,5) not null default 1 check (weight >= -1 and weight <= 1),
  confidence numeric(7,5) not null default 1 check (confidence >= 0 and confidence <= 1),
  evidence jsonb not null default '{}'::jsonb,
  source_fingerprint text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(season_id, source_type, source_id, relation, target_type, target_id, source_fingerprint)
);

create index if not exists echo_brain_semantic_edges_source_idx
  on public.echo_brain_semantic_edges(source_type, source_id, active);
create index if not exists echo_brain_semantic_edges_target_idx
  on public.echo_brain_semantic_edges(target_type, target_id, active);

create table if not exists public.echo_brain_decision_audits (
  id uuid primary key default gen_random_uuid(),
  decision_type text not null check (decision_type in ('composition','build','item_fit','counterfactual','investigation')),
  entity_key text not null,
  semantic_schema text,
  model_id uuid references public.composition_model_versions(id) on delete set null,
  model_version integer,
  scores jsonb not null default '{}'::jsonb,
  confidence jsonb not null default '{}'::jsonb,
  explanation jsonb not null default '{}'::jsonb,
  provenance jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists echo_brain_decision_audits_created_idx
  on public.echo_brain_decision_audits(decision_type, created_at desc);

create table if not exists public.echo_brain_counterfactual_audits (
  id uuid primary key default gen_random_uuid(),
  domain text not null check (domain in ('composition','build','equipment')),
  baseline_key text not null,
  candidate_key text not null,
  baseline_score numeric,
  candidate_score numeric,
  delta numeric,
  changed_components jsonb not null default '{}'::jsonb,
  confidence jsonb not null default '{}'::jsonb,
  semantic_schema text,
  model_id uuid references public.composition_model_versions(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists echo_brain_counterfactual_audits_created_idx
  on public.echo_brain_counterfactual_audits(domain, created_at desc);

-- Exposição é propositalmente anônima: registra que o produto mostrou a
-- recomendação, não quem a viu. Isso evita transformar popularidade induzida em
-- evidência orgânica e não cria um identificador comportamental do usuário.
create table if not exists public.echo_brain_recommendation_exposures (
  id uuid primary key default gen_random_uuid(),
  surface text not null check (surface in ('composition_lab','build_lab','comparison','other')),
  entity_key text not null,
  semantic_schema text,
  model_id uuid references public.composition_model_versions(id) on delete set null,
  model_version integer,
  brain_influence numeric(7,5) not null default 0 check (brain_influence >= 0 and brain_influence <= 0.55),
  context_hash text,
  created_at timestamptz not null default now()
);

create index if not exists echo_brain_recommendation_exposures_entity_idx
  on public.echo_brain_recommendation_exposures(entity_key, created_at desc);

alter table public.composition_match_observations
  add column if not exists recommendation_exposure_id uuid references public.echo_brain_recommendation_exposures(id) on delete set null,
  add column if not exists observation_provenance text not null default 'unknown'
    check (observation_provenance in ('organic','brain_exposed','unknown','admin_import'));

create index if not exists composition_match_observations_exposure_idx
  on public.composition_match_observations(recommendation_exposure_id)
  where recommendation_exposure_id is not null;

alter table public.echo_brain_knowledge_versions enable row level security;
alter table public.echo_brain_knowledge_change_queue enable row level security;
alter table public.echo_brain_knowledge_invalidations enable row level security;
alter table public.echo_brain_semantic_edges enable row level security;
alter table public.echo_brain_decision_audits enable row level security;
alter table public.echo_brain_counterfactual_audits enable row level security;
alter table public.echo_brain_recommendation_exposures enable row level security;

revoke all on table public.echo_brain_knowledge_versions from anon, authenticated;
revoke all on table public.echo_brain_knowledge_change_queue from anon, authenticated;
revoke all on table public.echo_brain_knowledge_invalidations from anon, authenticated;
revoke all on table public.echo_brain_semantic_edges from anon, authenticated;
revoke all on table public.echo_brain_decision_audits from anon, authenticated;
revoke all on table public.echo_brain_counterfactual_audits from anon, authenticated;
revoke all on table public.echo_brain_recommendation_exposures from anon, authenticated;

grant select, update on table public.echo_brain_knowledge_change_queue to authenticated;
grant select on table public.echo_brain_knowledge_versions to authenticated;
grant select, update on table public.echo_brain_knowledge_invalidations to authenticated;
grant select, insert, update on table public.echo_brain_semantic_edges to authenticated;
grant select on table public.echo_brain_decision_audits to authenticated;
grant select on table public.echo_brain_counterfactual_audits to authenticated;

create policy echo_brain_knowledge_versions_admin_select
  on public.echo_brain_knowledge_versions for select to authenticated
  using (public.echo_is_admin());
create policy echo_brain_knowledge_queue_admin
  on public.echo_brain_knowledge_change_queue for all to authenticated
  using (public.echo_is_admin()) with check (public.echo_is_admin());
create policy echo_brain_knowledge_invalidations_admin
  on public.echo_brain_knowledge_invalidations for all to authenticated
  using (public.echo_is_admin()) with check (public.echo_is_admin());
create policy echo_brain_semantic_edges_admin
  on public.echo_brain_semantic_edges for all to authenticated
  using (public.echo_is_admin()) with check (public.echo_is_admin());
create policy echo_brain_decision_audits_admin_select
  on public.echo_brain_decision_audits for select to authenticated
  using (public.echo_is_admin());
create policy echo_brain_counterfactual_audits_admin_select
  on public.echo_brain_counterfactual_audits for select to authenticated
  using (public.echo_is_admin());

create or replace function public.echo_brain_mark_hero_profile_dirty()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_hero_id text;
  v_reason jsonb;
begin
  if tg_table_name = 'heroes' then
    v_hero_id := case when tg_op='DELETE' then old.id::text else new.id::text end;
  else
    v_hero_id := case when tg_op='DELETE' then old.hero_id::text else new.hero_id::text end;
  end if;
  if coalesce(v_hero_id,'')='' then return null; end if;
  v_reason := jsonb_build_object('table',tg_table_name,'operation',tg_op,'at',now());
  insert into public.echo_brain_knowledge_change_queue(entity_type,entity_id,source,reasons,status,updated_at,resolved_at)
  values('hero_profile',v_hero_id,'database-trigger',jsonb_build_array(v_reason),'pending',now(),null)
  on conflict(entity_type,entity_id) do update set
    reasons=public.echo_brain_knowledge_change_queue.reasons || jsonb_build_array(v_reason),
    source='database-trigger',status='pending',updated_at=now(),resolved_at=null;
  return null;
end;
$$;

revoke all on function public.echo_brain_mark_hero_profile_dirty() from public, anon, authenticated;

drop trigger if exists trg_echo_brain_hero_profile_dirty on public.heroes;
create trigger trg_echo_brain_hero_profile_dirty after insert or update or delete on public.heroes
for each row execute function public.echo_brain_mark_hero_profile_dirty();

drop trigger if exists trg_echo_brain_hero_skill_dirty on public.hero_skills;
create trigger trg_echo_brain_hero_skill_dirty after insert or update or delete on public.hero_skills
for each row execute function public.echo_brain_mark_hero_profile_dirty();

drop trigger if exists trg_echo_brain_hero_base_stats_dirty on public.hero_base_stats;
create trigger trg_echo_brain_hero_base_stats_dirty after insert or update or delete on public.hero_base_stats
for each row execute function public.echo_brain_mark_hero_profile_dirty();

drop trigger if exists trg_echo_brain_hero_weapon_stats_dirty on public.hero_weapon_stats;
create trigger trg_echo_brain_hero_weapon_stats_dirty after insert or update or delete on public.hero_weapon_stats
for each row execute function public.echo_brain_mark_hero_profile_dirty();

-- Instalação fail-safe: nenhum herói existente começa falsamente como atual.
insert into public.echo_brain_knowledge_change_queue(entity_type,entity_id,source,reasons,status)
select 'hero_profile', h.id::text, 'migration-bootstrap',
       jsonb_build_array(jsonb_build_object('operation','baseline_required','at',now())), 'pending'
from public.heroes h
on conflict(entity_type,entity_id) do nothing;

create or replace function public.admin_echo_brain_reconcile_knowledge(p_limit integer default 100)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  r record;
  v_snapshot jsonb;
  v_previous public.echo_brain_knowledge_versions%rowtype;
  v_fingerprint text;
  v_version integer;
  v_version_id bigint;
  v_season_id uuid;
  v_game_version text;
  v_changed boolean;
  v_processed integer := 0;
  v_versioned integer := 0;
  v_unchanged integer := 0;
begin
  if not public.echo_is_admin() then raise exception 'admin_required' using errcode='42501'; end if;
  select id,game_version into v_season_id,v_game_version from public.seasons
  where active is true order by starts_at desc nulls last,created_at desc limit 1;

  for r in
    select * from public.echo_brain_knowledge_change_queue
    where status in ('pending','processing') order by updated_at asc limit greatest(1,least(coalesce(p_limit,100),500))
    for update skip locked
  loop
    v_processed := v_processed + 1;
    update public.echo_brain_knowledge_change_queue set status='processing',updated_at=now()
    where entity_type=r.entity_type and entity_id=r.entity_id;

    if r.entity_type='hero_profile' then
      select jsonb_build_object(
        'hero', to_jsonb(h),
        'skills', coalesce((select jsonb_agg(to_jsonb(s) order by s.display_order,s.id) from public.hero_skills s where s.hero_id=h.id),'[]'::jsonb),
        'baseStats', coalesce((select jsonb_object_agg(b.stat_key,b.value order by b.stat_key) from public.hero_base_stats b where b.hero_id=h.id),'{}'::jsonb),
        'weaponStats', coalesce((select jsonb_object_agg(w.stat_key,w.value order by w.stat_key) from public.hero_weapon_stats w where w.hero_id=h.id),'{}'::jsonb)
      ) into v_snapshot
      from public.heroes h where h.id::text=r.entity_id;
      if v_snapshot is null then
        v_snapshot := jsonb_build_object('hero',jsonb_build_object('id',r.entity_id,'deleted',true),'skills','[]'::jsonb,'baseStats','{}'::jsonb,'weaponStats','{}'::jsonb);
      end if;
    else
      v_snapshot := jsonb_build_object('entityType',r.entity_type,'entityId',r.entity_id);
    end if;

    v_fingerprint := md5(v_snapshot::text);
    select * into v_previous from public.echo_brain_knowledge_versions
    where entity_type=r.entity_type and entity_id=r.entity_id order by version desc limit 1;
    v_changed := not found or v_previous.semantic_fingerprint<>v_fingerprint;

    if not v_changed then
      update public.echo_brain_knowledge_change_queue set status='resolved',resolved_at=now(),updated_at=now()
      where entity_type=r.entity_type and entity_id=r.entity_id;
      v_unchanged := v_unchanged + 1;
      continue;
    end if;

    perform pg_advisory_xact_lock(hashtextextended(r.entity_type||':'||r.entity_id,0));
    select coalesce(max(version),0)+1 into v_version from public.echo_brain_knowledge_versions
    where entity_type=r.entity_type and entity_id=r.entity_id;

    insert into public.echo_brain_knowledge_versions(
      entity_type,entity_id,version,season_id,game_version,source,change_class,semantic_fingerprint,snapshot,created_by
    ) values (
      r.entity_type,r.entity_id,v_version,v_season_id,v_game_version,r.source,
      case when v_previous.id is null then 'baseline' else 'knowledge_change' end,
      v_fingerprint,v_snapshot,auth.uid()
    ) returning id into v_version_id;

    if v_previous.id is not null then
      insert into public.echo_brain_knowledge_invalidations(knowledge_version_id,entity_type,entity_id,scope,reason,metadata)
      values
        (v_version_id,r.entity_type,r.entity_id,'build_recommendations','hero_profile_changed',jsonb_build_object('gameVersion',v_game_version)),
        (v_version_id,r.entity_type,r.entity_id,'composition_recommendations','hero_profile_changed',jsonb_build_object('gameVersion',v_game_version)),
        (v_version_id,r.entity_type,r.entity_id,'training','hero_profile_changed',jsonb_build_object('gameVersion',v_game_version)),
        (v_version_id,r.entity_type,r.entity_id,'simulation_readiness','hero_profile_changed',jsonb_build_object('gameVersion',v_game_version))
      on conflict(knowledge_version_id,scope) do nothing;
    end if;

    update public.echo_brain_knowledge_change_queue set status='resolved',resolved_at=now(),updated_at=now()
    where entity_type=r.entity_type and entity_id=r.entity_id;
    v_versioned := v_versioned + 1;
  end loop;

  return jsonb_build_object('ok',true,'processed',v_processed,'versioned',v_versioned,'unchanged',v_unchanged,'seasonId',v_season_id,'gameVersion',v_game_version);
end;
$$;

revoke all on function public.admin_echo_brain_reconcile_knowledge(integer) from public, anon;
grant execute on function public.admin_echo_brain_reconcile_knowledge(integer) to authenticated;

create or replace view public.echo_brain_current_knowledge
with (security_invoker=true) as
select 'hero_profile'::text as entity_type, v.entity_id, v.version, v.game_version,
       v.semantic_fingerprint, v.created_at, v.snapshot
from public.echo_brain_knowledge_versions v
join (
  select entity_type,entity_id,max(version) version from public.echo_brain_knowledge_versions group by entity_type,entity_id
) x on x.entity_type=v.entity_type and x.entity_id=v.entity_id and x.version=v.version
union all
select 'equipment'::text, e.equipment_id, e.version, e.game_version,
       e.semantic_fingerprint, e.created_at, e.after_snapshot
from public.equipment_brain_versions e
join (
  select equipment_id,max(version) version from public.equipment_brain_versions group by equipment_id
) y on y.equipment_id=e.equipment_id and y.version=e.version;

revoke all on public.echo_brain_current_knowledge from anon, authenticated;
grant select on public.echo_brain_current_knowledge to authenticated;

create or replace function public.admin_echo_brain_knowledge_snapshot()
returns jsonb
language plpgsql
stable
security definer
set search_path=public,pg_temp
as $$
declare
  v_pending bigint;
  v_invalid bigint;
  v_hero_versions bigint;
  v_equipment_versions bigint;
  v_edges bigint;
begin
  if not public.echo_is_admin() then raise exception 'admin_required' using errcode='42501'; end if;
  select count(*) into v_pending from public.echo_brain_knowledge_change_queue where status in ('pending','processing');
  select count(*) into v_invalid from public.echo_brain_knowledge_invalidations where status='pending';
  select count(*) into v_hero_versions from public.echo_brain_knowledge_versions where entity_type='hero_profile';
  select count(*) into v_equipment_versions from public.equipment_brain_versions;
  select count(*) into v_edges from public.echo_brain_semantic_edges where active is true;
  return jsonb_build_object('pendingKnowledge',v_pending,'pendingInvalidations',v_invalid,'heroVersions',v_hero_versions,'equipmentVersions',v_equipment_versions,'semanticEdges',v_edges);
end;
$$;
revoke all on function public.admin_echo_brain_knowledge_snapshot() from public,anon;
grant execute on function public.admin_echo_brain_knowledge_snapshot() to authenticated;

create or replace function public.echo_brain_register_recommendation_exposure(
  p_surface text,
  p_entity_key text,
  p_semantic_schema text default null,
  p_model_id uuid default null,
  p_model_version integer default null,
  p_brain_influence numeric default 0,
  p_context_hash text default null
)
returns uuid
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare v_id uuid;
begin
  if coalesce(p_surface,'') not in ('composition_lab','build_lab','comparison','other') then raise exception 'invalid_surface'; end if;
  if coalesce(trim(p_entity_key),'')='' then raise exception 'entity_key_required'; end if;
  insert into public.echo_brain_recommendation_exposures(surface,entity_key,semantic_schema,model_id,model_version,brain_influence,context_hash)
  values(p_surface,p_entity_key,p_semantic_schema,p_model_id,p_model_version,least(.55,greatest(0,coalesce(p_brain_influence,0))),p_context_hash)
  returning id into v_id;
  return v_id;
end;
$$;
revoke all on function public.echo_brain_register_recommendation_exposure(text,text,text,uuid,integer,numeric,text) from public;
grant execute on function public.echo_brain_register_recommendation_exposure(text,text,text,uuid,integer,numeric,text) to anon,authenticated;

create or replace function public.echo_brain_observation_provenance_guard()
returns trigger
language plpgsql
set search_path=public,pg_temp
as $$
begin
  if new.recommendation_exposure_id is not null then
    new.recommended_by_brain := true;
    new.observation_provenance := 'brain_exposed';
  elsif new.observation_provenance='organic' then
    new.recommended_by_brain := false;
  elsif new.recommended_by_brain is true and new.observation_provenance='unknown' then
    new.observation_provenance := 'brain_exposed';
  end if;
  return new;
end;
$$;

drop trigger if exists trg_echo_brain_observation_provenance on public.composition_match_observations;
create trigger trg_echo_brain_observation_provenance before insert or update on public.composition_match_observations
for each row execute function public.echo_brain_observation_provenance_guard();

-- Readiness do futuro simulador: somente diagnóstico. Não habilita simulador.
create or replace function public.admin_echo_brain_simulation_readiness()
returns jsonb
language plpgsql
stable
security definer
set search_path=public,pg_temp
as $$
declare v_knowledge bigint; v_equipment bigint; v_sim bigint;
begin
  if not public.echo_is_admin() then raise exception 'admin_required' using errcode='42501'; end if;
  select count(*) into v_knowledge from public.echo_brain_knowledge_change_queue where status in ('pending','processing');
  select count(*) into v_equipment from public.equipment_brain_change_queue where status in ('pending','processing');
  select count(*) into v_sim from public.echo_brain_knowledge_invalidations where status='pending' and scope='simulation_readiness';
  return jsonb_build_object(
    'ready', (v_knowledge=0 and v_equipment=0 and v_sim=0),
    'simulatorEnabled', false,
    'knowledgePending',v_knowledge,
    'equipmentPending',v_equipment,
    'simulationInvalidations',v_sim,
    'contract','verified-rules-first-v1'
  );
end;
$$;
revoke all on function public.admin_echo_brain_simulation_readiness() from public,anon;
grant execute on function public.admin_echo_brain_simulation_readiness() to authenticated;

comment on table public.echo_brain_knowledge_versions is 'Fonte de verdade versionada do Echo Brain para perfis completos de herói e regras verificadas.';
comment on table public.echo_brain_semantic_edges is 'Grafo semântico auditável: entidade -> relação -> entidade/efeito, com peso, confiança e evidência.';
comment on table public.echo_brain_recommendation_exposures is 'Proveniência anônima de recomendações exibidas, usada para impedir feedback loop no treino.';
comment on function public.admin_echo_brain_simulation_readiness() is 'Gate somente de leitura: o simulador continua desabilitado até as regras verificadas estarem completas.';
