-- Classificações persistentes para efeitos de equipamento que precisam de decisão humana.
-- Permite distinguir efeitos reais sem base pública de erros de cadastro sem alterar o motor.

create table if not exists public.equipment_attribute_classifications (
  id bigint generated by default as identity primary key,
  normalized_key text not null unique,
  raw_label text not null,
  classification text not null check (classification in ('external_data_required','informational')),
  display_label text,
  reason text,
  missing_data text,
  public_note text,
  active boolean not null default true,
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists equipment_attribute_classifications_active_idx
  on public.equipment_attribute_classifications (active, classification, normalized_key);

alter table public.equipment_attribute_classifications enable row level security;

drop policy if exists equipment_attribute_classifications_public_select on public.equipment_attribute_classifications;
create policy equipment_attribute_classifications_public_select
  on public.equipment_attribute_classifications
  for select
  to anon, authenticated
  using (active = true);

drop policy if exists equipment_attribute_classifications_authenticated_insert on public.equipment_attribute_classifications;
create policy equipment_attribute_classifications_authenticated_insert
  on public.equipment_attribute_classifications
  for insert
  to authenticated
  with check (true);

drop policy if exists equipment_attribute_classifications_authenticated_update on public.equipment_attribute_classifications;
create policy equipment_attribute_classifications_authenticated_update
  on public.equipment_attribute_classifications
  for update
  to authenticated
  using (true)
  with check (true);

drop policy if exists equipment_attribute_classifications_authenticated_delete on public.equipment_attribute_classifications;
create policy equipment_attribute_classifications_authenticated_delete
  on public.equipment_attribute_classifications
  for delete
  to authenticated
  using (true);

-- Caso real já confirmado: o efeito existe, mas o jogo não expõe a base necessária.
insert into public.equipment_attribute_classifications (
  normalized_key,
  raw_label,
  classification,
  display_label,
  reason,
  missing_data,
  public_note
) values (
  'tempo_de_troca_de_modo_da_arma_primaria_percentual',
  'Tempo de troca de modo da arma primária percentual',
  'external_data_required',
  'Tempo de troca de modo da arma primária',
  'O efeito é real, mas o jogo não disponibiliza publicamente a base e a regra interna necessárias para calcular o tempo final com segurança.',
  'Tempo-base oficial da troca de modo da arma primária e a regra exata de aplicação.',
  'Este efeito existe no equipamento, porém o jogo não disponibiliza os dados-base necessários para calcular seu impacto final com segurança.'
)
on conflict (normalized_key) do update set
  classification = excluded.classification,
  display_label = excluded.display_label,
  reason = excluded.reason,
  missing_data = excluded.missing_data,
  public_note = excluded.public_note,
  active = true,
  updated_at = now();
